name: ag_ui_example
description: Example application demonstrating AG-UI Dart SDK features
publish_to: 'none' # Example app, not published
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  ag_ui:
    path: ../

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0