name: ag_ui
description: Dart SDK for AG-UI protocol - standardizing agent-user interactions
version: 0.1.0
homepage: https://github.com/ag-ui-protocol/ag-ui

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0