name: ChatAppSwiftUI
options:
  bundleIdPrefix: com.agui.example
  deploymentTarget:
    iOS: 17.0
packages:
  MarkdownUI:
    url: https://github.com/gonzalezreal/MarkdownUI.git
    from: 2.4.1
settings:
  base:
    SWIFT_VERSION: 5.9
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
targets:
  ChatAppSwiftUI:
    type: application
    platform: iOS
    deploymentTarget: 17.0
    sources:
      - path: Sources
    resources:
      - path: Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.agui.example.chatappswiftui
    dependencies:
      - package: MarkdownUI
        product: MarkdownUI
      - framework: ../shared/build/XCFrameworks/release/shared.xcframework
        embed: true
        codeSign: true
    info:
      path: Resources/Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
        UIUserInterfaceStyle: Automatic
        UIApplicationSupportsIndirectInputEvents: true
  ChatAppSwiftUITests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: 17.0
    sources:
      - path: Tests
    dependencies:
      - target: ChatAppSwiftUI
