import { defineEventTrace } from "../../event-trace-test";

// Generated by the event trace updater.
// Reason: CopilotKit 1.76.0 is an AG-UI 1.0 client: RunAgentInput now carries protocolVersion "1.0"
// Before accepting changes, verify whether the implementation regressed.
const shared1 =
  '{"steps":[{"description":"Gather ingredients: cocoa, butter, eggs, sugar, flour","status":"pending"},{"description":"Melt butter and mix with cocoa and sugar","status":"pending"},{"description":"Add eggs and flour, mix until smooth","status":"pending"},{"description":"Pour into greased pan and bake at 350F for 25 minutes","status":"pending"}]}' as const;
const shared2 =
  '{"steps":[{"description":"Design and build a spacecraft capable of Mars transit","status":"pending"},{"description":"Assemble crew and run mission simulations","status":"pending"},{"description":"Launch from Earth and navigate to Mars","status":"pending"},{"description":"Land on Mars surface and establish base camp","status":"pending"}]}' as const;
const shared3 = {
  steps: [
    {
      description: "Gather ingredients: cocoa, butter, eggs, sugar, flour",
      status: "completed",
    },
    {
      description: "Melt butter and mix with cocoa and sugar",
      status: "completed",
    },
    {
      description: "Add eggs and flour, mix until smooth",
      status: "completed",
    },
    {
      description: "Pour into greased pan and bake at 350F for 25 minutes",
      status: "completed",
    },
  ],
  tools: [],
  messages: [
    {
      id: "id-3",
      content: "Hi",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
    },
    {
      content: "Hello! How can I assist you today?",
      additional_kwargs: {},
      response_metadata: {
        model_provider: "openai",
        usage: {
          prompt_tokens: 111,
          completion_tokens: 9,
          total_tokens: 120,
        },
      },
      tool_call_chunks: [],
      id: "id-4",
      usage_metadata: {
        input_tokens: 111,
        output_tokens: 9,
        total_tokens: 120,
        input_token_details: {},
        output_token_details: {},
      },
      invalid_tool_calls: [],
      tool_calls: [],
      type: "ai",
    },
    {
      id: "id-7",
      content: "Give me a plan to make brownies",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
    },
  ],
} as const;
const shared4 = {
  steps: [
    {
      description: "Gather ingredients: cocoa, butter, eggs, sugar, flour",
      status: "completed",
    },
    {
      description: "Melt butter and mix with cocoa and sugar",
      status: "completed",
    },
    {
      description: "Add eggs and flour, mix until smooth",
      status: "completed",
    },
    {
      description: "Pour into greased pan and bake at 350F for 25 minutes",
      status: "pending",
    },
  ],
  tools: [],
  messages: [
    {
      id: "id-3",
      content: "Hi",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
    },
    {
      content: "Hello! How can I assist you today?",
      additional_kwargs: {},
      response_metadata: {
        model_provider: "openai",
        usage: {
          prompt_tokens: 111,
          completion_tokens: 9,
          total_tokens: 120,
        },
      },
      tool_call_chunks: [],
      id: "id-4",
      usage_metadata: {
        input_tokens: 111,
        output_tokens: 9,
        total_tokens: 120,
        input_token_details: {},
        output_token_details: {},
      },
      invalid_tool_calls: [],
      tool_calls: [],
      type: "ai",
    },
    {
      id: "id-7",
      content: "Give me a plan to make brownies",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
    },
  ],
} as const;
const shared5 = {
  steps: [
    {
      description: "Gather ingredients: cocoa, butter, eggs, sugar, flour",
      status: "completed",
    },
    {
      description: "Melt butter and mix with cocoa and sugar",
      status: "completed",
    },
    {
      description: "Add eggs and flour, mix until smooth",
      status: "pending",
    },
    {
      description: "Pour into greased pan and bake at 350F for 25 minutes",
      status: "pending",
    },
  ],
  tools: [],
  messages: [
    {
      id: "id-3",
      content: "Hi",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
    },
    {
      content: "Hello! How can I assist you today?",
      additional_kwargs: {},
      response_metadata: {
        model_provider: "openai",
        usage: {
          prompt_tokens: 111,
          completion_tokens: 9,
          total_tokens: 120,
        },
      },
      tool_call_chunks: [],
      id: "id-4",
      usage_metadata: {
        input_tokens: 111,
        output_tokens: 9,
        total_tokens: 120,
        input_token_details: {},
        output_token_details: {},
      },
      invalid_tool_calls: [],
      tool_calls: [],
      type: "ai",
    },
    {
      id: "id-7",
      content: "Give me a plan to make brownies",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
    },
  ],
} as const;
const shared6 = {
  steps: [
    {
      description: "Gather ingredients: cocoa, butter, eggs, sugar, flour",
      status: "completed",
    },
    {
      description: "Melt butter and mix with cocoa and sugar",
      status: "pending",
    },
    {
      description: "Add eggs and flour, mix until smooth",
      status: "pending",
    },
    {
      description: "Pour into greased pan and bake at 350F for 25 minutes",
      status: "pending",
    },
  ],
  tools: [],
  messages: [
    {
      id: "id-3",
      content: "Hi",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
    },
    {
      content: "Hello! How can I assist you today?",
      additional_kwargs: {},
      response_metadata: {
        model_provider: "openai",
        usage: {
          prompt_tokens: 111,
          completion_tokens: 9,
          total_tokens: 120,
        },
      },
      tool_call_chunks: [],
      id: "id-4",
      usage_metadata: {
        input_tokens: 111,
        output_tokens: 9,
        total_tokens: 120,
        input_token_details: {},
        output_token_details: {},
      },
      invalid_tool_calls: [],
      tool_calls: [],
      type: "ai",
    },
    {
      id: "id-7",
      content: "Give me a plan to make brownies",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
    },
  ],
} as const;
const shared7 = {
  steps: [
    {
      description: "Design and build a spacecraft capable of Mars transit",
      status: "completed",
    },
    {
      description: "Assemble crew and run mission simulations",
      status: "completed",
    },
    {
      description: "Launch from Earth and navigate to Mars",
      status: "completed",
    },
    {
      description: "Land on Mars surface and establish base camp",
      status: "completed",
    },
  ],
  tools: [],
  messages: [
    {
      id: "id-3",
      content: "Hi",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
    },
    {
      content: "Hello! How can I assist you today?",
      additional_kwargs: {},
      response_metadata: {
        model_provider: "openai",
        usage: {
          prompt_tokens: 111,
          completion_tokens: 9,
          total_tokens: 120,
        },
      },
      tool_call_chunks: [],
      id: "id-4",
      usage_metadata: {
        input_tokens: 111,
        output_tokens: 9,
        total_tokens: 120,
        input_token_details: {},
        output_token_details: {},
      },
      invalid_tool_calls: [],
      tool_calls: [],
      type: "ai",
    },
    {
      id: "id-7",
      content: "Go to Mars",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
    },
  ],
} as const;
const shared8 = {
  steps: [
    {
      description: "Design and build a spacecraft capable of Mars transit",
      status: "completed",
    },
    {
      description: "Assemble crew and run mission simulations",
      status: "completed",
    },
    {
      description: "Launch from Earth and navigate to Mars",
      status: "completed",
    },
    {
      description: "Land on Mars surface and establish base camp",
      status: "pending",
    },
  ],
  tools: [],
  messages: [
    {
      id: "id-3",
      content: "Hi",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
    },
    {
      content: "Hello! How can I assist you today?",
      additional_kwargs: {},
      response_metadata: {
        model_provider: "openai",
        usage: {
          prompt_tokens: 111,
          completion_tokens: 9,
          total_tokens: 120,
        },
      },
      tool_call_chunks: [],
      id: "id-4",
      usage_metadata: {
        input_tokens: 111,
        output_tokens: 9,
        total_tokens: 120,
        input_token_details: {},
        output_token_details: {},
      },
      invalid_tool_calls: [],
      tool_calls: [],
      type: "ai",
    },
    {
      id: "id-7",
      content: "Go to Mars",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
    },
  ],
} as const;
const shared9 = {
  steps: [
    {
      description: "Design and build a spacecraft capable of Mars transit",
      status: "completed",
    },
    {
      description: "Assemble crew and run mission simulations",
      status: "completed",
    },
    {
      description: "Launch from Earth and navigate to Mars",
      status: "pending",
    },
    {
      description: "Land on Mars surface and establish base camp",
      status: "pending",
    },
  ],
  tools: [],
  messages: [
    {
      id: "id-3",
      content: "Hi",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
    },
    {
      content: "Hello! How can I assist you today?",
      additional_kwargs: {},
      response_metadata: {
        model_provider: "openai",
        usage: {
          prompt_tokens: 111,
          completion_tokens: 9,
          total_tokens: 120,
        },
      },
      tool_call_chunks: [],
      id: "id-4",
      usage_metadata: {
        input_tokens: 111,
        output_tokens: 9,
        total_tokens: 120,
        input_token_details: {},
        output_token_details: {},
      },
      invalid_tool_calls: [],
      tool_calls: [],
      type: "ai",
    },
    {
      id: "id-7",
      content: "Go to Mars",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
    },
  ],
} as const;
const shared10 = {
  steps: [
    {
      description: "Design and build a spacecraft capable of Mars transit",
      status: "completed",
    },
    {
      description: "Assemble crew and run mission simulations",
      status: "pending",
    },
    {
      description: "Launch from Earth and navigate to Mars",
      status: "pending",
    },
    {
      description: "Land on Mars surface and establish base camp",
      status: "pending",
    },
  ],
  tools: [],
  messages: [
    {
      id: "id-3",
      content: "Hi",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
    },
    {
      content: "Hello! How can I assist you today?",
      additional_kwargs: {},
      response_metadata: {
        model_provider: "openai",
        usage: {
          prompt_tokens: 111,
          completion_tokens: 9,
          total_tokens: 120,
        },
      },
      tool_call_chunks: [],
      id: "id-4",
      usage_metadata: {
        input_tokens: 111,
        output_tokens: 9,
        total_tokens: 120,
        input_token_details: {},
        output_token_details: {},
      },
      invalid_tool_calls: [],
      tool_calls: [],
      type: "ai",
    },
    {
      id: "id-7",
      content: "Go to Mars",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
    },
  ],
} as const;
const shared11 = {
  type: "STATE_SNAPSHOT",
  snapshot: {
    steps: [],
    tools: [],
    messages: [
      {
        id: "id-3",
        content: "Hi",
        additional_kwargs: {},
        response_metadata: {},
        type: "human",
      },
      {
        content: "Hello! How can I assist you today?",
        additional_kwargs: {},
        response_metadata: {
          model_provider: "openai",
          usage: {
            prompt_tokens: 111,
            completion_tokens: 9,
            total_tokens: 120,
          },
        },
        tool_call_chunks: [],
        tool_calls: [],
        id: "id-4",
        usage_metadata: {
          input_tokens: 111,
          output_tokens: 9,
          total_tokens: 120,
          input_token_details: {},
          output_token_details: {},
        },
        invalid_tool_calls: [],
        type: "ai",
      },
    ],
  },
} as const;
const shared12 = {
  name: "generate_task_steps_generative_ui",
  arguments: shared1,
} as const;
const shared13 = {
  name: "generate_task_steps_generative_ui",
  arguments: shared2,
} as const;
const shared14 = {
  type: "RUN_STARTED",
  threadId: "id-1",
  runId: "id-2",
  input: {
    threadId: "id-1",
    runId: "id-2",
    protocolVersion: "1.0",
    state: {},
    messages: [
      {
        id: "id-3",
        role: "user",
        content: "Hi",
      },
    ],
    tools: [],
    context: [],
    forwardedProps: {},
  },
} as const;
const shared15 = {
  type: "MESSAGES_SNAPSHOT",
  messages: [
    {
      id: "id-3",
      role: "user",
      content: "Hi",
    },
    {
      id: "id-4",
      role: "assistant",
      content: "Hello! How can I assist you today?",
      toolCalls: [],
    },
  ],
} as const;
const shared16 = {
  type: "STATE_SNAPSHOT",
  snapshot: {
    steps: [],
    tools: [],
    messages: [
      {
        id: "id-3",
        content: "Hi",
        additional_kwargs: {},
        response_metadata: {},
        type: "human",
      },
    ],
  },
} as const;
const shared17 = {
  type: "CUSTOM",
  name: "PredictState",
  value: [
    {
      state_key: "steps",
      tool: "generate_task_steps_generative_ui",
      tool_argument: "steps",
    },
  ],
} as const;
const shared18 = {
  content: "Steps executed.",
  tool_call_id: "id-8",
  additional_kwargs: {},
  response_metadata: {},
  id: "id-11",
  type: "tool",
} as const;
const shared19 = {
  type: "TOOL_CALL_START",
  toolCallId: "id-8",
  toolCallName: "generate_task_steps_generative_ui",
  parentMessageId: "id-9",
} as const;
const shared20 = {
  id: "id-10",
  role: "assistant",
  content: "Done! I've completed that for you.",
  toolCalls: [],
} as const;
const shared21 = {
  type: "TEXT_MESSAGE_CONTENT",
  messageId: "id-10",
  delta: "Done! I've completed",
} as const;
const shared22 = {
  type: "TEXT_MESSAGE_CONTENT",
  messageId: "id-4",
  delta: "Hello! How can I ass",
} as const;

export const agenticGenUIEventTrace = defineEventTrace(import.meta.url, {
  interactWithTheChatToGetAPlannerOnPrompt: [
    shared14,
    {
      type: "STEP_STARTED",
      stepName: "start_flow",
    },
    shared16,
    {
      type: "STEP_FINISHED",
      stepName: "start_flow",
    },
    {
      type: "STEP_STARTED",
      stepName: "chat_node",
    },
    {
      type: "TEXT_MESSAGE_START",
      messageId: "id-4",
      role: "assistant",
    },
    shared22,
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: "ist you today?",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-4",
    },
    shared11,
    {
      type: "STEP_FINISHED",
      stepName: "chat_node",
    },
    shared15,
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-5",
    },
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-6",
      input: {
        threadId: "id-1",
        runId: "id-6",
        protocolVersion: "1.0",
        state: {
          steps: [],
          tools: [],
          messages: [
            {
              id: "id-3",
              content: "Hi",
              additional_kwargs: {},
              response_metadata: {},
              type: "human",
            },
            {
              content: "Hello! How can I assist you today?",
              additional_kwargs: {},
              response_metadata: {
                model_provider: "openai",
                usage: {
                  prompt_tokens: 111,
                  completion_tokens: 9,
                  total_tokens: 120,
                },
              },
              tool_call_chunks: [],
              tool_calls: [],
              id: "id-4",
              usage_metadata: {
                input_tokens: 111,
                output_tokens: 9,
                total_tokens: 120,
                input_token_details: {},
                output_token_details: {},
              },
              invalid_tool_calls: [],
              type: "ai",
            },
          ],
        },
        messages: [
          {
            id: "id-7",
            role: "user",
            content: "Give me a plan to make brownies",
          },
        ],
        tools: [],
        context: [],
        forwardedProps: {},
      },
    },
    {
      type: "STEP_STARTED",
      stepName: "start_flow",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        steps: [],
        tools: [],
        messages: [
          {
            id: "id-3",
            content: "Hi",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
          },
          {
            content: "Hello! How can I assist you today?",
            additional_kwargs: {},
            response_metadata: {
              model_provider: "openai",
              usage: {
                prompt_tokens: 111,
                completion_tokens: 9,
                total_tokens: 120,
              },
            },
            tool_call_chunks: [],
            id: "id-4",
            usage_metadata: {
              input_tokens: 111,
              output_tokens: 9,
              total_tokens: 120,
              input_token_details: {},
              output_token_details: {},
            },
            invalid_tool_calls: [],
            tool_calls: [],
            type: "ai",
          },
          {
            id: "id-7",
            content: "Give me a plan to make brownies",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
          },
        ],
      },
    },
    {
      type: "STEP_FINISHED",
      stepName: "start_flow",
    },
    {
      type: "STEP_STARTED",
      stepName: "chat_node",
    },
    shared17,
    shared19,
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: '{"steps":[{"descript',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: 'ion":"Gather ingredi',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: "ents: cocoa, butter,",
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: ' eggs, sugar, flour"',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: ',"status":"pending"}',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: ',{"description":"Mel',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: "t butter and mix wit",
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: 'h cocoa and sugar","',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: 'status":"pending"},{',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: '"description":"Add e',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: "ggs and flour, mix u",
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: 'ntil smooth","status',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: '":"pending"},{"descr',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: 'iption":"Pour into g',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: "reased pan and bake ",
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: "at 350F for 25 minut",
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: 'es","status":"pendin',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: 'g"}]}',
    },
    {
      type: "TOOL_CALL_END",
      toolCallId: "id-8",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: shared6,
    },
    {
      type: "CUSTOM",
      name: "manually_emit_state",
      value: shared6,
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: shared5,
    },
    {
      type: "CUSTOM",
      name: "manually_emit_state",
      value: shared5,
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: shared4,
    },
    {
      type: "CUSTOM",
      name: "manually_emit_state",
      value: shared4,
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: shared3,
    },
    {
      type: "CUSTOM",
      name: "manually_emit_state",
      value: shared3,
    },
    {
      type: "TEXT_MESSAGE_START",
      messageId: "id-10",
      role: "assistant",
    },
    shared21,
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-10",
      delta: " that for you.",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-10",
    },
    {
      type: "STEP_FINISHED",
      stepName: "chat_node",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        steps: [
          {
            description:
              "Gather ingredients: cocoa, butter, eggs, sugar, flour",
            status: "completed",
          },
          {
            description: "Melt butter and mix with cocoa and sugar",
            status: "completed",
          },
          {
            description: "Add eggs and flour, mix until smooth",
            status: "completed",
          },
          {
            description:
              "Pour into greased pan and bake at 350F for 25 minutes",
            status: "completed",
          },
        ],
        tools: [],
        messages: [
          {
            id: "id-3",
            content: "Hi",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
          },
          {
            content: "Hello! How can I assist you today?",
            additional_kwargs: {},
            response_metadata: {
              model_provider: "openai",
              usage: {
                prompt_tokens: 111,
                completion_tokens: 9,
                total_tokens: 120,
              },
            },
            tool_call_chunks: [],
            id: "id-4",
            usage_metadata: {
              input_tokens: 111,
              output_tokens: 9,
              total_tokens: 120,
              input_token_details: {},
              output_token_details: {},
            },
            invalid_tool_calls: [],
            tool_calls: [],
            type: "ai",
          },
          {
            id: "id-7",
            content: "Give me a plan to make brownies",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
          },
          {
            content: "",
            additional_kwargs: {
              tool_calls: [
                {
                  index: 0,
                  id: "id-8",
                  type: "function",
                  function: shared12,
                },
              ],
            },
            response_metadata: {
              model_provider: "openai",
              usage: {
                prompt_tokens: 127,
                completion_tokens: 95,
                total_tokens: 222,
              },
            },
            tool_call_chunks: [
              {
                name: "generate_task_steps_generative_ui",
                args: shared1,
                id: "id-8",
                index: 0,
                type: "tool_call_chunk",
              },
            ],
            tool_calls: [
              {
                name: "generate_task_steps_generative_ui",
                args: {
                  steps: [
                    {
                      description:
                        "Gather ingredients: cocoa, butter, eggs, sugar, flour",
                      status: "pending",
                    },
                    {
                      description: "Melt butter and mix with cocoa and sugar",
                      status: "pending",
                    },
                    {
                      description: "Add eggs and flour, mix until smooth",
                      status: "pending",
                    },
                    {
                      description:
                        "Pour into greased pan and bake at 350F for 25 minutes",
                      status: "pending",
                    },
                  ],
                },
                id: "id-8",
                type: "tool_call",
              },
            ],
            id: "id-9",
            usage_metadata: {
              input_tokens: 127,
              output_tokens: 95,
              total_tokens: 222,
              input_token_details: {},
              output_token_details: {},
            },
            invalid_tool_calls: [],
            type: "ai",
          },
          shared18,
          {
            content: "Done! I've completed that for you.",
            additional_kwargs: {},
            response_metadata: {
              model_provider: "openai",
              usage: {
                prompt_tokens: 131,
                completion_tokens: 9,
                total_tokens: 140,
              },
            },
            tool_call_chunks: [],
            tool_calls: [],
            id: "id-10",
            usage_metadata: {
              input_tokens: 131,
              output_tokens: 9,
              total_tokens: 140,
              input_token_details: {},
              output_token_details: {},
            },
            invalid_tool_calls: [],
            type: "ai",
          },
        ],
      },
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hi",
        },
        {
          id: "id-4",
          role: "assistant",
          content: "Hello! How can I assist you today?",
          toolCalls: [],
        },
        {
          id: "id-7",
          role: "user",
          content: "Give me a plan to make brownies",
        },
        {
          id: "id-9",
          role: "assistant",
          content: "",
          toolCalls: [
            {
              id: "id-8",
              type: "function",
              function: shared12,
            },
          ],
        },
        {
          id: "id-11",
          role: "tool",
          content: "Steps executed.",
          toolCallId: "id-8",
        },
        shared20,
      ],
    },
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-12",
    },
  ],
  interactWithTheChatUsingPredefinedPromptsAndPerformSteps: [
    shared14,
    {
      type: "STEP_STARTED",
      stepName: "start_flow",
    },
    shared16,
    {
      type: "STEP_FINISHED",
      stepName: "start_flow",
    },
    {
      type: "STEP_STARTED",
      stepName: "chat_node",
    },
    {
      type: "TEXT_MESSAGE_START",
      messageId: "id-4",
      role: "assistant",
    },
    shared22,
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: "ist you today?",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-4",
    },
    shared11,
    {
      type: "STEP_FINISHED",
      stepName: "chat_node",
    },
    shared15,
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-5",
    },
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-6",
      input: {
        threadId: "id-1",
        runId: "id-6",
        protocolVersion: "1.0",
        state: {
          steps: [],
          tools: [],
          messages: [
            {
              id: "id-3",
              content: "Hi",
              additional_kwargs: {},
              response_metadata: {},
              type: "human",
            },
            {
              content: "Hello! How can I assist you today?",
              additional_kwargs: {},
              response_metadata: {
                model_provider: "openai",
                usage: {
                  prompt_tokens: 111,
                  completion_tokens: 9,
                  total_tokens: 120,
                },
              },
              tool_call_chunks: [],
              tool_calls: [],
              id: "id-4",
              usage_metadata: {
                input_tokens: 111,
                output_tokens: 9,
                total_tokens: 120,
                input_token_details: {},
                output_token_details: {},
              },
              invalid_tool_calls: [],
              type: "ai",
            },
          ],
        },
        messages: [
          {
            id: "id-7",
            role: "user",
            content: "Go to Mars",
          },
        ],
        tools: [],
        context: [],
        forwardedProps: {},
      },
    },
    {
      type: "STEP_STARTED",
      stepName: "start_flow",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        steps: [],
        tools: [],
        messages: [
          {
            id: "id-3",
            content: "Hi",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
          },
          {
            content: "Hello! How can I assist you today?",
            additional_kwargs: {},
            response_metadata: {
              model_provider: "openai",
              usage: {
                prompt_tokens: 111,
                completion_tokens: 9,
                total_tokens: 120,
              },
            },
            tool_call_chunks: [],
            id: "id-4",
            usage_metadata: {
              input_tokens: 111,
              output_tokens: 9,
              total_tokens: 120,
              input_token_details: {},
              output_token_details: {},
            },
            invalid_tool_calls: [],
            tool_calls: [],
            type: "ai",
          },
          {
            id: "id-7",
            content: "Go to Mars",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
          },
        ],
      },
    },
    {
      type: "STEP_FINISHED",
      stepName: "start_flow",
    },
    {
      type: "STEP_STARTED",
      stepName: "chat_node",
    },
    shared17,
    shared19,
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: '{"steps":[{"descript',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: 'ion":"Design and bui',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: "ld a spacecraft capa",
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: 'ble of Mars transit"',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: ',"status":"pending"}',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: ',{"description":"Ass',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: "emble crew and run m",
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: 'ission simulations",',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: '"status":"pending"},',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: '{"description":"Laun',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: "ch from Earth and na",
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: 'vigate to Mars","sta',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: 'tus":"pending"},{"de',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: 'scription":"Land on ',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: "Mars surface and est",
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: 'ablish base camp","s',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: 'tatus":"pending"}]}',
    },
    {
      type: "TOOL_CALL_END",
      toolCallId: "id-8",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: shared10,
    },
    {
      type: "CUSTOM",
      name: "manually_emit_state",
      value: shared10,
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: shared9,
    },
    {
      type: "CUSTOM",
      name: "manually_emit_state",
      value: shared9,
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: shared8,
    },
    {
      type: "CUSTOM",
      name: "manually_emit_state",
      value: shared8,
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: shared7,
    },
    {
      type: "CUSTOM",
      name: "manually_emit_state",
      value: shared7,
    },
    {
      type: "TEXT_MESSAGE_START",
      messageId: "id-10",
      role: "assistant",
    },
    shared21,
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-10",
      delta: " that for you.",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-10",
    },
    {
      type: "STEP_FINISHED",
      stepName: "chat_node",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        steps: [
          {
            description:
              "Design and build a spacecraft capable of Mars transit",
            status: "completed",
          },
          {
            description: "Assemble crew and run mission simulations",
            status: "completed",
          },
          {
            description: "Launch from Earth and navigate to Mars",
            status: "completed",
          },
          {
            description: "Land on Mars surface and establish base camp",
            status: "completed",
          },
        ],
        tools: [],
        messages: [
          {
            id: "id-3",
            content: "Hi",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
          },
          {
            content: "Hello! How can I assist you today?",
            additional_kwargs: {},
            response_metadata: {
              model_provider: "openai",
              usage: {
                prompt_tokens: 111,
                completion_tokens: 9,
                total_tokens: 120,
              },
            },
            tool_call_chunks: [],
            id: "id-4",
            usage_metadata: {
              input_tokens: 111,
              output_tokens: 9,
              total_tokens: 120,
              input_token_details: {},
              output_token_details: {},
            },
            invalid_tool_calls: [],
            tool_calls: [],
            type: "ai",
          },
          {
            id: "id-7",
            content: "Go to Mars",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
          },
          {
            content: "",
            additional_kwargs: {
              tool_calls: [
                {
                  index: 0,
                  id: "id-8",
                  type: "function",
                  function: shared13,
                },
              ],
            },
            response_metadata: {
              model_provider: "openai",
              usage: {
                prompt_tokens: 122,
                completion_tokens: 93,
                total_tokens: 215,
              },
            },
            tool_call_chunks: [
              {
                name: "generate_task_steps_generative_ui",
                args: shared2,
                id: "id-8",
                index: 0,
                type: "tool_call_chunk",
              },
            ],
            tool_calls: [
              {
                name: "generate_task_steps_generative_ui",
                args: {
                  steps: [
                    {
                      description:
                        "Design and build a spacecraft capable of Mars transit",
                      status: "pending",
                    },
                    {
                      description: "Assemble crew and run mission simulations",
                      status: "pending",
                    },
                    {
                      description: "Launch from Earth and navigate to Mars",
                      status: "pending",
                    },
                    {
                      description:
                        "Land on Mars surface and establish base camp",
                      status: "pending",
                    },
                  ],
                },
                id: "id-8",
                type: "tool_call",
              },
            ],
            id: "id-9",
            usage_metadata: {
              input_tokens: 122,
              output_tokens: 93,
              total_tokens: 215,
              input_token_details: {},
              output_token_details: {},
            },
            invalid_tool_calls: [],
            type: "ai",
          },
          shared18,
          {
            content: "Done! I've completed that for you.",
            additional_kwargs: {},
            response_metadata: {
              model_provider: "openai",
              usage: {
                prompt_tokens: 126,
                completion_tokens: 9,
                total_tokens: 135,
              },
            },
            tool_call_chunks: [],
            tool_calls: [],
            id: "id-10",
            usage_metadata: {
              input_tokens: 126,
              output_tokens: 9,
              total_tokens: 135,
              input_token_details: {},
              output_token_details: {},
            },
            invalid_tool_calls: [],
            type: "ai",
          },
        ],
      },
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hi",
        },
        {
          id: "id-4",
          role: "assistant",
          content: "Hello! How can I assist you today?",
          toolCalls: [],
        },
        {
          id: "id-7",
          role: "user",
          content: "Go to Mars",
        },
        {
          id: "id-9",
          role: "assistant",
          content: "",
          toolCalls: [
            {
              id: "id-8",
              type: "function",
              function: shared13,
            },
          ],
        },
        {
          id: "id-11",
          role: "tool",
          content: "Steps executed.",
          toolCallId: "id-8",
        },
        shared20,
      ],
    },
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-12",
    },
  ],
});
