import { defineEventTrace } from "../../event-trace-test";

// Generated by the event trace updater.
// Reason: LangGraph v3 streaming event semantics; refreshed after functional TypeScript browser validation
// Before accepting changes, verify whether the implementation regressed.
const shared1 =
  "Change the background color of the chat. Can be anything that the CSS background attribute accepts. Regular colors, linear or radial gradients etc." as const;
const shared2 =
  "I can see the image you've shared. It appears to contain visual content that I can analyze. Let me describe what I observe in detail for you." as const;
const shared3 =
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwADhQGAWjR9awAAAABJRU5ErkJggg==" as const;
const shared4 = {
  type: "MESSAGES_SNAPSHOT",
  messages: [
    {
      id: "id-4",
      role: "user",
      content: [
        {
          type: "text",
          text: "Tell me what do you see in this image",
        },
        {
          type: "image",
          source: {
            type: "data",
            value: shared3,
            mimeType: "image/png",
          },
        },
      ],
    },
    {
      id: "id-5",
      role: "assistant",
      content: shared2,
      toolCalls: [],
    },
  ],
} as const;
const shared5 = [
  {
    type: "function",
    name: "change_background",
    function: {
      name: "change_background",
      description: shared1,
      parameters: {
        type: "object",
        properties: {
          background: {
            type: "string",
            description:
              "The background. Prefer gradients. Only use when asked.",
          },
        },
        required: ["background"],
      },
    },
  },
] as const;
const shared6 = [
  {
    type: "text",
    text: shared2,
  },
] as const;

export const agenticChatMultimodalPageEventTrace = defineEventTrace(
  import.meta.url,
  {
    uploadAnImageAndReceiveADescription: [
      {
        type: "RUN_STARTED",
        threadId: "id-1",
        runId: "id-2",
        input: {
          threadId: "id-1",
          runId: "id-3",
          state: {},
          messages: [
            {
              id: "id-4",
              role: "user",
              content: [
                {
                  type: "text",
                  text: "Tell me what do you see in this image",
                },
                {
                  type: "image",
                  source: {
                    type: "data",
                    value: shared3,
                    mimeType: "image/png",
                  },
                  metadata: {
                    filename: "test-image.png",
                  },
                },
              ],
            },
          ],
          tools: [
            {
              name: "change_background",
              description: shared1,
              parameters: {
                type: "object",
                properties: {
                  background: {
                    type: "string",
                    description:
                      "The background. Prefer gradients. Only use when asked.",
                  },
                },
                required: ["background"],
              },
            },
          ],
          context: [],
          forwardedProps: {},
        },
      },
      {
        type: "STEP_STARTED",
        stepName: "agentic_chat_multimodal",
      },
      {
        type: "STEP_FINISHED",
        stepName: "agentic_chat_multimodal",
      },
      {
        type: "STEP_STARTED",
        stepName: "visionChatNode",
      },
      {
        type: "TEXT_MESSAGE_START",
        messageId: "id-5",
        role: "assistant",
      },
      {
        type: "TEXT_MESSAGE_CONTENT",
        messageId: "id-5",
        delta: "I can see the image ",
      },
      {
        type: "TEXT_MESSAGE_CONTENT",
        messageId: "id-5",
        delta: "you've shared. It ap",
      },
      {
        type: "TEXT_MESSAGE_CONTENT",
        messageId: "id-5",
        delta: "pears to contain vis",
      },
      {
        type: "TEXT_MESSAGE_CONTENT",
        messageId: "id-5",
        delta: "ual content that I c",
      },
      {
        type: "TEXT_MESSAGE_CONTENT",
        messageId: "id-5",
        delta: "an analyze. Let me d",
      },
      {
        type: "TEXT_MESSAGE_CONTENT",
        messageId: "id-5",
        delta: "escribe what I obser",
      },
      {
        type: "TEXT_MESSAGE_CONTENT",
        messageId: "id-5",
        delta: "ve in detail for you",
      },
      {
        type: "TEXT_MESSAGE_CONTENT",
        messageId: "id-5",
        delta: ".",
      },
      {
        type: "TEXT_MESSAGE_END",
        messageId: "id-5",
      },
      {
        type: "STEP_FINISHED",
        stepName: "visionChatNode",
      },
      {
        type: "STATE_SNAPSHOT",
        snapshot: {
          tools: shared5,
        },
      },
      {
        type: "MESSAGES_SNAPSHOT",
        messages: [
          {
            id: "id-4",
            role: "user",
            content: [
              {
                type: "text",
                text: "Tell me what do you see in this image",
              },
              {
                type: "image",
                source: {
                  type: "data",
                  value: shared3,
                  mimeType: "image/png",
                },
              },
            ],
          },
        ],
      },
      shared4,
      {
        type: "STATE_SNAPSHOT",
        snapshot: {
          tools: shared5,
          messages: [
            {
              id: "id-4",
              content: [
                {
                  type: "text",
                  text: "Tell me what do you see in this image",
                },
                {
                  type: "image_url",
                  image_url: {
                    url: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwADhQGAWjR9awAAAABJRU5ErkJggg==",
                  },
                },
              ],
              additional_kwargs: {},
              response_metadata: {},
              type: "human",
            },
            {
              id: "id-5",
              content: shared6,
              usage_metadata: {
                input_tokens: 59,
                output_tokens: 36,
                total_tokens: 95,
              },
              response_metadata: {
                output_version: "v1",
                model_provider: "openai",
                model_name: "gpt-5.4",
                finish_reason: "stop",
              },
              tool_calls: [],
              invalid_tool_calls: [],
              content_blocks: shared6,
              additional_kwargs: {},
              type: "ai",
            },
          ],
        },
      },
      shared4,
      {
        type: "RUN_FINISHED",
        threadId: "id-1",
        runId: "id-2",
        usage: [
          {
            inputTokens: 59,
            outputTokens: 36,
            totalTokens: 95,
          },
        ],
      },
    ],
  },
);
