import { defineEventTrace } from "../../event-trace-test";

// Generated by the event trace updater.
// Reason: LangGraph v3 streaming event semantics; refreshed after functional TypeScript browser validation
// Before accepting changes, verify whether the implementation regressed.
const shared1 =
  '{"recipe":{"title":"Pasta Aglio e Olio","skill_level":"Intermediate","special_preferences":[],"cooking_time":"45 min","ingredients":[{"icon":"🍝","name":"Pasta","amount":"400g"},{"icon":"🧂","name":"Salt","amount":"1 tsp"},{"icon":"🫒","name":"Olive Oil","amount":"4 tbsp"},{"icon":"🧄","name":"Garlic","amount":"6 cloves"},{"icon":"🍅","name":"Tomatoes","amount":"2 cups"}],"instructions":["Boil water and cook pasta until al dente","Slice garlic thinly and sauté in olive oil","Dice tomatoes and add to the pan","Season with salt to taste","Toss pasta with the sauce and serve"],"changes":""}}' as const;
const shared2 =
  "Here are the ingredients:\n- Pasta: 400g\n- Salt: 1 tsp\n- Olive Oil: 4 tbsp\n- Garlic: 6 cloves\n- Tomatoes: 2 cups\n- Potatoes: 12\n- Carrots: 3\n- All-Purpose Flour: 2 cups" as const;
const shared3 =
  'Please give me a pasta recipe of your choosing, but one of the ingredients should be "Pasta"' as const;
const shared4 = {
  type: "MESSAGES_SNAPSHOT",
  messages: [
    {
      id: "id-4",
      role: "user",
      content: shared3,
    },
    {
      id: "id-6",
      role: "assistant",
      content: "",
      toolCalls: [
        {
          id: "id-5",
          type: "function",
          function: {
            name: "generate_recipe",
            arguments: shared1,
          },
        },
      ],
    },
    {
      id: "id-8",
      role: "tool",
      content: "Recipe generated.",
      toolCallId: "id-5",
    },
    {
      id: "id-7",
      role: "assistant",
      content: "Done! I've completed that for you.",
      toolCalls: [],
    },
  ],
} as const;
const shared5 = [
  {
    type: "tool_call",
    id: "id-5",
    name: "generate_recipe",
    args: {
      recipe: {
        title: "Pasta Aglio e Olio",
        skill_level: "Intermediate",
        special_preferences: [],
        cooking_time: "45 min",
        ingredients: [
          {
            icon: "🍝",
            name: "Pasta",
            amount: "400g",
          },
          {
            icon: "🧂",
            name: "Salt",
            amount: "1 tsp",
          },
          {
            icon: "🫒",
            name: "Olive Oil",
            amount: "4 tbsp",
          },
          {
            icon: "🧄",
            name: "Garlic",
            amount: "6 cloves",
          },
          {
            icon: "🍅",
            name: "Tomatoes",
            amount: "2 cups",
          },
        ],
        instructions: [
          "Boil water and cook pasta until al dente",
          "Slice garlic thinly and sauté in olive oil",
          "Dice tomatoes and add to the pan",
          "Season with salt to taste",
          "Toss pasta with the sauce and serve",
        ],
        changes: "",
      },
    },
  },
] as const;
const shared6 = {
  skill_level: "Intermediate",
  special_preferences: [],
  cooking_time: "45 min",
  ingredients: [
    {
      icon: "🍝",
      name: "Pasta",
      amount: "400g",
    },
    {
      icon: "🧂",
      name: "Salt",
      amount: "1 tsp",
    },
    {
      icon: "🫒",
      name: "Olive Oil",
      amount: "4 tbsp",
    },
    {
      icon: "🧄",
      name: "Garlic",
      amount: "6 cloves",
    },
    {
      icon: "🍅",
      name: "Tomatoes",
      amount: "2 cups",
    },
  ],
  instructions: [
    "Boil water and cook pasta until al dente",
    "Slice garlic thinly and sauté in olive oil",
    "Dice tomatoes and add to the pan",
    "Season with salt to taste",
    "Toss pasta with the sauce and serve",
  ],
  title: "Pasta Aglio e Olio",
  changes: "",
} as const;
const shared7 = {
  type: "MESSAGES_SNAPSHOT",
  messages: [
    {
      id: "id-4",
      role: "user",
      content: "Give me all the ingredients",
    },
    {
      id: "id-5",
      role: "assistant",
      content: shared2,
      toolCalls: [],
    },
  ],
} as const;
const shared8 = {
  title: "Make Your Recipe",
  skill_level: "Intermediate",
  cooking_time: "45 min",
  special_preferences: [],
  ingredients: [
    {
      icon: "🥕",
      name: "Carrots",
      amount: "3 large, grated",
    },
    {
      icon: "🌾",
      name: "All-Purpose Flour",
      amount: "2 cups",
    },
    {
      icon: "🍴",
      name: "Potatoes",
      amount: "12",
    },
  ],
  instructions: ["Preheat oven to 350°F (175°C)"],
} as const;
const shared9 = [
  {
    type: "text",
    text: shared2,
  },
] as const;
const shared10 = [
  {
    id: "id-4",
    role: "user",
    content: shared3,
  },
] as const;
const shared11 = {
  output_version: "v1",
  model_provider: "openai",
  model_name: "gpt-4o-mini",
  finish_reason: "stop",
} as const;

export const sharedStatePageEventTrace = defineEventTrace(import.meta.url, {
  interactWithTheChatToGetARecipeOnPrompt: [
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-2",
      input: {
        threadId: "id-1",
        runId: "id-3",
        state: {},
        messages: shared10,
        tools: [],
        context: [],
        forwardedProps: {},
      },
    },
    {
      type: "STEP_STARTED",
      stepName: "shared_state",
    },
    {
      type: "STEP_FINISHED",
      stepName: "shared_state",
    },
    {
      type: "STEP_STARTED",
      stepName: "chat_node",
    },
    {
      type: "TOOL_CALL_START",
      toolCallId: "id-5",
      toolCallName: "generate_recipe",
      parentMessageId: "id-6",
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-5",
      delta: '{"recipe":{"title":"',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-5",
      delta: 'Pasta Aglio e Olio",',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-5",
      delta: '"skill_level":"Inter',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-5",
      delta: 'mediate","special_pr',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-5",
      delta: 'eferences":[],"cooki',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-5",
      delta: 'ng_time":"45 min","i',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-5",
      delta: 'ngredients":[{"icon"',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-5",
      delta: ':"🍝","name":"Pasta"',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-5",
      delta: ',"amount":"400g"},{"',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-5",
      delta: 'icon":"🧂","name":"S',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-5",
      delta: 'alt","amount":"1 tsp',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-5",
      delta: '"},{"icon":"🫒","nam',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-5",
      delta: 'e":"Olive Oil","amou',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-5",
      delta: 'nt":"4 tbsp"},{"icon',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-5",
      delta: '":"🧄","name":"Garli',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-5",
      delta: 'c","amount":"6 clove',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-5",
      delta: 's"},{"icon":"🍅","na',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-5",
      delta: 'me":"Tomatoes","amou',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-5",
      delta: 'nt":"2 cups"}],"inst',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-5",
      delta: 'ructions":["Boil wat',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-5",
      delta: "er and cook pasta un",
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-5",
      delta: 'til al dente","Slice',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-5",
      delta: " garlic thinly and s",
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-5",
      delta: 'auté in olive oil","',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-5",
      delta: "Dice tomatoes and ad",
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-5",
      delta: 'd to the pan","Seaso',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-5",
      delta: "n with salt to taste",
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-5",
      delta: '","Toss pasta with t',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-5",
      delta: 'he sauce and serve"]',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-5",
      delta: ',"changes":""}}',
    },
    {
      type: "TOOL_CALL_END",
      toolCallId: "id-5",
    },
    {
      type: "STEP_FINISHED",
      stepName: "chat_node",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        tools: [],
        recipe: {
          skill_level: "Beginner",
          special_preferences: [],
          cooking_time: "15 min",
          ingredients: [
            {
              icon: "🍴",
              name: "Sample Ingredient",
              amount: "1 unit",
            },
          ],
          instructions: ["First step instruction"],
        },
      },
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: shared10,
    },
    {
      type: "STEP_STARTED",
      stepName: "chat_node",
    },
    {
      type: "TEXT_MESSAGE_START",
      messageId: "id-7",
      role: "assistant",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-7",
      delta: "Done! I've completed",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-7",
      delta: " that for you.",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-7",
    },
    {
      type: "STEP_FINISHED",
      stepName: "chat_node",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        tools: [],
        recipe: shared6,
      },
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-4",
          role: "user",
          content: shared3,
        },
        {
          id: "id-6",
          role: "assistant",
          content: "",
          toolCalls: [
            {
              id: "id-5",
              type: "function",
              function: {
                name: "generate_recipe",
                arguments: shared1,
              },
            },
          ],
        },
        {
          id: "id-8",
          role: "tool",
          content: "Recipe generated.",
          toolCallId: "id-5",
        },
      ],
    },
    shared4,
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        recipe: shared6,
        tools: [],
        messages: [
          {
            id: "id-4",
            content: shared3,
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
          },
          {
            id: "id-6",
            content: shared5,
            usage_metadata: {
              input_tokens: 267,
              output_tokens: 153,
              total_tokens: 420,
            },
            response_metadata: {
              output_version: "v1",
              model_provider: "openai",
              model_name: "gpt-4o-mini",
              finish_reason: "tool_use",
            },
            tool_calls: shared5,
            invalid_tool_calls: [],
            content_blocks: shared5,
            additional_kwargs: {},
            type: "ai",
          },
          {
            content: "Recipe generated.",
            tool_call_id: "id-5",
            additional_kwargs: {},
            response_metadata: {},
            id: "id-8",
            type: "tool",
          },
          {
            id: "id-7",
            content: [
              {
                type: "text",
                text: "Done! I've completed that for you.",
              },
            ],
            usage_metadata: {
              input_tokens: 410,
              output_tokens: 9,
              total_tokens: 419,
            },
            response_metadata: shared11,
            tool_calls: [],
            invalid_tool_calls: [],
            content_blocks: [
              {
                type: "text",
                text: "Done! I've completed that for you.",
              },
            ],
            additional_kwargs: {},
            type: "ai",
          },
        ],
      },
    },
    shared4,
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-2",
      usage: [
        {
          inputTokens: 677,
          outputTokens: 162,
          totalTokens: 839,
        },
      ],
    },
  ],
  shareStateBetweenUIAndChat: [
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-2",
      input: {
        threadId: "id-1",
        runId: "id-3",
        state: {
          recipe: shared8,
        },
        messages: [
          {
            id: "id-4",
            role: "user",
            content: "Give me all the ingredients",
          },
        ],
        tools: [],
        context: [],
        forwardedProps: {},
      },
    },
    {
      type: "STEP_STARTED",
      stepName: "shared_state",
    },
    {
      type: "STEP_FINISHED",
      stepName: "shared_state",
    },
    {
      type: "STEP_STARTED",
      stepName: "chat_node",
    },
    {
      type: "TEXT_MESSAGE_START",
      messageId: "id-5",
      role: "assistant",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-5",
      delta: "Here are the ingredi",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-5",
      delta: "ents:\n- Pasta: 400g\n",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-5",
      delta: "- Salt: 1 tsp\n- Oliv",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-5",
      delta: "e Oil: 4 tbsp\n- Garl",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-5",
      delta: "ic: 6 cloves\n- Tomat",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-5",
      delta: "oes: 2 cups\n- Potato",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-5",
      delta: "es: 12\n- Carrots: 3\n",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-5",
      delta: "- All-Purpose Flour:",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-5",
      delta: " 2 cups",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-5",
    },
    {
      type: "STEP_FINISHED",
      stepName: "chat_node",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        recipe: shared8,
        tools: [],
      },
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-4",
          role: "user",
          content: "Give me all the ingredients",
        },
      ],
    },
    shared7,
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        recipe: shared8,
        tools: [],
        messages: [
          {
            id: "id-4",
            content: "Give me all the ingredients",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
          },
          {
            id: "id-5",
            content: shared9,
            usage_metadata: {
              input_tokens: 304,
              output_tokens: 42,
              total_tokens: 346,
            },
            response_metadata: shared11,
            tool_calls: [],
            invalid_tool_calls: [],
            content_blocks: shared9,
            additional_kwargs: {},
            type: "ai",
          },
        ],
      },
    },
    shared7,
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-2",
      usage: [
        {
          inputTokens: 304,
          outputTokens: 42,
          totalTokens: 346,
        },
      ],
    },
  ],
});
