import { defineEventTrace } from "../../event-trace-test";

// Generated by the event trace updater.
// Reason: Raw V3 replay after 2fa766ad6: client-owned run IDs and V2-aligned step/state ordering. All payloads audited against passing V2 references; raw V3 omits empty snapshots and retains native tool-call content in intermediate state. Unexecuted journeys preserved.
// Before accepting changes, verify whether the implementation regressed.
const shared1 =
  '{"recipe":{"title":"Pasta Aglio e Olio","skill_level":"Intermediate","special_preferences":[],"cooking_time":"45 min","ingredients":[{"icon":"🍝","name":"Pasta","amount":"400g"},{"icon":"🧂","name":"Salt","amount":"1 tsp"},{"icon":"🫒","name":"Olive Oil","amount":"4 tbsp"},{"icon":"🧄","name":"Garlic","amount":"6 cloves"},{"icon":"🍅","name":"Tomatoes","amount":"2 cups"}],"instructions":["Boil water and cook pasta until al dente","Slice garlic thinly and sauté in olive oil","Dice tomatoes and add to the pan","Season with salt to taste","Toss pasta with the sauce and serve"],"changes":""}}' as const;
const shared2 =
  "Here are the ingredients:\n- Pasta: 400g\n- Salt: 1 tsp\n- Olive Oil: 4 tbsp\n- Garlic: 6 cloves\n- Tomatoes: 2 cups\n- Potatoes: 12\n- Carrots: 3\n- All-Purpose Flour: 2 cups" as const;
const shared3 =
  'Please give me a pasta recipe of your choosing, but one of the ingredients should be "Pasta"' as const;
const shared4 = {
  name: "generate_recipe",
  arguments: shared1,
} as const;
const shared5 = {
  skill_level: "Intermediate",
  special_preferences: [],
  cooking_time: "45 min",
  ingredients: [
    {
      icon: "🍝",
      name: "Pasta",
      amount: "400g",
    },
    {
      icon: "🧂",
      name: "Salt",
      amount: "1 tsp",
    },
    {
      icon: "🫒",
      name: "Olive Oil",
      amount: "4 tbsp",
    },
    {
      icon: "🧄",
      name: "Garlic",
      amount: "6 cloves",
    },
    {
      icon: "🍅",
      name: "Tomatoes",
      amount: "2 cups",
    },
  ],
  instructions: [
    "Boil water and cook pasta until al dente",
    "Slice garlic thinly and sauté in olive oil",
    "Dice tomatoes and add to the pan",
    "Season with salt to taste",
    "Toss pasta with the sauce and serve",
  ],
  title: "Pasta Aglio e Olio",
  changes: "",
} as const;
const shared6 = {
  tools: [],
  messages: [
    {
      id: "id-3",
      content: shared3,
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
    },
  ],
  recipe: {
    skill_level: "Beginner",
    special_preferences: [],
    cooking_time: "15 min",
    ingredients: [
      {
        icon: "🍴",
        name: "Sample Ingredient",
        amount: "1 unit",
      },
    ],
    instructions: ["First step instruction"],
  },
} as const;
const shared7 = {
  title: "Make Your Recipe",
  skill_level: "Intermediate",
  cooking_time: "45 min",
  special_preferences: [],
  ingredients: [
    {
      icon: "🥕",
      name: "Carrots",
      amount: "3 large, grated",
    },
    {
      icon: "🌾",
      name: "All-Purpose Flour",
      amount: "2 cups",
    },
    {
      icon: "🍴",
      name: "Potatoes",
      amount: "12",
    },
  ],
  instructions: ["Preheat oven to 350°F (175°C)"],
} as const;
const shared8 = {
  id: "id-3",
  role: "user",
  content: shared3,
} as const;
const shared9 = {
  id: "id-3",
  content: "Give me all the ingredients",
  additional_kwargs: {},
  response_metadata: {},
  type: "human",
} as const;

export const sharedStatePageEventTrace = defineEventTrace(import.meta.url, {
  interactWithTheChatToGetARecipeOnPrompt: [
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-2",
      protocolVersion: "1.0",
      input: {
        threadId: "id-1",
        runId: "id-2",
        protocolVersion: "1.0",
        state: {},
        messages: [shared8],
        tools: [],
        context: [],
        forwardedProps: {},
      },
    },
    {
      type: "STEP_STARTED",
      stepName: "start_flow",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {},
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        tools: [],
        messages: [
          {
            id: "id-3",
            content: shared3,
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
          },
        ],
      },
    },
    {
      type: "CUSTOM",
      name: "manually_emit_intermediate_state",
      value: shared6,
    },
    {
      type: "STEP_FINISHED",
      stepName: "start_flow",
    },
    {
      type: "STEP_STARTED",
      stepName: "chat_node",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: shared6,
    },
    {
      type: "CUSTOM",
      name: "PredictState",
      value: [
        {
          state_key: "recipe",
          tool: "generate_recipe",
          tool_argument: "recipe",
        },
      ],
    },
    {
      type: "TOOL_CALL_START",
      toolCallId: "id-4",
      toolCallName: "generate_recipe",
      parentMessageId: "id-5",
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: '{"recipe":{"title":"',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: 'Pasta Aglio e Olio",',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: '"skill_level":"Inter',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: 'mediate","special_pr',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: 'eferences":[],"cooki',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: 'ng_time":"45 min","i',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: 'ngredients":[{"icon"',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: ':"🍝","name":"Pasta"',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: ',"amount":"400g"},{"',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: 'icon":"🧂","name":"S',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: 'alt","amount":"1 tsp',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: '"},{"icon":"🫒","nam',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: 'e":"Olive Oil","amou',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: 'nt":"4 tbsp"},{"icon',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: '":"🧄","name":"Garli',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: 'c","amount":"6 clove',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: 's"},{"icon":"🍅","na',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: 'me":"Tomatoes","amou',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: 'nt":"2 cups"}],"inst',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: 'ructions":["Boil wat',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: "er and cook pasta un",
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: 'til al dente","Slice',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: " garlic thinly and s",
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: 'auté in olive oil","',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: "Dice tomatoes and ad",
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: 'd to the pan","Seaso',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: "n with salt to taste",
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: '","Toss pasta with t',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: 'he sauce and serve"]',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: ',"changes":""}}',
    },
    {
      type: "TOOL_CALL_END",
      toolCallId: "id-4",
    },
    {
      type: "CUSTOM",
      name: "manually_emit_intermediate_state",
      value: {
        recipe: shared5,
        tools: [],
        messages: [
          {
            id: "id-3",
            content: shared3,
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
          },
        ],
      },
    },
    {
      type: "STEP_FINISHED",
      stepName: "chat_node",
    },
    {
      type: "STEP_STARTED",
      stepName: "start_flow",
    },
    {
      type: "STEP_FINISHED",
      stepName: "start_flow",
    },
    {
      type: "STEP_STARTED",
      stepName: "chat_node",
    },
    {
      type: "TEXT_MESSAGE_START",
      messageId: "id-6",
      role: "assistant",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-6",
      delta: "Done! I've completed",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-6",
      delta: " that for you.",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-6",
    },
    {
      type: "STEP_FINISHED",
      stepName: "chat_node",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        tools: [],
        messages: [
          {
            id: "id-3",
            content: shared3,
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
          },
          {
            id: "id-5",
            content: "",
            usage_metadata: {
              input_token_details: {},
              output_token_details: {},
              input_tokens: 267,
              output_tokens: 153,
              total_tokens: 420,
            },
            additional_kwargs: {
              tool_calls: [
                {
                  index: 0,
                  id: "id-4",
                  type: "function",
                  function: shared4,
                },
              ],
            },
            response_metadata: {
              model_provider: "openai",
              usage: {
                prompt_tokens: 267,
                completion_tokens: 153,
                total_tokens: 420,
              },
            },
            tool_calls: [
              {
                type: "tool_call",
                id: "id-4",
                name: "generate_recipe",
                args: {
                  recipe: {
                    title: "Pasta Aglio e Olio",
                    skill_level: "Intermediate",
                    special_preferences: [],
                    cooking_time: "45 min",
                    ingredients: [
                      {
                        icon: "🍝",
                        name: "Pasta",
                        amount: "400g",
                      },
                      {
                        icon: "🧂",
                        name: "Salt",
                        amount: "1 tsp",
                      },
                      {
                        icon: "🫒",
                        name: "Olive Oil",
                        amount: "4 tbsp",
                      },
                      {
                        icon: "🧄",
                        name: "Garlic",
                        amount: "6 cloves",
                      },
                      {
                        icon: "🍅",
                        name: "Tomatoes",
                        amount: "2 cups",
                      },
                    ],
                    instructions: [
                      "Boil water and cook pasta until al dente",
                      "Slice garlic thinly and sauté in olive oil",
                      "Dice tomatoes and add to the pan",
                      "Season with salt to taste",
                      "Toss pasta with the sauce and serve",
                    ],
                    changes: "",
                  },
                },
              },
            ],
            invalid_tool_calls: [],
            type: "ai",
            tool_call_chunks: [
              {
                name: "generate_recipe",
                args: shared1,
                id: "id-4",
                index: 0,
                type: "tool_call_chunk",
              },
            ],
          },
          {
            content: "Recipe generated.",
            tool_call_id: "id-4",
            additional_kwargs: {},
            response_metadata: {},
            id: "id-7",
            type: "tool",
          },
          {
            id: "id-6",
            content: "Done! I've completed that for you.",
            usage_metadata: {
              input_token_details: {},
              output_token_details: {},
              input_tokens: 410,
              output_tokens: 9,
              total_tokens: 419,
            },
            additional_kwargs: {},
            response_metadata: {
              model_provider: "openai",
              usage: {
                prompt_tokens: 410,
                completion_tokens: 9,
                total_tokens: 419,
              },
            },
            tool_calls: [],
            invalid_tool_calls: [],
            type: "ai",
            tool_call_chunks: [],
          },
        ],
        recipe: shared5,
      },
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        shared8,
        {
          id: "id-5",
          role: "assistant",
          content: "",
          toolCalls: [
            {
              id: "id-4",
              type: "function",
              function: shared4,
            },
          ],
        },
        {
          id: "id-7",
          role: "tool",
          content: "Recipe generated.",
          toolCallId: "id-4",
        },
        {
          id: "id-6",
          role: "assistant",
          content: "Done! I've completed that for you.",
          toolCalls: [],
        },
      ],
    },
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-8",
      usage: [
        {
          provider: "openai",
          model: "gpt-4o-mini",
          inputTokens: 677,
          outputTokens: 162,
          totalTokens: 839,
        },
      ],
    },
  ],
  shareStateBetweenUIAndChat: [
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-2",
      protocolVersion: "1.0",
      input: {
        threadId: "id-1",
        runId: "id-2",
        protocolVersion: "1.0",
        state: {
          recipe: shared7,
        },
        messages: [
          {
            id: "id-3",
            role: "user",
            content: "Give me all the ingredients",
          },
        ],
        tools: [],
        context: [],
        forwardedProps: {},
      },
    },
    {
      type: "STEP_STARTED",
      stepName: "start_flow",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {},
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        recipe: shared7,
        tools: [],
        messages: [shared9],
      },
    },
    {
      type: "STEP_FINISHED",
      stepName: "start_flow",
    },
    {
      type: "STEP_STARTED",
      stepName: "chat_node",
    },
    {
      type: "TEXT_MESSAGE_START",
      messageId: "id-4",
      role: "assistant",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: "Here are the ingredi",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: "ents:\n- Pasta: 400g\n",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: "- Salt: 1 tsp\n- Oliv",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: "e Oil: 4 tbsp\n- Garl",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: "ic: 6 cloves\n- Tomat",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: "oes: 2 cups\n- Potato",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: "es: 12\n- Carrots: 3\n",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: "- All-Purpose Flour:",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: " 2 cups",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-4",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        recipe: shared7,
        tools: [],
        messages: [
          shared9,
          {
            id: "id-4",
            content: shared2,
            usage_metadata: {
              input_token_details: {},
              output_token_details: {},
              input_tokens: 304,
              output_tokens: 42,
              total_tokens: 346,
            },
            additional_kwargs: {},
            response_metadata: {
              model_provider: "openai",
              usage: {
                prompt_tokens: 304,
                completion_tokens: 42,
                total_tokens: 346,
              },
            },
            tool_calls: [],
            invalid_tool_calls: [],
            type: "ai",
            tool_call_chunks: [],
          },
        ],
      },
    },
    {
      type: "STEP_FINISHED",
      stepName: "chat_node",
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Give me all the ingredients",
        },
        {
          id: "id-4",
          role: "assistant",
          content: shared2,
          toolCalls: [],
        },
      ],
    },
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-5",
      usage: [
        {
          provider: "openai",
          model: "gpt-4o-mini",
          inputTokens: 304,
          outputTokens: 42,
          totalTokens: 346,
        },
      ],
    },
  ],
});
