export enum EventType {
  TEXT_MESSAGE_START = "TEXT_MESSAGE_START",
  TEXT_MESSAGE_CONTENT = "TEXT_MESSAGE_CONTENT",
  TEXT_MESSAGE_END = "TEXT_MESSAGE_END",
  TEXT_MESSAGE_CHUNK = "TEXT_MESSAGE_CHUNK",
  TOOL_CALL_START = "TOOL_CALL_START",
  TOOL_CALL_ARGS = "TOOL_CALL_ARGS",
  TOOL_CALL_END = "TOOL_CALL_END",
  TOOL_CALL_CHUNK = "TOOL_CALL_CHUNK",
  TOOL_CALL_RESULT = "TOOL_CALL_RESULT",
  /** @deprecated Use REASONING_START instead. Will be removed in 1.0.0. */
  THINKING_START = "THINKING_START",
  /** @deprecated Use REASONING_END instead. Will be removed in 1.0.0. */
  THINKING_END = "THINKING_END",
  /** @deprecated Use REASONING_MESSAGE_START instead. Will be removed in 1.0.0. */
  THINKING_TEXT_MESSAGE_START = "THINKING_TEXT_MESSAGE_START",
  /** @deprecated Use REASONING_MESSAGE_CONTENT instead. Will be removed in 1.0.0. */
  THINKING_TEXT_MESSAGE_CONTENT = "THINKING_TEXT_MESSAGE_CONTENT",
  /** @deprecated Use REASONING_MESSAGE_END instead. Will be removed in 1.0.0. */
  THINKING_TEXT_MESSAGE_END = "THINKING_TEXT_MESSAGE_END",
  STATE_SNAPSHOT = "STATE_SNAPSHOT",
  STATE_DELTA = "STATE_DELTA",
  MESSAGES_SNAPSHOT = "MESSAGES_SNAPSHOT",
  ACTIVITY_SNAPSHOT = "ACTIVITY_SNAPSHOT",
  ACTIVITY_DELTA = "ACTIVITY_DELTA",
  RAW = "RAW",
  CUSTOM = "CUSTOM",
  RUN_STARTED = "RUN_STARTED",
  RUN_FINISHED = "RUN_FINISHED",
  RUN_ERROR = "RUN_ERROR",
  STEP_STARTED = "STEP_STARTED",
  STEP_FINISHED = "STEP_FINISHED",
  REASONING_START = "REASONING_START",
  REASONING_MESSAGE_START = "REASONING_MESSAGE_START",
  REASONING_MESSAGE_CONTENT = "REASONING_MESSAGE_CONTENT",
  REASONING_MESSAGE_END = "REASONING_MESSAGE_END",
  REASONING_MESSAGE_CHUNK = "REASONING_MESSAGE_CHUNK",
  REASONING_END = "REASONING_END",
  REASONING_ENCRYPTED_VALUE = "REASONING_ENCRYPTED_VALUE",
}

export type {
  TextMessageRole,
  BaseEvent,
  BaseEventFields,
  AGUIEvent,
  AGUIEventByType,
  AGUIEventOf,
  EventPayloadOf,
  TextMessageStartEvent,
  TextMessageContentEvent,
  TextMessageEndEvent,
  TextMessageChunkEvent,
  ThinkingTextMessageStartEvent,
  ThinkingTextMessageContentEvent,
  ThinkingTextMessageEndEvent,
  ToolCallStartEvent,
  ToolCallArgsEvent,
  ToolCallEndEvent,
  ToolCallChunkEvent,
  ToolCallResultEvent,
  ThinkingStartEvent,
  ThinkingEndEvent,
  StateSnapshotEvent,
  StateDeltaEvent,
  MessagesSnapshotEvent,
  ActivitySnapshotEvent,
  ActivityDeltaEvent,
  RawEvent,
  CustomEvent,
  RunStartedEvent,
  RunFinishedEvent,
  RunFinishedOutcome,
  RunFinishedSuccessOutcome,
  RunFinishedInterruptOutcome,
  RunErrorEvent,
  StepStartedEvent,
  StepFinishedEvent,
  ReasoningStartEvent,
  ReasoningMessageStartEvent,
  ReasoningMessageContentEvent,
  ReasoningMessageEndEvent,
  ReasoningMessageChunkEvent,
  ReasoningEndEvent,
  ReasoningEncryptedValueEvent,
  ReasoningEncryptedValueSubtype,
  BaseEventProps,
  TextMessageStartEventProps,
  TextMessageContentEventProps,
  TextMessageEndEventProps,
  TextMessageChunkEventProps,
  ThinkingTextMessageStartEventProps,
  ThinkingTextMessageContentEventProps,
  ThinkingTextMessageEndEventProps,
  ToolCallStartEventProps,
  ToolCallArgsEventProps,
  ToolCallEndEventProps,
  ToolCallChunkEventProps,
  ToolCallResultEventProps,
  ThinkingStartEventProps,
  ThinkingEndEventProps,
  StateSnapshotEventProps,
  StateDeltaEventProps,
  MessagesSnapshotEventProps,
  ActivitySnapshotEventProps,
  ActivityDeltaEventProps,
  RawEventProps,
  CustomEventProps,
  RunStartedEventProps,
  RunFinishedEventProps,
  RunErrorEventProps,
  StepStartedEventProps,
  StepFinishedEventProps,
  ReasoningStartEventProps,
  ReasoningMessageStartEventProps,
  ReasoningMessageContentEventProps,
  ReasoningMessageEndEventProps,
  ReasoningMessageChunkEventProps,
  ReasoningEndEventProps,
  ReasoningEncryptedValueEventProps,
} from "./events-static";
