[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.dependencies]
thiserror = "^2"
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
uuid = { version = "1.17.0", features = ["v4", "serde"] }

