import { defineEventTrace } from "../../event-trace-test";

// Generated by the event trace updater.
// Reason: CopilotKit 1.76.0 is an AG-UI 1.0 client: RunAgentInput now carries protocolVersion "1.0"
// Before accepting changes, verify whether the implementation regressed.
const shared1 =
  "The Moon is Earth's only natural satellite, orbiting at an average distance of about 384,400 km. It takes approximately 27.3 days to complete one orbit." as const;
const shared2 =
  "Change the background color of the chat. Can be anything that the CSS background attribute accepts. Regular colors, linear of radial gradients etc." as const;
const shared3 =
  'App Context:\n[\n  {\n    "description": "Name of the user",\n    "value": "Bob"\n  }\n]' as const;
const shared4 =
  "Kaavish is a wonderful musical group known for their unique blend of Eastern and Western sounds!" as const;
const shared5 =
  "That's great! Mango is a wonderful tropical fruit known for its sweet, juicy flavor." as const;
const shared6 = {
  messages: [
    {
      content: "Hey there",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
      name: null,
      id: "id-3",
    },
    {
      content: shared3,
      additional_kwargs: {},
      response_metadata: {},
      type: "system",
      name: null,
      id: "id-5",
    },
    {
      content: "Hello! How can I assist you today?",
      additional_kwargs: {},
      response_metadata: {
        finish_reason: "stop",
        model_name: "gpt-4.1-mini",
        model_provider: "openai",
      },
      type: "ai",
      name: null,
      id: "id-4",
      tool_calls: [],
      invalid_tool_calls: [],
      usage_metadata: null,
    },
    {
      content: "My favorite fruit is Mango",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
      name: null,
      id: "id-7",
    },
    {
      content: shared5,
      additional_kwargs: {},
      response_metadata: {
        finish_reason: "stop",
        model_name: "gpt-4.1-mini",
        model_provider: "openai",
      },
      type: "ai",
      name: null,
      id: "id-8",
      tool_calls: [],
      invalid_tool_calls: [],
      usage_metadata: null,
    },
    {
      content: "and I love listening to Kaavish",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
      name: null,
      id: "id-10",
    },
    {
      content: shared4,
      additional_kwargs: {},
      response_metadata: {
        finish_reason: "stop",
        model_name: "gpt-4.1-mini",
        model_provider: "openai",
      },
      type: "ai",
      name: null,
      id: "id-11",
      tool_calls: [],
      invalid_tool_calls: [],
      usage_metadata: null,
    },
    {
      content: "tell me an interesting fact about Moon",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
      name: null,
      id: "id-13",
    },
    {
      content: shared1,
      additional_kwargs: {},
      response_metadata: {
        finish_reason: "stop",
        model_name: "gpt-4.1-mini",
        model_provider: "openai",
      },
      type: "ai",
      name: null,
      id: "id-14",
      tool_calls: [],
      invalid_tool_calls: [],
      usage_metadata: null,
    },
  ],
  copilotkit: {
    actions: [
      {
        name: "change_background",
        description: shared2,
        parameters: {
          type: "object",
          properties: {
            background: {
              type: "string",
              description:
                "The background. Prefer gradients. Only use when asked.",
            },
          },
          required: ["background"],
        },
      },
    ],
    context: [
      {
        description: "Name of the user",
        value: "Bob",
      },
    ],
  },
} as const;
const shared7 = {
  messages: [
    {
      content: "Hey there",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
      name: null,
      id: "id-3",
    },
    {
      content: shared3,
      additional_kwargs: {},
      response_metadata: {},
      type: "system",
      name: null,
      id: "id-5",
    },
    {
      content: "Hello! How can I assist you today?",
      additional_kwargs: {},
      response_metadata: {
        finish_reason: "stop",
        model_name: "gpt-4.1-mini",
        model_provider: "openai",
      },
      type: "ai",
      name: null,
      id: "id-4",
      tool_calls: [],
      invalid_tool_calls: [],
      usage_metadata: null,
    },
    {
      content: "My favorite fruit is Mango",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
      name: null,
      id: "id-7",
    },
    {
      content: shared5,
      additional_kwargs: {},
      response_metadata: {
        finish_reason: "stop",
        model_name: "gpt-4.1-mini",
        model_provider: "openai",
      },
      type: "ai",
      name: null,
      id: "id-8",
      tool_calls: [],
      invalid_tool_calls: [],
      usage_metadata: null,
    },
    {
      content: "and I love listening to Kaavish",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
      name: null,
      id: "id-10",
    },
    {
      content: shared4,
      additional_kwargs: {},
      response_metadata: {
        finish_reason: "stop",
        model_name: "gpt-4.1-mini",
        model_provider: "openai",
      },
      type: "ai",
      name: null,
      id: "id-11",
      tool_calls: [],
      invalid_tool_calls: [],
      usage_metadata: null,
    },
  ],
  copilotkit: {
    actions: [
      {
        name: "change_background",
        description: shared2,
        parameters: {
          type: "object",
          properties: {
            background: {
              type: "string",
              description:
                "The background. Prefer gradients. Only use when asked.",
            },
          },
          required: ["background"],
        },
      },
    ],
    context: [
      {
        description: "Name of the user",
        value: "Bob",
      },
    ],
  },
} as const;
const shared8 = {
  messages: [
    {
      content: "Hi change the background color to blue",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
      name: null,
      id: "id-3",
    },
    {
      content: shared3,
      additional_kwargs: {},
      response_metadata: {},
      type: "system",
      name: null,
      id: "id-6",
    },
    {
      content: "",
      additional_kwargs: {},
      response_metadata: {},
      type: "ai",
      name: null,
      id: "id-5",
      tool_calls: [
        {
          name: "change_background",
          args: {
            background: "blue",
          },
          id: "id-4",
          type: "tool_call",
        },
      ],
      invalid_tool_calls: [],
      usage_metadata: null,
    },
    {
      content: '{"status":"success","message":"Background changed to blue"}',
      additional_kwargs: {},
      response_metadata: {},
      type: "tool",
      name: null,
      id: "id-8",
      tool_call_id: "id-4",
      artifact: null,
      status: "success",
    },
    {
      content: "Done! I've completed that for you.",
      additional_kwargs: {},
      response_metadata: {
        finish_reason: "stop",
        model_name: "gpt-4.1-mini",
        model_provider: "openai",
      },
      type: "ai",
      name: null,
      id: "id-9",
      tool_calls: [],
      invalid_tool_calls: [],
      usage_metadata: null,
    },
    {
      content: "Hi change the background color to pink",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
      name: null,
      id: "id-11",
    },
    {
      content: "",
      additional_kwargs: {},
      response_metadata: {},
      type: "ai",
      name: null,
      id: "id-13",
      tool_calls: [
        {
          name: "change_background",
          args: {
            background: "pink",
          },
          id: "id-12",
          type: "tool_call",
        },
      ],
      invalid_tool_calls: [],
      usage_metadata: null,
    },
  ],
  copilotkit: {
    intercepted_tool_calls: null,
    original_ai_message_id: null,
  },
} as const;
const shared9 = {
  messages: [
    {
      content: "Hi change the background color to blue",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
      name: null,
      id: "id-3",
    },
    {
      content: shared3,
      additional_kwargs: {},
      response_metadata: {},
      type: "system",
      name: null,
      id: "id-6",
    },
    {
      content: "",
      additional_kwargs: {},
      response_metadata: {},
      type: "ai",
      name: null,
      id: "id-5",
      tool_calls: [
        {
          name: "change_background",
          args: {
            background: "blue",
          },
          id: "id-4",
          type: "tool_call",
        },
      ],
      invalid_tool_calls: [],
      usage_metadata: null,
    },
    {
      content: '{"status":"success","message":"Background changed to blue"}',
      additional_kwargs: {},
      response_metadata: {},
      type: "tool",
      name: null,
      id: "id-8",
      tool_call_id: "id-4",
      artifact: null,
      status: "success",
    },
    {
      content: "Done! I've completed that for you.",
      additional_kwargs: {},
      response_metadata: {
        finish_reason: "stop",
        model_name: "gpt-4.1-mini",
        model_provider: "openai",
      },
      type: "ai",
      name: null,
      id: "id-9",
      tool_calls: [],
      invalid_tool_calls: [],
      usage_metadata: null,
    },
  ],
  copilotkit: {
    actions: [
      {
        name: "change_background",
        description: shared2,
        parameters: {
          type: "object",
          properties: {
            background: {
              type: "string",
              description:
                "The background. Prefer gradients. Only use when asked.",
            },
          },
          required: ["background"],
        },
      },
    ],
    context: [
      {
        description: "Name of the user",
        value: "Bob",
      },
    ],
  },
} as const;
const shared10 = {
  messages: [
    {
      content: "Hey there",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
      name: null,
      id: "id-3",
    },
    {
      content: shared3,
      additional_kwargs: {},
      response_metadata: {},
      type: "system",
      name: null,
      id: "id-5",
    },
    {
      content: "Hello! How can I assist you today?",
      additional_kwargs: {},
      response_metadata: {
        finish_reason: "stop",
        model_name: "gpt-4.1-mini",
        model_provider: "openai",
      },
      type: "ai",
      name: null,
      id: "id-4",
      tool_calls: [],
      invalid_tool_calls: [],
      usage_metadata: null,
    },
    {
      content: "My favorite fruit is Mango",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
      name: null,
      id: "id-7",
    },
    {
      content: shared5,
      additional_kwargs: {},
      response_metadata: {
        finish_reason: "stop",
        model_name: "gpt-4.1-mini",
        model_provider: "openai",
      },
      type: "ai",
      name: null,
      id: "id-8",
      tool_calls: [],
      invalid_tool_calls: [],
      usage_metadata: null,
    },
  ],
  copilotkit: {
    actions: [
      {
        name: "change_background",
        description: shared2,
        parameters: {
          type: "object",
          properties: {
            background: {
              type: "string",
              description:
                "The background. Prefer gradients. Only use when asked.",
            },
          },
          required: ["background"],
        },
      },
    ],
    context: [
      {
        description: "Name of the user",
        value: "Bob",
      },
    ],
  },
} as const;
const shared11 = {
  messages: [
    {
      content: "Hey there",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
      name: null,
      id: "id-3",
    },
    {
      content: shared3,
      additional_kwargs: {},
      response_metadata: {},
      type: "system",
      name: null,
      id: "id-5",
    },
    {
      content: "Hello! How can I assist you today?",
      additional_kwargs: {},
      response_metadata: {
        finish_reason: "stop",
        model_name: "gpt-4.1-mini",
        model_provider: "openai",
      },
      type: "ai",
      name: null,
      id: "id-4",
      tool_calls: [],
      invalid_tool_calls: [],
      usage_metadata: null,
    },
  ],
  copilotkit: {
    actions: [
      {
        name: "change_background",
        description: shared2,
        parameters: {
          type: "object",
          properties: {
            background: {
              type: "string",
              description:
                "The background. Prefer gradients. Only use when asked.",
            },
          },
          required: ["background"],
        },
      },
    ],
    context: [
      {
        description: "Name of the user",
        value: "Bob",
      },
    ],
  },
} as const;
const shared12 = {
  messages: [
    {
      content: "Hi change the background color to blue",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
      name: null,
      id: "id-3",
    },
    {
      content: shared3,
      additional_kwargs: {},
      response_metadata: {},
      type: "system",
      name: null,
      id: "id-6",
    },
    {
      content: "",
      additional_kwargs: {},
      response_metadata: {},
      type: "ai",
      name: null,
      id: "id-5",
      tool_calls: [
        {
          name: "change_background",
          args: {
            background: "blue",
          },
          id: "id-4",
          type: "tool_call",
        },
      ],
      invalid_tool_calls: [],
      usage_metadata: null,
    },
  ],
  copilotkit: {
    intercepted_tool_calls: null,
    original_ai_message_id: null,
  },
} as const;
const shared13 = {
  content: '{"status":"success","message":"Background changed to pink"}',
  additional_kwargs: {},
  response_metadata: {},
  type: "tool",
  name: null,
  id: "id-15",
  tool_call_id: "id-12",
  artifact: null,
  status: "success",
} as const;
const shared14 = {
  id: "id-14",
  role: "assistant",
  content: shared1,
} as const;
const shared15 = {
  content: shared3,
  additional_kwargs: {},
  response_metadata: {},
  type: "system",
  name: null,
  id: null,
} as const;
const shared16 = {
  id: "id-13",
  role: "assistant",
  content: "",
  toolCalls: [
    {
      id: "id-12",
      type: "function",
      function: {
        name: "change_background",
        arguments: '{"background": "pink"}',
      },
    },
  ],
} as const;
const shared17 = {
  id: "id-5",
  role: "assistant",
  content: "",
  toolCalls: [
    {
      id: "id-4",
      type: "function",
      function: {
        name: "change_background",
        arguments: '{"background": "blue"}',
      },
    },
  ],
} as const;
const shared18 = {
  content: "Can you remind me what my favorite fruit is?",
  additional_kwargs: {},
  response_metadata: {},
  type: "human",
  name: null,
  id: "id-16",
} as const;
const shared19 = {
  id: "id-11",
  role: "assistant",
  content: shared4,
} as const;
const shared20 = {
  id: "id-5",
  role: "system",
  content: shared3,
} as const;
const shared21 = {
  id: "id-6",
  role: "system",
  content: shared3,
} as const;
const shared22 = {
  id: "id-8",
  role: "assistant",
  content: shared5,
} as const;
const shared23 = {
  id: "id-15",
  role: "tool",
  content: '{"status":"success","message":"Background changed to pink"}',
  toolCallId: "id-12",
} as const;
const shared24 = {
  id: "id-8",
  role: "tool",
  content: '{"status":"success","message":"Background changed to blue"}',
  toolCallId: "id-4",
} as const;
const shared25 = {
  content: "Hi, I am duaa",
  additional_kwargs: {},
  response_metadata: {},
  type: "human",
  name: null,
  id: "id-3",
} as const;
const shared26 = {
  id: "id-16",
  role: "user",
  content: "Can you remind me what my favorite fruit is?",
} as const;

export const agenticChatPageEventTrace = defineEventTrace(import.meta.url, {
  agenticChatChangesBackgroundOnMessageAndReset: [
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-2",
      input: {
        threadId: "id-1",
        runId: "id-2",
        protocolVersion: "1.0",
        state: {},
        messages: [
          {
            id: "id-3",
            role: "user",
            content: "Hi change the background color to blue",
          },
        ],
        tools: [
          {
            name: "change_background",
            description: shared2,
            parameters: {
              type: "object",
              properties: {
                background: {
                  type: "string",
                  description:
                    "The background. Prefer gradients. Only use when asked.",
                },
              },
              required: ["background"],
            },
          },
        ],
        context: [
          {
            description: "Name of the user",
            value: "Bob",
          },
        ],
        forwardedProps: {},
      },
    },
    {
      type: "STEP_STARTED",
      stepName: "CopilotKitMiddleware.before_agent",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          shared15,
          {
            content: "Hi change the background color to blue",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-3",
          },
        ],
        tools: [
          {
            name: "change_background",
            description: shared2,
            parameters: {
              type: "object",
              properties: {
                background: {
                  type: "string",
                  description:
                    "The background. Prefer gradients. Only use when asked.",
                },
              },
              required: ["background"],
            },
          },
        ],
        copilotkit: {
          actions: [
            {
              name: "change_background",
              description: shared2,
              parameters: {
                type: "object",
                properties: {
                  background: {
                    type: "string",
                    description:
                      "The background. Prefer gradients. Only use when asked.",
                  },
                },
                required: ["background"],
              },
            },
          ],
          context: [
            {
              description: "Name of the user",
              value: "Bob",
            },
          ],
        },
      },
    },
    {
      type: "STEP_FINISHED",
      stepName: "CopilotKitMiddleware.before_agent",
    },
    {
      type: "STEP_STARTED",
      stepName: "model",
    },
    {
      type: "TOOL_CALL_START",
      toolCallId: "id-4",
      toolCallName: "change_background",
      parentMessageId: "id-5",
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: '{"background":"blue"',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: "}",
    },
    {
      type: "TOOL_CALL_END",
      toolCallId: "id-4",
    },
    {
      type: "STEP_FINISHED",
      stepName: "model",
    },
    {
      type: "STEP_STARTED",
      stepName: "CopilotKitMiddleware.after_model",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            content: "Hi change the background color to blue",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-3",
          },
          {
            content: shared3,
            additional_kwargs: {},
            response_metadata: {},
            type: "system",
            name: null,
            id: "id-6",
          },
          {
            content: "",
            additional_kwargs: {},
            response_metadata: {},
            type: "ai",
            name: null,
            id: "id-5",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
        ],
        tools: [
          {
            name: "change_background",
            description: shared2,
            parameters: {
              type: "object",
              properties: {
                background: {
                  type: "string",
                  description:
                    "The background. Prefer gradients. Only use when asked.",
                },
              },
              required: ["background"],
            },
          },
        ],
        copilotkit: {
          intercepted_tool_calls: [
            {
              name: "change_background",
              args: {
                background: "blue",
              },
              id: "call_change_background_1",
              type: "tool_call",
            },
          ],
          original_ai_message_id: "id-5",
        },
      },
    },
    {
      type: "STEP_FINISHED",
      stepName: "CopilotKitMiddleware.after_model",
    },
    {
      type: "STEP_STARTED",
      stepName: "CopilotKitMiddleware.after_agent",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            content: "Hi change the background color to blue",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-3",
          },
          {
            content: shared3,
            additional_kwargs: {},
            response_metadata: {},
            type: "system",
            name: null,
            id: "id-6",
          },
          {
            content: "",
            additional_kwargs: {},
            response_metadata: {},
            type: "ai",
            name: null,
            id: "id-5",
            tool_calls: [
              {
                name: "change_background",
                args: {
                  background: "blue",
                },
                id: "id-4",
                type: "tool_call",
              },
            ],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
        ],
        tools: [
          {
            name: "change_background",
            description: shared2,
            parameters: {
              type: "object",
              properties: {
                background: {
                  type: "string",
                  description:
                    "The background. Prefer gradients. Only use when asked.",
                },
              },
              required: ["background"],
            },
          },
        ],
        copilotkit: {
          intercepted_tool_calls: null,
          original_ai_message_id: null,
        },
      },
    },
    {
      type: "STEP_FINISHED",
      stepName: "CopilotKitMiddleware.after_agent",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: shared12,
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hi change the background color to blue",
        },
        shared21,
        shared17,
      ],
    },
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-2",
    },
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-7",
      input: {
        threadId: "id-1",
        runId: "id-7",
        protocolVersion: "1.0",
        state: shared12,
        messages: [shared17, shared24, shared21],
        tools: [
          {
            name: "change_background",
            description: shared2,
            parameters: {
              type: "object",
              properties: {
                background: {
                  type: "string",
                  description:
                    "The background. Prefer gradients. Only use when asked.",
                },
              },
              required: ["background"],
            },
          },
        ],
        context: [
          {
            description: "Name of the user",
            value: "Bob",
          },
        ],
        forwardedProps: {},
      },
    },
    {
      type: "STEP_STARTED",
      stepName: "CopilotKitMiddleware.before_agent",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            content: "Hi change the background color to blue",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-3",
          },
          {
            content: shared3,
            additional_kwargs: {},
            response_metadata: {},
            type: "system",
            name: null,
            id: "id-6",
          },
          {
            content: "",
            additional_kwargs: {},
            response_metadata: {},
            type: "ai",
            name: null,
            id: "id-5",
            tool_calls: [
              {
                name: "change_background",
                args: {
                  background: "blue",
                },
                id: "id-4",
                type: "tool_call",
              },
            ],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          {
            content:
              '{"status":"success","message":"Background changed to blue"}',
            additional_kwargs: {},
            response_metadata: {},
            type: "tool",
            name: null,
            id: "id-8",
            tool_call_id: "id-4",
            artifact: null,
            status: "success",
          },
        ],
        copilotkit: {
          actions: [
            {
              name: "change_background",
              description: shared2,
              parameters: {
                type: "object",
                properties: {
                  background: {
                    type: "string",
                    description:
                      "The background. Prefer gradients. Only use when asked.",
                  },
                },
                required: ["background"],
              },
            },
          ],
          context: [
            {
              description: "Name of the user",
              value: "Bob",
            },
          ],
        },
        tools: [
          {
            name: "change_background",
            description: shared2,
            parameters: {
              type: "object",
              properties: {
                background: {
                  type: "string",
                  description:
                    "The background. Prefer gradients. Only use when asked.",
                },
              },
              required: ["background"],
            },
          },
        ],
      },
    },
    {
      type: "STEP_FINISHED",
      stepName: "CopilotKitMiddleware.before_agent",
    },
    {
      type: "STEP_STARTED",
      stepName: "model",
    },
    {
      type: "TEXT_MESSAGE_START",
      messageId: "id-9",
      role: "assistant",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-9",
      delta: "Done! I've completed",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-9",
      delta: " that for you.",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-9",
    },
    {
      type: "STEP_FINISHED",
      stepName: "model",
    },
    {
      type: "STEP_STARTED",
      stepName: "CopilotKitMiddleware.after_model",
    },
    {
      type: "STEP_FINISHED",
      stepName: "CopilotKitMiddleware.after_model",
    },
    {
      type: "STEP_STARTED",
      stepName: "CopilotKitMiddleware.after_agent",
    },
    {
      type: "STEP_FINISHED",
      stepName: "CopilotKitMiddleware.after_agent",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: shared9,
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hi change the background color to blue",
        },
        shared21,
        shared17,
        shared24,
        {
          id: "id-9",
          role: "assistant",
          content: "Done! I've completed that for you.",
        },
      ],
    },
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-7",
    },
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-10",
      input: {
        threadId: "id-1",
        runId: "id-10",
        protocolVersion: "1.0",
        state: shared9,
        messages: [
          {
            id: "id-11",
            role: "user",
            content: "Hi change the background color to pink",
          },
        ],
        tools: [
          {
            name: "change_background",
            description: shared2,
            parameters: {
              type: "object",
              properties: {
                background: {
                  type: "string",
                  description:
                    "The background. Prefer gradients. Only use when asked.",
                },
              },
              required: ["background"],
            },
          },
        ],
        context: [
          {
            description: "Name of the user",
            value: "Bob",
          },
        ],
        forwardedProps: {},
      },
    },
    {
      type: "STEP_STARTED",
      stepName: "CopilotKitMiddleware.before_agent",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            content: "Hi change the background color to blue",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-3",
          },
          {
            content: shared3,
            additional_kwargs: {},
            response_metadata: {},
            type: "system",
            name: null,
            id: "id-6",
          },
          {
            content: "",
            additional_kwargs: {},
            response_metadata: {},
            type: "ai",
            name: null,
            id: "id-5",
            tool_calls: [
              {
                name: "change_background",
                args: {
                  background: "blue",
                },
                id: "id-4",
                type: "tool_call",
              },
            ],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          {
            content:
              '{"status":"success","message":"Background changed to blue"}',
            additional_kwargs: {},
            response_metadata: {},
            type: "tool",
            name: null,
            id: "id-8",
            tool_call_id: "id-4",
            artifact: null,
            status: "success",
          },
          {
            content: "Done! I've completed that for you.",
            additional_kwargs: {},
            response_metadata: {
              finish_reason: "stop",
              model_name: "gpt-4.1-mini",
              model_provider: "openai",
            },
            type: "ai",
            name: null,
            id: "id-9",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          {
            content: "Hi change the background color to pink",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-11",
          },
        ],
        copilotkit: {
          actions: [
            {
              name: "change_background",
              description: shared2,
              parameters: {
                type: "object",
                properties: {
                  background: {
                    type: "string",
                    description:
                      "The background. Prefer gradients. Only use when asked.",
                  },
                },
                required: ["background"],
              },
            },
          ],
          context: [
            {
              description: "Name of the user",
              value: "Bob",
            },
          ],
        },
        tools: [
          {
            name: "change_background",
            description: shared2,
            parameters: {
              type: "object",
              properties: {
                background: {
                  type: "string",
                  description:
                    "The background. Prefer gradients. Only use when asked.",
                },
              },
              required: ["background"],
            },
          },
        ],
      },
    },
    {
      type: "STEP_FINISHED",
      stepName: "CopilotKitMiddleware.before_agent",
    },
    {
      type: "STEP_STARTED",
      stepName: "model",
    },
    {
      type: "TOOL_CALL_START",
      toolCallId: "id-12",
      toolCallName: "change_background",
      parentMessageId: "id-13",
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-12",
      delta: '{"background":"pink"',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-12",
      delta: "}",
    },
    {
      type: "TOOL_CALL_END",
      toolCallId: "id-12",
    },
    {
      type: "STEP_FINISHED",
      stepName: "model",
    },
    {
      type: "STEP_STARTED",
      stepName: "CopilotKitMiddleware.after_model",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            content: "Hi change the background color to blue",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-3",
          },
          {
            content: shared3,
            additional_kwargs: {},
            response_metadata: {},
            type: "system",
            name: null,
            id: "id-6",
          },
          {
            content: "",
            additional_kwargs: {},
            response_metadata: {},
            type: "ai",
            name: null,
            id: "id-5",
            tool_calls: [
              {
                name: "change_background",
                args: {
                  background: "blue",
                },
                id: "id-4",
                type: "tool_call",
              },
            ],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          {
            content:
              '{"status":"success","message":"Background changed to blue"}',
            additional_kwargs: {},
            response_metadata: {},
            type: "tool",
            name: null,
            id: "id-8",
            tool_call_id: "id-4",
            artifact: null,
            status: "success",
          },
          {
            content: "Done! I've completed that for you.",
            additional_kwargs: {},
            response_metadata: {
              finish_reason: "stop",
              model_name: "gpt-4.1-mini",
              model_provider: "openai",
            },
            type: "ai",
            name: null,
            id: "id-9",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          {
            content: "Hi change the background color to pink",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-11",
          },
          {
            content: "",
            additional_kwargs: {},
            response_metadata: {},
            type: "ai",
            name: null,
            id: "id-13",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
        ],
        copilotkit: {
          intercepted_tool_calls: [
            {
              name: "change_background",
              args: {
                background: "pink",
              },
              id: "call_change_background_2",
              type: "tool_call",
            },
          ],
          original_ai_message_id: "id-13",
        },
        tools: [
          {
            name: "change_background",
            description: shared2,
            parameters: {
              type: "object",
              properties: {
                background: {
                  type: "string",
                  description:
                    "The background. Prefer gradients. Only use when asked.",
                },
              },
              required: ["background"],
            },
          },
        ],
      },
    },
    {
      type: "STEP_FINISHED",
      stepName: "CopilotKitMiddleware.after_model",
    },
    {
      type: "STEP_STARTED",
      stepName: "CopilotKitMiddleware.after_agent",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            content: "Hi change the background color to blue",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-3",
          },
          {
            content: shared3,
            additional_kwargs: {},
            response_metadata: {},
            type: "system",
            name: null,
            id: "id-6",
          },
          {
            content: "",
            additional_kwargs: {},
            response_metadata: {},
            type: "ai",
            name: null,
            id: "id-5",
            tool_calls: [
              {
                name: "change_background",
                args: {
                  background: "blue",
                },
                id: "id-4",
                type: "tool_call",
              },
            ],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          {
            content:
              '{"status":"success","message":"Background changed to blue"}',
            additional_kwargs: {},
            response_metadata: {},
            type: "tool",
            name: null,
            id: "id-8",
            tool_call_id: "id-4",
            artifact: null,
            status: "success",
          },
          {
            content: "Done! I've completed that for you.",
            additional_kwargs: {},
            response_metadata: {
              finish_reason: "stop",
              model_name: "gpt-4.1-mini",
              model_provider: "openai",
            },
            type: "ai",
            name: null,
            id: "id-9",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          {
            content: "Hi change the background color to pink",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-11",
          },
          {
            content: "",
            additional_kwargs: {},
            response_metadata: {},
            type: "ai",
            name: null,
            id: "id-13",
            tool_calls: [
              {
                name: "change_background",
                args: {
                  background: "pink",
                },
                id: "id-12",
                type: "tool_call",
              },
            ],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
        ],
        copilotkit: {
          intercepted_tool_calls: null,
          original_ai_message_id: null,
        },
        tools: [
          {
            name: "change_background",
            description: shared2,
            parameters: {
              type: "object",
              properties: {
                background: {
                  type: "string",
                  description:
                    "The background. Prefer gradients. Only use when asked.",
                },
              },
              required: ["background"],
            },
          },
        ],
      },
    },
    {
      type: "STEP_FINISHED",
      stepName: "CopilotKitMiddleware.after_agent",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: shared8,
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hi change the background color to blue",
        },
        shared21,
        shared17,
        shared24,
        {
          id: "id-9",
          role: "assistant",
          content: "Done! I've completed that for you.",
        },
        {
          id: "id-11",
          role: "user",
          content: "Hi change the background color to pink",
        },
        shared16,
      ],
    },
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-10",
    },
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-14",
      input: {
        threadId: "id-1",
        runId: "id-14",
        protocolVersion: "1.0",
        state: shared8,
        messages: [shared16, shared23],
        tools: [
          {
            name: "change_background",
            description: shared2,
            parameters: {
              type: "object",
              properties: {
                background: {
                  type: "string",
                  description:
                    "The background. Prefer gradients. Only use when asked.",
                },
              },
              required: ["background"],
            },
          },
        ],
        context: [
          {
            description: "Name of the user",
            value: "Bob",
          },
        ],
        forwardedProps: {},
      },
    },
    {
      type: "STEP_STARTED",
      stepName: "CopilotKitMiddleware.before_agent",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            content: "Hi change the background color to blue",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-3",
          },
          {
            content: shared3,
            additional_kwargs: {},
            response_metadata: {},
            type: "system",
            name: null,
            id: "id-6",
          },
          {
            content: "",
            additional_kwargs: {},
            response_metadata: {},
            type: "ai",
            name: null,
            id: "id-5",
            tool_calls: [
              {
                name: "change_background",
                args: {
                  background: "blue",
                },
                id: "id-4",
                type: "tool_call",
              },
            ],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          {
            content:
              '{"status":"success","message":"Background changed to blue"}',
            additional_kwargs: {},
            response_metadata: {},
            type: "tool",
            name: null,
            id: "id-8",
            tool_call_id: "id-4",
            artifact: null,
            status: "success",
          },
          {
            content: "Done! I've completed that for you.",
            additional_kwargs: {},
            response_metadata: {
              finish_reason: "stop",
              model_name: "gpt-4.1-mini",
              model_provider: "openai",
            },
            type: "ai",
            name: null,
            id: "id-9",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          {
            content: "Hi change the background color to pink",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-11",
          },
          {
            content: "",
            additional_kwargs: {},
            response_metadata: {},
            type: "ai",
            name: null,
            id: "id-13",
            tool_calls: [
              {
                name: "change_background",
                args: {
                  background: "pink",
                },
                id: "id-12",
                type: "tool_call",
              },
            ],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          shared13,
        ],
        copilotkit: {
          actions: [
            {
              name: "change_background",
              description: shared2,
              parameters: {
                type: "object",
                properties: {
                  background: {
                    type: "string",
                    description:
                      "The background. Prefer gradients. Only use when asked.",
                  },
                },
                required: ["background"],
              },
            },
          ],
          context: [
            {
              description: "Name of the user",
              value: "Bob",
            },
          ],
        },
        tools: [
          {
            name: "change_background",
            description: shared2,
            parameters: {
              type: "object",
              properties: {
                background: {
                  type: "string",
                  description:
                    "The background. Prefer gradients. Only use when asked.",
                },
              },
              required: ["background"],
            },
          },
        ],
      },
    },
    {
      type: "STEP_FINISHED",
      stepName: "CopilotKitMiddleware.before_agent",
    },
    {
      type: "STEP_STARTED",
      stepName: "model",
    },
    {
      type: "TEXT_MESSAGE_START",
      messageId: "id-16",
      role: "assistant",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-16",
      delta: "Done! I've completed",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-16",
      delta: " that for you.",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-16",
    },
    {
      type: "STEP_FINISHED",
      stepName: "model",
    },
    {
      type: "STEP_STARTED",
      stepName: "CopilotKitMiddleware.after_model",
    },
    {
      type: "STEP_FINISHED",
      stepName: "CopilotKitMiddleware.after_model",
    },
    {
      type: "STEP_STARTED",
      stepName: "CopilotKitMiddleware.after_agent",
    },
    {
      type: "STEP_FINISHED",
      stepName: "CopilotKitMiddleware.after_agent",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            content: "Hi change the background color to blue",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-3",
          },
          {
            content: shared3,
            additional_kwargs: {},
            response_metadata: {},
            type: "system",
            name: null,
            id: "id-6",
          },
          {
            content: "",
            additional_kwargs: {},
            response_metadata: {},
            type: "ai",
            name: null,
            id: "id-5",
            tool_calls: [
              {
                name: "change_background",
                args: {
                  background: "blue",
                },
                id: "id-4",
                type: "tool_call",
              },
            ],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          {
            content:
              '{"status":"success","message":"Background changed to blue"}',
            additional_kwargs: {},
            response_metadata: {},
            type: "tool",
            name: null,
            id: "id-8",
            tool_call_id: "id-4",
            artifact: null,
            status: "success",
          },
          {
            content: "Done! I've completed that for you.",
            additional_kwargs: {},
            response_metadata: {
              finish_reason: "stop",
              model_name: "gpt-4.1-mini",
              model_provider: "openai",
            },
            type: "ai",
            name: null,
            id: "id-9",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          {
            content: "Hi change the background color to pink",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-11",
          },
          {
            content: "",
            additional_kwargs: {},
            response_metadata: {},
            type: "ai",
            name: null,
            id: "id-13",
            tool_calls: [
              {
                name: "change_background",
                args: {
                  background: "pink",
                },
                id: "id-12",
                type: "tool_call",
              },
            ],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          shared13,
          {
            content: "Done! I've completed that for you.",
            additional_kwargs: {},
            response_metadata: {
              finish_reason: "stop",
              model_name: "gpt-4.1-mini",
              model_provider: "openai",
            },
            type: "ai",
            name: null,
            id: "id-16",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
        ],
        copilotkit: {
          actions: [
            {
              name: "change_background",
              description: shared2,
              parameters: {
                type: "object",
                properties: {
                  background: {
                    type: "string",
                    description:
                      "The background. Prefer gradients. Only use when asked.",
                  },
                },
                required: ["background"],
              },
            },
          ],
          context: [
            {
              description: "Name of the user",
              value: "Bob",
            },
          ],
        },
      },
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hi change the background color to blue",
        },
        shared21,
        shared17,
        shared24,
        {
          id: "id-9",
          role: "assistant",
          content: "Done! I've completed that for you.",
        },
        {
          id: "id-11",
          role: "user",
          content: "Hi change the background color to pink",
        },
        shared16,
        shared23,
        {
          id: "id-16",
          role: "assistant",
          content: "Done! I've completed that for you.",
        },
      ],
    },
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-14",
    },
  ],
  agenticChatRetainsMemoryOfUserMessagesDuringAConversation: [
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-2",
      input: {
        threadId: "id-1",
        runId: "id-2",
        protocolVersion: "1.0",
        state: {},
        messages: [
          {
            id: "id-3",
            role: "user",
            content: "Hey there",
          },
        ],
        tools: [
          {
            name: "change_background",
            description: shared2,
            parameters: {
              type: "object",
              properties: {
                background: {
                  type: "string",
                  description:
                    "The background. Prefer gradients. Only use when asked.",
                },
              },
              required: ["background"],
            },
          },
        ],
        context: [
          {
            description: "Name of the user",
            value: "Bob",
          },
        ],
        forwardedProps: {},
      },
    },
    {
      type: "STEP_STARTED",
      stepName: "CopilotKitMiddleware.before_agent",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          shared15,
          {
            content: "Hey there",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-3",
          },
        ],
        tools: [
          {
            name: "change_background",
            description: shared2,
            parameters: {
              type: "object",
              properties: {
                background: {
                  type: "string",
                  description:
                    "The background. Prefer gradients. Only use when asked.",
                },
              },
              required: ["background"],
            },
          },
        ],
        copilotkit: {
          actions: [
            {
              name: "change_background",
              description: shared2,
              parameters: {
                type: "object",
                properties: {
                  background: {
                    type: "string",
                    description:
                      "The background. Prefer gradients. Only use when asked.",
                  },
                },
                required: ["background"],
              },
            },
          ],
          context: [
            {
              description: "Name of the user",
              value: "Bob",
            },
          ],
        },
      },
    },
    {
      type: "STEP_FINISHED",
      stepName: "CopilotKitMiddleware.before_agent",
    },
    {
      type: "STEP_STARTED",
      stepName: "model",
    },
    {
      type: "TEXT_MESSAGE_START",
      messageId: "id-4",
      role: "assistant",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: "Hello! How can I ass",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: "ist you today?",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-4",
    },
    {
      type: "STEP_FINISHED",
      stepName: "model",
    },
    {
      type: "STEP_STARTED",
      stepName: "CopilotKitMiddleware.after_model",
    },
    {
      type: "STEP_FINISHED",
      stepName: "CopilotKitMiddleware.after_model",
    },
    {
      type: "STEP_STARTED",
      stepName: "CopilotKitMiddleware.after_agent",
    },
    {
      type: "STEP_FINISHED",
      stepName: "CopilotKitMiddleware.after_agent",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: shared11,
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hey there",
        },
        shared20,
        {
          id: "id-4",
          role: "assistant",
          content: "Hello! How can I assist you today?",
        },
      ],
    },
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-2",
    },
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-6",
      input: {
        threadId: "id-1",
        runId: "id-6",
        protocolVersion: "1.0",
        state: shared11,
        messages: [
          shared20,
          {
            id: "id-7",
            role: "user",
            content: "My favorite fruit is Mango",
          },
        ],
        tools: [
          {
            name: "change_background",
            description: shared2,
            parameters: {
              type: "object",
              properties: {
                background: {
                  type: "string",
                  description:
                    "The background. Prefer gradients. Only use when asked.",
                },
              },
              required: ["background"],
            },
          },
        ],
        context: [
          {
            description: "Name of the user",
            value: "Bob",
          },
        ],
        forwardedProps: {},
      },
    },
    {
      type: "STEP_STARTED",
      stepName: "CopilotKitMiddleware.before_agent",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            content: "Hey there",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-3",
          },
          {
            content: shared3,
            additional_kwargs: {},
            response_metadata: {},
            type: "system",
            name: null,
            id: "id-5",
          },
          {
            content: "Hello! How can I assist you today?",
            additional_kwargs: {},
            response_metadata: {
              finish_reason: "stop",
              model_name: "gpt-4.1-mini",
              model_provider: "openai",
            },
            type: "ai",
            name: null,
            id: "id-4",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          {
            content: "My favorite fruit is Mango",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-7",
          },
        ],
        copilotkit: {
          actions: [
            {
              name: "change_background",
              description: shared2,
              parameters: {
                type: "object",
                properties: {
                  background: {
                    type: "string",
                    description:
                      "The background. Prefer gradients. Only use when asked.",
                  },
                },
                required: ["background"],
              },
            },
          ],
          context: [
            {
              description: "Name of the user",
              value: "Bob",
            },
          ],
        },
        tools: [
          {
            name: "change_background",
            description: shared2,
            parameters: {
              type: "object",
              properties: {
                background: {
                  type: "string",
                  description:
                    "The background. Prefer gradients. Only use when asked.",
                },
              },
              required: ["background"],
            },
          },
        ],
      },
    },
    {
      type: "STEP_FINISHED",
      stepName: "CopilotKitMiddleware.before_agent",
    },
    {
      type: "STEP_STARTED",
      stepName: "model",
    },
    {
      type: "TEXT_MESSAGE_START",
      messageId: "id-8",
      role: "assistant",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-8",
      delta: "That's great! Mango ",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-8",
      delta: "is a wonderful tropi",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-8",
      delta: "cal fruit known for ",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-8",
      delta: "its sweet, juicy fla",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-8",
      delta: "vor.",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-8",
    },
    {
      type: "STEP_FINISHED",
      stepName: "model",
    },
    {
      type: "STEP_STARTED",
      stepName: "CopilotKitMiddleware.after_model",
    },
    {
      type: "STEP_FINISHED",
      stepName: "CopilotKitMiddleware.after_model",
    },
    {
      type: "STEP_STARTED",
      stepName: "CopilotKitMiddleware.after_agent",
    },
    {
      type: "STEP_FINISHED",
      stepName: "CopilotKitMiddleware.after_agent",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: shared10,
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hey there",
        },
        shared20,
        {
          id: "id-4",
          role: "assistant",
          content: "Hello! How can I assist you today?",
        },
        {
          id: "id-7",
          role: "user",
          content: "My favorite fruit is Mango",
        },
        shared22,
      ],
    },
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-6",
    },
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-9",
      input: {
        threadId: "id-1",
        runId: "id-9",
        protocolVersion: "1.0",
        state: shared10,
        messages: [
          {
            id: "id-10",
            role: "user",
            content: "and I love listening to Kaavish",
          },
        ],
        tools: [
          {
            name: "change_background",
            description: shared2,
            parameters: {
              type: "object",
              properties: {
                background: {
                  type: "string",
                  description:
                    "The background. Prefer gradients. Only use when asked.",
                },
              },
              required: ["background"],
            },
          },
        ],
        context: [
          {
            description: "Name of the user",
            value: "Bob",
          },
        ],
        forwardedProps: {},
      },
    },
    {
      type: "STEP_STARTED",
      stepName: "CopilotKitMiddleware.before_agent",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            content: "Hey there",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-3",
          },
          {
            content: shared3,
            additional_kwargs: {},
            response_metadata: {},
            type: "system",
            name: null,
            id: "id-5",
          },
          {
            content: "Hello! How can I assist you today?",
            additional_kwargs: {},
            response_metadata: {
              finish_reason: "stop",
              model_name: "gpt-4.1-mini",
              model_provider: "openai",
            },
            type: "ai",
            name: null,
            id: "id-4",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          {
            content: "My favorite fruit is Mango",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-7",
          },
          {
            content: shared5,
            additional_kwargs: {},
            response_metadata: {
              finish_reason: "stop",
              model_name: "gpt-4.1-mini",
              model_provider: "openai",
            },
            type: "ai",
            name: null,
            id: "id-8",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          {
            content: "and I love listening to Kaavish",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-10",
          },
        ],
        copilotkit: {
          actions: [
            {
              name: "change_background",
              description: shared2,
              parameters: {
                type: "object",
                properties: {
                  background: {
                    type: "string",
                    description:
                      "The background. Prefer gradients. Only use when asked.",
                  },
                },
                required: ["background"],
              },
            },
          ],
          context: [
            {
              description: "Name of the user",
              value: "Bob",
            },
          ],
        },
        tools: [
          {
            name: "change_background",
            description: shared2,
            parameters: {
              type: "object",
              properties: {
                background: {
                  type: "string",
                  description:
                    "The background. Prefer gradients. Only use when asked.",
                },
              },
              required: ["background"],
            },
          },
        ],
      },
    },
    {
      type: "STEP_FINISHED",
      stepName: "CopilotKitMiddleware.before_agent",
    },
    {
      type: "STEP_STARTED",
      stepName: "model",
    },
    {
      type: "TEXT_MESSAGE_START",
      messageId: "id-11",
      role: "assistant",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-11",
      delta: "Kaavish is a wonderf",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-11",
      delta: "ul musical group kno",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-11",
      delta: "wn for their unique ",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-11",
      delta: "blend of Eastern and",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-11",
      delta: " Western sounds!",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-11",
    },
    {
      type: "STEP_FINISHED",
      stepName: "model",
    },
    {
      type: "STEP_STARTED",
      stepName: "CopilotKitMiddleware.after_model",
    },
    {
      type: "STEP_FINISHED",
      stepName: "CopilotKitMiddleware.after_model",
    },
    {
      type: "STEP_STARTED",
      stepName: "CopilotKitMiddleware.after_agent",
    },
    {
      type: "STEP_FINISHED",
      stepName: "CopilotKitMiddleware.after_agent",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: shared7,
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hey there",
        },
        shared20,
        {
          id: "id-4",
          role: "assistant",
          content: "Hello! How can I assist you today?",
        },
        {
          id: "id-7",
          role: "user",
          content: "My favorite fruit is Mango",
        },
        shared22,
        {
          id: "id-10",
          role: "user",
          content: "and I love listening to Kaavish",
        },
        shared19,
      ],
    },
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-9",
    },
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-12",
      input: {
        threadId: "id-1",
        runId: "id-12",
        protocolVersion: "1.0",
        state: shared7,
        messages: [
          {
            id: "id-13",
            role: "user",
            content: "tell me an interesting fact about Moon",
          },
        ],
        tools: [
          {
            name: "change_background",
            description: shared2,
            parameters: {
              type: "object",
              properties: {
                background: {
                  type: "string",
                  description:
                    "The background. Prefer gradients. Only use when asked.",
                },
              },
              required: ["background"],
            },
          },
        ],
        context: [
          {
            description: "Name of the user",
            value: "Bob",
          },
        ],
        forwardedProps: {},
      },
    },
    {
      type: "STEP_STARTED",
      stepName: "CopilotKitMiddleware.before_agent",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            content: "Hey there",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-3",
          },
          {
            content: shared3,
            additional_kwargs: {},
            response_metadata: {},
            type: "system",
            name: null,
            id: "id-5",
          },
          {
            content: "Hello! How can I assist you today?",
            additional_kwargs: {},
            response_metadata: {
              finish_reason: "stop",
              model_name: "gpt-4.1-mini",
              model_provider: "openai",
            },
            type: "ai",
            name: null,
            id: "id-4",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          {
            content: "My favorite fruit is Mango",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-7",
          },
          {
            content: shared5,
            additional_kwargs: {},
            response_metadata: {
              finish_reason: "stop",
              model_name: "gpt-4.1-mini",
              model_provider: "openai",
            },
            type: "ai",
            name: null,
            id: "id-8",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          {
            content: "and I love listening to Kaavish",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-10",
          },
          {
            content: shared4,
            additional_kwargs: {},
            response_metadata: {
              finish_reason: "stop",
              model_name: "gpt-4.1-mini",
              model_provider: "openai",
            },
            type: "ai",
            name: null,
            id: "id-11",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          {
            content: "tell me an interesting fact about Moon",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-13",
          },
        ],
        copilotkit: {
          actions: [
            {
              name: "change_background",
              description: shared2,
              parameters: {
                type: "object",
                properties: {
                  background: {
                    type: "string",
                    description:
                      "The background. Prefer gradients. Only use when asked.",
                  },
                },
                required: ["background"],
              },
            },
          ],
          context: [
            {
              description: "Name of the user",
              value: "Bob",
            },
          ],
        },
        tools: [
          {
            name: "change_background",
            description: shared2,
            parameters: {
              type: "object",
              properties: {
                background: {
                  type: "string",
                  description:
                    "The background. Prefer gradients. Only use when asked.",
                },
              },
              required: ["background"],
            },
          },
        ],
      },
    },
    {
      type: "STEP_FINISHED",
      stepName: "CopilotKitMiddleware.before_agent",
    },
    {
      type: "STEP_STARTED",
      stepName: "model",
    },
    {
      type: "TEXT_MESSAGE_START",
      messageId: "id-14",
      role: "assistant",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-14",
      delta: "The Moon is Earth's ",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-14",
      delta: "only natural satelli",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-14",
      delta: "te, orbiting at an a",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-14",
      delta: "verage distance of a",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-14",
      delta: "bout 384,400 km. It ",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-14",
      delta: "takes approximately ",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-14",
      delta: "27.3 days to complet",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-14",
      delta: "e one orbit.",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-14",
    },
    {
      type: "STEP_FINISHED",
      stepName: "model",
    },
    {
      type: "STEP_STARTED",
      stepName: "CopilotKitMiddleware.after_model",
    },
    {
      type: "STEP_FINISHED",
      stepName: "CopilotKitMiddleware.after_model",
    },
    {
      type: "STEP_STARTED",
      stepName: "CopilotKitMiddleware.after_agent",
    },
    {
      type: "STEP_FINISHED",
      stepName: "CopilotKitMiddleware.after_agent",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: shared6,
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hey there",
        },
        shared20,
        {
          id: "id-4",
          role: "assistant",
          content: "Hello! How can I assist you today?",
        },
        {
          id: "id-7",
          role: "user",
          content: "My favorite fruit is Mango",
        },
        shared22,
        {
          id: "id-10",
          role: "user",
          content: "and I love listening to Kaavish",
        },
        shared19,
        {
          id: "id-13",
          role: "user",
          content: "tell me an interesting fact about Moon",
        },
        shared14,
      ],
    },
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-12",
    },
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-15",
      input: {
        threadId: "id-1",
        runId: "id-15",
        protocolVersion: "1.0",
        state: shared6,
        messages: [shared26],
        tools: [
          {
            name: "change_background",
            description: shared2,
            parameters: {
              type: "object",
              properties: {
                background: {
                  type: "string",
                  description:
                    "The background. Prefer gradients. Only use when asked.",
                },
              },
              required: ["background"],
            },
          },
        ],
        context: [
          {
            description: "Name of the user",
            value: "Bob",
          },
        ],
        forwardedProps: {},
      },
    },
    {
      type: "STEP_STARTED",
      stepName: "CopilotKitMiddleware.before_agent",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            content: "Hey there",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-3",
          },
          {
            content: shared3,
            additional_kwargs: {},
            response_metadata: {},
            type: "system",
            name: null,
            id: "id-5",
          },
          {
            content: "Hello! How can I assist you today?",
            additional_kwargs: {},
            response_metadata: {
              finish_reason: "stop",
              model_name: "gpt-4.1-mini",
              model_provider: "openai",
            },
            type: "ai",
            name: null,
            id: "id-4",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          {
            content: "My favorite fruit is Mango",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-7",
          },
          {
            content: shared5,
            additional_kwargs: {},
            response_metadata: {
              finish_reason: "stop",
              model_name: "gpt-4.1-mini",
              model_provider: "openai",
            },
            type: "ai",
            name: null,
            id: "id-8",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          {
            content: "and I love listening to Kaavish",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-10",
          },
          {
            content: shared4,
            additional_kwargs: {},
            response_metadata: {
              finish_reason: "stop",
              model_name: "gpt-4.1-mini",
              model_provider: "openai",
            },
            type: "ai",
            name: null,
            id: "id-11",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          {
            content: "tell me an interesting fact about Moon",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-13",
          },
          {
            content: shared1,
            additional_kwargs: {},
            response_metadata: {
              finish_reason: "stop",
              model_name: "gpt-4.1-mini",
              model_provider: "openai",
            },
            type: "ai",
            name: null,
            id: "id-14",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          shared18,
        ],
        copilotkit: {
          actions: [
            {
              name: "change_background",
              description: shared2,
              parameters: {
                type: "object",
                properties: {
                  background: {
                    type: "string",
                    description:
                      "The background. Prefer gradients. Only use when asked.",
                  },
                },
                required: ["background"],
              },
            },
          ],
          context: [
            {
              description: "Name of the user",
              value: "Bob",
            },
          ],
        },
        tools: [
          {
            name: "change_background",
            description: shared2,
            parameters: {
              type: "object",
              properties: {
                background: {
                  type: "string",
                  description:
                    "The background. Prefer gradients. Only use when asked.",
                },
              },
              required: ["background"],
            },
          },
        ],
      },
    },
    {
      type: "STEP_FINISHED",
      stepName: "CopilotKitMiddleware.before_agent",
    },
    {
      type: "STEP_STARTED",
      stepName: "model",
    },
    {
      type: "TEXT_MESSAGE_START",
      messageId: "id-17",
      role: "assistant",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-17",
      delta: "Your favorite fruit ",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-17",
      delta: "is Mango!",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-17",
    },
    {
      type: "STEP_FINISHED",
      stepName: "model",
    },
    {
      type: "STEP_STARTED",
      stepName: "CopilotKitMiddleware.after_model",
    },
    {
      type: "STEP_FINISHED",
      stepName: "CopilotKitMiddleware.after_model",
    },
    {
      type: "STEP_STARTED",
      stepName: "CopilotKitMiddleware.after_agent",
    },
    {
      type: "STEP_FINISHED",
      stepName: "CopilotKitMiddleware.after_agent",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            content: "Hey there",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-3",
          },
          {
            content: shared3,
            additional_kwargs: {},
            response_metadata: {},
            type: "system",
            name: null,
            id: "id-5",
          },
          {
            content: "Hello! How can I assist you today?",
            additional_kwargs: {},
            response_metadata: {
              finish_reason: "stop",
              model_name: "gpt-4.1-mini",
              model_provider: "openai",
            },
            type: "ai",
            name: null,
            id: "id-4",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          {
            content: "My favorite fruit is Mango",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-7",
          },
          {
            content: shared5,
            additional_kwargs: {},
            response_metadata: {
              finish_reason: "stop",
              model_name: "gpt-4.1-mini",
              model_provider: "openai",
            },
            type: "ai",
            name: null,
            id: "id-8",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          {
            content: "and I love listening to Kaavish",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-10",
          },
          {
            content: shared4,
            additional_kwargs: {},
            response_metadata: {
              finish_reason: "stop",
              model_name: "gpt-4.1-mini",
              model_provider: "openai",
            },
            type: "ai",
            name: null,
            id: "id-11",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          {
            content: "tell me an interesting fact about Moon",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-13",
          },
          {
            content: shared1,
            additional_kwargs: {},
            response_metadata: {
              finish_reason: "stop",
              model_name: "gpt-4.1-mini",
              model_provider: "openai",
            },
            type: "ai",
            name: null,
            id: "id-14",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          shared18,
          {
            content: "Your favorite fruit is Mango!",
            additional_kwargs: {},
            response_metadata: {
              finish_reason: "stop",
              model_name: "gpt-4.1-mini",
              model_provider: "openai",
            },
            type: "ai",
            name: null,
            id: "id-17",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
        ],
        copilotkit: {
          actions: [
            {
              name: "change_background",
              description: shared2,
              parameters: {
                type: "object",
                properties: {
                  background: {
                    type: "string",
                    description:
                      "The background. Prefer gradients. Only use when asked.",
                  },
                },
                required: ["background"],
              },
            },
          ],
          context: [
            {
              description: "Name of the user",
              value: "Bob",
            },
          ],
        },
      },
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hey there",
        },
        shared20,
        {
          id: "id-4",
          role: "assistant",
          content: "Hello! How can I assist you today?",
        },
        {
          id: "id-7",
          role: "user",
          content: "My favorite fruit is Mango",
        },
        shared22,
        {
          id: "id-10",
          role: "user",
          content: "and I love listening to Kaavish",
        },
        shared19,
        {
          id: "id-13",
          role: "user",
          content: "tell me an interesting fact about Moon",
        },
        shared14,
        shared26,
        {
          id: "id-17",
          role: "assistant",
          content: "Your favorite fruit is Mango!",
        },
      ],
    },
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-15",
    },
  ],
  agenticChatSendsAndReceivesAMessage: [
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-2",
      input: {
        threadId: "id-1",
        runId: "id-2",
        protocolVersion: "1.0",
        state: {},
        messages: [
          {
            id: "id-3",
            role: "user",
            content: "Hi, I am duaa",
          },
        ],
        tools: [
          {
            name: "change_background",
            description: shared2,
            parameters: {
              type: "object",
              properties: {
                background: {
                  type: "string",
                  description:
                    "The background. Prefer gradients. Only use when asked.",
                },
              },
              required: ["background"],
            },
          },
        ],
        context: [
          {
            description: "Name of the user",
            value: "Bob",
          },
        ],
        forwardedProps: {},
      },
    },
    {
      type: "STEP_STARTED",
      stepName: "CopilotKitMiddleware.before_agent",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [shared15, shared25],
        tools: [
          {
            name: "change_background",
            description: shared2,
            parameters: {
              type: "object",
              properties: {
                background: {
                  type: "string",
                  description:
                    "The background. Prefer gradients. Only use when asked.",
                },
              },
              required: ["background"],
            },
          },
        ],
        copilotkit: {
          actions: [
            {
              name: "change_background",
              description: shared2,
              parameters: {
                type: "object",
                properties: {
                  background: {
                    type: "string",
                    description:
                      "The background. Prefer gradients. Only use when asked.",
                  },
                },
                required: ["background"],
              },
            },
          ],
          context: [
            {
              description: "Name of the user",
              value: "Bob",
            },
          ],
        },
      },
    },
    {
      type: "STEP_FINISHED",
      stepName: "CopilotKitMiddleware.before_agent",
    },
    {
      type: "STEP_STARTED",
      stepName: "model",
    },
    {
      type: "TEXT_MESSAGE_START",
      messageId: "id-4",
      role: "assistant",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: "Hello duaa! How can ",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: "I assist you today?",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-4",
    },
    {
      type: "STEP_FINISHED",
      stepName: "model",
    },
    {
      type: "STEP_STARTED",
      stepName: "CopilotKitMiddleware.after_model",
    },
    {
      type: "STEP_FINISHED",
      stepName: "CopilotKitMiddleware.after_model",
    },
    {
      type: "STEP_STARTED",
      stepName: "CopilotKitMiddleware.after_agent",
    },
    {
      type: "STEP_FINISHED",
      stepName: "CopilotKitMiddleware.after_agent",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          shared25,
          {
            content: shared3,
            additional_kwargs: {},
            response_metadata: {},
            type: "system",
            name: null,
            id: "id-5",
          },
          {
            content: "Hello duaa! How can I assist you today?",
            additional_kwargs: {},
            response_metadata: {
              finish_reason: "stop",
              model_name: "gpt-4.1-mini",
              model_provider: "openai",
            },
            type: "ai",
            name: null,
            id: "id-4",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
        ],
        copilotkit: {
          actions: [
            {
              name: "change_background",
              description: shared2,
              parameters: {
                type: "object",
                properties: {
                  background: {
                    type: "string",
                    description:
                      "The background. Prefer gradients. Only use when asked.",
                  },
                },
                required: ["background"],
              },
            },
          ],
          context: [
            {
              description: "Name of the user",
              value: "Bob",
            },
          ],
        },
      },
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hi, I am duaa",
        },
        shared20,
        {
          id: "id-4",
          role: "assistant",
          content: "Hello duaa! How can I assist you today?",
        },
      ],
    },
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-2",
    },
  ],
});
