import { defineEventTrace } from "../../event-trace-test";

// Generated by the event trace updater.
// Reason: CopilotKit 1.76 runtime (@ag-ui/client 1.0.1): RUN_STARTED.input declares protocolVersion, rawEvent no longer forwarded, duplicate trailing STATE_SNAPSHOT dropped (PNI-537)
// Before accepting changes, verify whether the implementation regressed.
const shared1 =
  '{"document": "Once upon a time, in a land far away, there lived a magnificent dragon named Atlantis. Atlantis was known throughout the realm for its shimmering scales that reflected the light of a thousand stars. The dragon Atlantis would soar above the mountains, breathing fire that lit up the night sky. Villagers would gather to watch Atlantis perform its aerial dances, marveling at the grace of this ancient creature."}' as const;
const shared2 =
  "Once upon a time, in a land far away, there lived a magnificent dragon named AtlantisLola. AtlantisLola was known throughout the realm for its shimmering scales that reflected the light of a thousand stars. The dragon AtlantisLola would soar above the mountains, breathing fire that lit up the night sky. Villagers would gather to watch AtlantisLola perform its aerial dances, marveling at the grace of this ancient creature." as const;
const shared3 =
  '{"document": "Once upon a time, in a land far away, there lived a magnificent dragon named Lola. Lola was known throughout the realm for its shimmering scales that reflected the light of a thousand stars. The dragon Lola would soar above the mountains, breathing fire that lit up the night sky. Villagers would gather to watch Lola perform its aerial dances, marveling at the grace of this ancient creature."}' as const;
const shared4 =
  "Once upon a time, in a land far away, there lived a magnificent dragon named Atlantis. Atlantis was known throughout the realm for its shimmering scales that reflected the light of a thousand stars. The dragon Atlantis would soar above the mountains, breathing fire that lit up the night sky. Villagers would gather to watch Atlantis perform its aerial dances, marveling at the grace of this ancient creature." as const;
const shared5 =
  "Once upon a time, in a land far away, there lived a magnificent dragon named Lola. Lola was known throughout the realm for its shimmering scales that reflected the light of a thousand stars. The dragon Lola would soar above the mountains, breathing fire that lit up the night sky. Villagers would gather to watch Lola perform its aerial dances, marveling at the grace of this ancient creature." as const;
const shared6 = {
  type: "STATE_SNAPSHOT",
  snapshot: {
    messages: [
      {
        content: "Give me a story for a dragon called Atlantis in document",
        additional_kwargs: {},
        response_metadata: {},
        type: "human",
        name: null,
        id: "id-3",
      },
      {
        content: "",
        additional_kwargs: {},
        response_metadata: {
          finish_reason: "tool_calls",
          model_name: "gpt-4.1-mini",
          model_provider: "openai",
        },
        type: "ai",
        name: null,
        id: "id-5",
        tool_calls: [
          {
            name: "write_document_local",
            args: {
              document: shared4,
            },
            id: "id-4",
            type: "tool_call",
          },
        ],
        invalid_tool_calls: [],
        usage_metadata: null,
      },
      {
        content: "Document written.",
        additional_kwargs: {},
        response_metadata: {},
        type: "tool",
        name: null,
        id: "id-6",
        tool_call_id: "id-4",
        artifact: null,
        status: "success",
      },
      {
        content: "",
        additional_kwargs: {},
        response_metadata: {},
        type: "ai",
        name: null,
        id: "id-7",
        tool_calls: [
          {
            name: "confirm_changes",
            args: {},
            id: "id-8",
            type: "tool_call",
          },
        ],
        invalid_tool_calls: [],
        usage_metadata: null,
      },
      {
        content: '{"accepted":true}',
        additional_kwargs: {},
        response_metadata: {},
        type: "tool",
        name: null,
        id: "id-10",
        tool_call_id: "id-8",
        artifact: null,
        status: "success",
      },
      {
        content: "Done! I've completed that for you.",
        additional_kwargs: {},
        response_metadata: {
          finish_reason: "stop",
          model_name: "gpt-4.1-mini",
          model_provider: "openai",
        },
        type: "ai",
        name: null,
        id: "id-11",
        tool_calls: [],
        invalid_tool_calls: [],
        usage_metadata: null,
      },
      {
        content: "Change dragon name to Lola",
        additional_kwargs: {},
        response_metadata: {},
        type: "human",
        name: null,
        id: "id-13",
      },
      {
        content: "",
        additional_kwargs: {},
        response_metadata: {
          finish_reason: "tool_calls",
          model_name: "gpt-4.1-mini",
          model_provider: "openai",
        },
        type: "ai",
        name: null,
        id: "id-15",
        tool_calls: [
          {
            name: "write_document_local",
            args: {
              document: shared5,
            },
            id: "id-14",
            type: "tool_call",
          },
        ],
        invalid_tool_calls: [],
        usage_metadata: null,
      },
      {
        content: "Document written.",
        additional_kwargs: {},
        response_metadata: {},
        type: "tool",
        name: null,
        id: "id-16",
        tool_call_id: "id-14",
        artifact: null,
        status: "success",
      },
      {
        content: "",
        additional_kwargs: {},
        response_metadata: {},
        type: "ai",
        name: null,
        id: "id-17",
        tool_calls: [
          {
            name: "confirm_changes",
            args: {},
            id: "id-18",
            type: "tool_call",
          },
        ],
        invalid_tool_calls: [],
        usage_metadata: null,
      },
    ],
    document: shared5,
    tools: [
      {
        name: "confirm_changes",
        description: "",
        parameters: {
          type: "object",
          properties: {},
        },
      },
      {
        name: "write_document",
        description: "Present the proposed changes to the user for review",
        parameters: {
          type: "object",
          properties: {
            document: {
              type: "string",
              description: "The full updated document in markdown format",
            },
          },
          required: ["document"],
        },
      },
    ],
  },
} as const;
const shared7 = {
  type: "RUN_STARTED",
  threadId: "id-1",
  runId: "id-12",
  input: {
    threadId: "id-1",
    runId: "id-12",
    protocolVersion: "1.0",
    state: {
      messages: [
        {
          content: "Give me a story for a dragon called Atlantis in document",
          additional_kwargs: {},
          response_metadata: {},
          type: "human",
          name: null,
          id: "id-3",
        },
        {
          content: "",
          additional_kwargs: {},
          response_metadata: {
            finish_reason: "tool_calls",
            model_name: "gpt-4.1-mini",
            model_provider: "openai",
          },
          type: "ai",
          name: null,
          id: "id-5",
          tool_calls: [
            {
              name: "write_document_local",
              args: {
                document: shared4,
              },
              id: "id-4",
              type: "tool_call",
            },
          ],
          invalid_tool_calls: [],
          usage_metadata: null,
        },
        {
          content: "Document written.",
          additional_kwargs: {},
          response_metadata: {},
          type: "tool",
          name: null,
          id: "id-6",
          tool_call_id: "id-4",
          artifact: null,
          status: "success",
        },
        {
          content: "",
          additional_kwargs: {},
          response_metadata: {},
          type: "ai",
          name: null,
          id: "id-7",
          tool_calls: [
            {
              name: "confirm_changes",
              args: {},
              id: "id-8",
              type: "tool_call",
            },
          ],
          invalid_tool_calls: [],
          usage_metadata: null,
        },
        {
          content: '{"accepted":true}',
          additional_kwargs: {},
          response_metadata: {},
          type: "tool",
          name: null,
          id: "id-10",
          tool_call_id: "id-8",
          artifact: null,
          status: "success",
        },
        {
          content: "Done! I've completed that for you.",
          additional_kwargs: {},
          response_metadata: {
            finish_reason: "stop",
            model_name: "gpt-4.1-mini",
            model_provider: "openai",
          },
          type: "ai",
          name: null,
          id: "id-11",
          tool_calls: [],
          invalid_tool_calls: [],
          usage_metadata: null,
        },
      ],
      document: shared4,
      tools: [
        {
          name: "confirm_changes",
          description: "",
          parameters: {
            type: "object",
            properties: {},
          },
        },
        {
          name: "write_document",
          description: "Present the proposed changes to the user for review",
          parameters: {
            type: "object",
            properties: {
              document: {
                type: "string",
                description: "The full updated document in markdown format",
              },
            },
            required: ["document"],
          },
        },
      ],
    },
    messages: [
      {
        id: "id-13",
        role: "user",
        content: "Change dragon name to Lola",
      },
    ],
    tools: [
      {
        name: "confirm_changes",
        description: "",
        parameters: {
          type: "object",
          properties: {},
        },
      },
      {
        name: "write_document",
        description: "Present the proposed changes to the user for review",
        parameters: {
          type: "object",
          properties: {
            document: {
              type: "string",
              description: "The full updated document in markdown format",
            },
          },
          required: ["document"],
        },
      },
    ],
    context: [],
    forwardedProps: {},
  },
} as const;
const shared8 = {
  type: "STATE_SNAPSHOT",
  snapshot: {
    messages: [
      {
        content: "Give me a story for a dragon called Atlantis in document",
        additional_kwargs: {},
        response_metadata: {},
        type: "human",
        name: null,
        id: "id-3",
      },
      {
        content: "",
        additional_kwargs: {},
        response_metadata: {
          finish_reason: "tool_calls",
          model_name: "gpt-4.1-mini",
          model_provider: "openai",
        },
        type: "ai",
        name: null,
        id: "id-5",
        tool_calls: [
          {
            name: "write_document_local",
            args: {
              document: shared4,
            },
            id: "id-4",
            type: "tool_call",
          },
        ],
        invalid_tool_calls: [],
        usage_metadata: null,
      },
      {
        content: "Document written.",
        additional_kwargs: {},
        response_metadata: {},
        type: "tool",
        name: null,
        id: "id-6",
        tool_call_id: "id-4",
        artifact: null,
        status: "success",
      },
      {
        content: "",
        additional_kwargs: {},
        response_metadata: {},
        type: "ai",
        name: null,
        id: "id-7",
        tool_calls: [
          {
            name: "confirm_changes",
            args: {},
            id: "id-8",
            type: "tool_call",
          },
        ],
        invalid_tool_calls: [],
        usage_metadata: null,
      },
      {
        content: '{"accepted":true}',
        additional_kwargs: {},
        response_metadata: {},
        type: "tool",
        name: null,
        id: "id-10",
        tool_call_id: "id-8",
        artifact: null,
        status: "success",
      },
      {
        content: "Done! I've completed that for you.",
        additional_kwargs: {},
        response_metadata: {
          finish_reason: "stop",
          model_name: "gpt-4.1-mini",
          model_provider: "openai",
        },
        type: "ai",
        name: null,
        id: "id-11",
        tool_calls: [],
        invalid_tool_calls: [],
        usage_metadata: null,
      },
    ],
    document: shared4,
    tools: [
      {
        name: "confirm_changes",
        description: "",
        parameters: {
          type: "object",
          properties: {},
        },
      },
      {
        name: "write_document",
        description: "Present the proposed changes to the user for review",
        parameters: {
          type: "object",
          properties: {
            document: {
              type: "string",
              description: "The full updated document in markdown format",
            },
          },
          required: ["document"],
        },
      },
    ],
  },
} as const;
const shared9 = {
  type: "STATE_SNAPSHOT",
  snapshot: {
    messages: [
      {
        content: "Give me a story for a dragon called Atlantis in document",
        additional_kwargs: {},
        response_metadata: {},
        type: "human",
        name: null,
        id: "id-3",
      },
      {
        content: "",
        additional_kwargs: {},
        response_metadata: {
          finish_reason: "tool_calls",
          model_name: "gpt-4.1-mini",
          model_provider: "openai",
        },
        type: "ai",
        name: null,
        id: "id-5",
        tool_calls: [
          {
            name: "write_document_local",
            args: {
              document: shared4,
            },
            id: "id-4",
            type: "tool_call",
          },
        ],
        invalid_tool_calls: [],
        usage_metadata: null,
      },
      {
        content: "Document written.",
        additional_kwargs: {},
        response_metadata: {},
        type: "tool",
        name: null,
        id: "id-6",
        tool_call_id: "id-4",
        artifact: null,
        status: "success",
      },
      {
        content: "",
        additional_kwargs: {},
        response_metadata: {},
        type: "ai",
        name: null,
        id: "id-7",
        tool_calls: [
          {
            name: "confirm_changes",
            args: {},
            id: "id-8",
            type: "tool_call",
          },
        ],
        invalid_tool_calls: [],
        usage_metadata: null,
      },
    ],
    document: shared4,
    tools: [
      {
        name: "confirm_changes",
        description: "",
        parameters: {
          type: "object",
          properties: {},
        },
      },
      {
        name: "write_document",
        description: "Present the proposed changes to the user for review",
        parameters: {
          type: "object",
          properties: {
            document: {
              type: "string",
              description: "The full updated document in markdown format",
            },
          },
          required: ["document"],
        },
      },
    ],
  },
} as const;
const shared10 = {
  type: "MESSAGES_SNAPSHOT",
  messages: [
    {
      id: "id-3",
      role: "user",
      content: "Give me a story for a dragon called Atlantis in document",
    },
    {
      id: "id-5",
      role: "assistant",
      content: "",
      toolCalls: [
        {
          id: "id-4",
          type: "function",
          function: {
            name: "write_document_local",
            arguments: shared1,
          },
        },
      ],
    },
    {
      id: "id-6",
      role: "tool",
      content: "Document written.",
      toolCallId: "id-4",
    },
    {
      id: "id-7",
      role: "assistant",
      content: "",
      toolCalls: [
        {
          id: "id-8",
          type: "function",
          function: {
            name: "confirm_changes",
            arguments: "{}",
          },
        },
      ],
    },
    {
      id: "id-10",
      role: "tool",
      content: '{"accepted":true}',
      toolCallId: "id-8",
    },
    {
      id: "id-11",
      role: "assistant",
      content: "Done! I've completed that for you.",
    },
    {
      id: "id-13",
      role: "user",
      content: "Change dragon name to Lola",
    },
    {
      id: "id-15",
      role: "assistant",
      content: "",
      toolCalls: [
        {
          id: "id-14",
          type: "function",
          function: {
            name: "write_document_local",
            arguments: shared3,
          },
        },
      ],
    },
    {
      id: "id-16",
      role: "tool",
      content: "Document written.",
      toolCallId: "id-14",
    },
    {
      id: "id-17",
      role: "assistant",
      content: "",
      toolCalls: [
        {
          id: "id-18",
          type: "function",
          function: {
            name: "confirm_changes",
            arguments: "{}",
          },
        },
      ],
    },
  ],
} as const;
const shared11 = {
  type: "RUN_STARTED",
  threadId: "id-1",
  runId: "id-9",
  input: {
    threadId: "id-1",
    runId: "id-9",
    protocolVersion: "1.0",
    state: {
      document: shared4,
    },
    messages: [
      {
        id: "id-5",
        role: "assistant",
        content: "",
        toolCalls: [
          {
            id: "id-4",
            type: "function",
            function: {
              name: "write_document_local",
              arguments: shared1,
            },
          },
        ],
      },
      {
        id: "id-6",
        role: "tool",
        content: "Document written.",
        toolCallId: "id-4",
      },
      {
        id: "id-7",
        role: "assistant",
        content: "",
        toolCalls: [
          {
            id: "id-8",
            type: "function",
            function: {
              name: "confirm_changes",
              arguments: "{}",
            },
          },
        ],
      },
      {
        id: "id-10",
        role: "tool",
        content: '{"accepted":true}',
        toolCallId: "id-8",
      },
    ],
    tools: [
      {
        name: "confirm_changes",
        description: "",
        parameters: {
          type: "object",
          properties: {},
        },
      },
      {
        name: "write_document",
        description: "Present the proposed changes to the user for review",
        parameters: {
          type: "object",
          properties: {
            document: {
              type: "string",
              description: "The full updated document in markdown format",
            },
          },
          required: ["document"],
        },
      },
    ],
    context: [],
    forwardedProps: {},
  },
} as const;
const shared12 = {
  type: "MESSAGES_SNAPSHOT",
  messages: [
    {
      id: "id-3",
      role: "user",
      content: "Give me a story for a dragon called Atlantis in document",
    },
    {
      id: "id-5",
      role: "assistant",
      content: "",
      toolCalls: [
        {
          id: "id-4",
          type: "function",
          function: {
            name: "write_document_local",
            arguments: shared1,
          },
        },
      ],
    },
    {
      id: "id-6",
      role: "tool",
      content: "Document written.",
      toolCallId: "id-4",
    },
    {
      id: "id-7",
      role: "assistant",
      content: "",
      toolCalls: [
        {
          id: "id-8",
          type: "function",
          function: {
            name: "confirm_changes",
            arguments: "{}",
          },
        },
      ],
    },
    {
      id: "id-10",
      role: "tool",
      content: '{"accepted":true}',
      toolCallId: "id-8",
    },
    {
      id: "id-11",
      role: "assistant",
      content: "Done! I've completed that for you.",
    },
  ],
} as const;
const shared13 = {
  type: "MESSAGES_SNAPSHOT",
  messages: [
    {
      id: "id-3",
      role: "user",
      content: "Give me a story for a dragon called Atlantis in document",
    },
    {
      id: "id-5",
      role: "assistant",
      content: "",
      toolCalls: [
        {
          id: "id-4",
          type: "function",
          function: {
            name: "write_document_local",
            arguments: shared1,
          },
        },
      ],
    },
    {
      id: "id-6",
      role: "tool",
      content: "Document written.",
      toolCallId: "id-4",
    },
    {
      id: "id-7",
      role: "assistant",
      content: "",
      toolCalls: [
        {
          id: "id-8",
          type: "function",
          function: {
            name: "confirm_changes",
            arguments: "{}",
          },
        },
      ],
    },
  ],
} as const;
const shared14 = {
  type: "RUN_STARTED",
  threadId: "id-1",
  runId: "id-2",
  input: {
    threadId: "id-1",
    runId: "id-2",
    protocolVersion: "1.0",
    state: {},
    messages: [
      {
        id: "id-3",
        role: "user",
        content: "Give me a story for a dragon called Atlantis in document",
      },
    ],
    tools: [
      {
        name: "confirm_changes",
        description: "",
        parameters: {
          type: "object",
          properties: {},
        },
      },
      {
        name: "write_document",
        description: "Present the proposed changes to the user for review",
        parameters: {
          type: "object",
          properties: {
            document: {
              type: "string",
              description: "The full updated document in markdown format",
            },
          },
          required: ["document"],
        },
      },
    ],
    context: [],
    forwardedProps: {},
  },
} as const;
const shared15 = {
  document: shared2,
} as const;
const shared16 = {
  content: "Done! I've completed that for you.",
  additional_kwargs: {},
  response_metadata: {
    finish_reason: "stop",
    model_name: "gpt-4.1-mini",
    model_provider: "openai",
  },
  type: "ai",
  name: null,
  id: "id-21",
  tool_calls: [],
  invalid_tool_calls: [],
  usage_metadata: null,
} as const;
const shared17 = {
  type: "CUSTOM",
  name: "PredictState",
  value: [
    {
      state_key: "document",
      tool: "write_document_local",
      tool_argument: "document",
    },
  ],
} as const;
const shared18 = {
  type: "TOOL_CALL_START",
  toolCallId: "id-14",
  toolCallName: "write_document_local",
  parentMessageId: "id-15",
} as const;
const shared19 = {
  type: "TOOL_CALL_START",
  toolCallId: "id-4",
  toolCallName: "write_document_local",
  parentMessageId: "id-5",
} as const;
const shared20 = {
  id: "id-20",
  role: "tool",
  content: '{"accepted":false}',
  toolCallId: "id-18",
} as const;
const shared21 = {
  type: "TEXT_MESSAGE_CONTENT",
  messageId: "id-11",
  delta: "Done! I've completed",
} as const;
const shared22 = {
  type: "TEXT_MESSAGE_CONTENT",
  messageId: "id-21",
  delta: "Done! I've completed",
} as const;
const shared23 = {
  id: "id-20",
  role: "tool",
  content: '{"accepted":true}',
  toolCallId: "id-18",
} as const;

export const predictiveStateUpdatePageEventTrace = defineEventTrace(
  import.meta.url,
  {
    interactWithAgentAndApproveAskedChanges: [
      shared14,
      {
        type: "STEP_STARTED",
        stepName: "start_node",
      },
      {
        type: "STEP_FINISHED",
        stepName: "start_node",
      },
      {
        type: "STEP_STARTED",
        stepName: "chat_node",
      },
      shared17,
      shared19,
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: '{"document":"Once up',
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "on a time, in a land",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: " far away, there liv",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "ed a magnificent dra",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "gon named Atlantis. ",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "Atlantis was known t",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "hroughout the realm ",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "for its shimmering s",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "cales that reflected",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: " the light of a thou",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "sand stars. The drag",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "on Atlantis would so",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "ar above the mountai",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "ns, breathing fire t",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "hat lit up the night",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: " sky. Villagers woul",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "d gather to watch At",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "lantis perform its a",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "erial dances, marvel",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "ing at the grace of ",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "this ancient creatur",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: 'e."}',
      },
      {
        type: "TOOL_CALL_END",
        toolCallId: "id-4",
      },
      {
        type: "STEP_FINISHED",
        stepName: "chat_node",
      },
      shared9,
      shared13,
      {
        type: "RUN_FINISHED",
        threadId: "id-1",
        runId: "id-2",
      },
      shared11,
      {
        type: "STEP_STARTED",
        stepName: "start_node",
      },
      {
        type: "STEP_FINISHED",
        stepName: "start_node",
      },
      {
        type: "STEP_STARTED",
        stepName: "chat_node",
      },
      {
        type: "TEXT_MESSAGE_START",
        messageId: "id-11",
        role: "assistant",
      },
      shared21,
      {
        type: "TEXT_MESSAGE_CONTENT",
        messageId: "id-11",
        delta: " that for you.",
      },
      {
        type: "TEXT_MESSAGE_END",
        messageId: "id-11",
      },
      {
        type: "STEP_FINISHED",
        stepName: "chat_node",
      },
      shared8,
      shared12,
      {
        type: "RUN_FINISHED",
        threadId: "id-1",
        runId: "id-9",
      },
      shared7,
      {
        type: "STEP_STARTED",
        stepName: "start_node",
      },
      {
        type: "STEP_FINISHED",
        stepName: "start_node",
      },
      {
        type: "STEP_STARTED",
        stepName: "chat_node",
      },
      shared17,
      shared18,
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: '{"document":"Once up',
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: "on a time, in a land",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: " far away, there liv",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: "ed a magnificent dra",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: "gon named Lola. Lola",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: " was known throughou",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: "t the realm for its ",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: "shimmering scales th",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: "at reflected the lig",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: "ht of a thousand sta",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: "rs. The dragon Lola ",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: "would soar above the",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: " mountains, breathin",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: "g fire that lit up t",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: "he night sky. Villag",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: "ers would gather to ",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: "watch Lola perform i",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: "ts aerial dances, ma",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: "rveling at the grace",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: " of this ancient cre",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: 'ature."}',
      },
      {
        type: "TOOL_CALL_END",
        toolCallId: "id-14",
      },
      {
        type: "STEP_FINISHED",
        stepName: "chat_node",
      },
      shared6,
      shared10,
      {
        type: "RUN_FINISHED",
        threadId: "id-1",
        runId: "id-12",
      },
      {
        type: "RUN_STARTED",
        threadId: "id-1",
        runId: "id-19",
        input: {
          threadId: "id-1",
          runId: "id-19",
          protocolVersion: "1.0",
          state: shared15,
          messages: [
            {
              id: "id-15",
              role: "assistant",
              content: "",
              toolCalls: [
                {
                  id: "id-14",
                  type: "function",
                  function: {
                    name: "write_document_local",
                    arguments: shared3,
                  },
                },
              ],
            },
            {
              id: "id-16",
              role: "tool",
              content: "Document written.",
              toolCallId: "id-14",
            },
            {
              id: "id-17",
              role: "assistant",
              content: "",
              toolCalls: [
                {
                  id: "id-18",
                  type: "function",
                  function: {
                    name: "confirm_changes",
                    arguments: "{}",
                  },
                },
              ],
            },
            shared23,
          ],
          tools: [
            {
              name: "confirm_changes",
              description: "",
              parameters: {
                type: "object",
                properties: {},
              },
            },
            {
              name: "write_document",
              description:
                "Present the proposed changes to the user for review",
              parameters: {
                type: "object",
                properties: {
                  document: {
                    type: "string",
                    description: "The full updated document in markdown format",
                  },
                },
                required: ["document"],
              },
            },
          ],
          context: [],
          forwardedProps: {},
        },
      },
      {
        type: "STEP_STARTED",
        stepName: "start_node",
      },
      {
        type: "STEP_FINISHED",
        stepName: "start_node",
      },
      {
        type: "STEP_STARTED",
        stepName: "chat_node",
      },
      {
        type: "TEXT_MESSAGE_START",
        messageId: "id-21",
        role: "assistant",
      },
      shared22,
      {
        type: "TEXT_MESSAGE_CONTENT",
        messageId: "id-21",
        delta: " that for you.",
      },
      {
        type: "TEXT_MESSAGE_END",
        messageId: "id-21",
      },
      {
        type: "STEP_FINISHED",
        stepName: "chat_node",
      },
      {
        type: "STATE_SNAPSHOT",
        snapshot: {
          messages: [
            {
              content:
                "Give me a story for a dragon called Atlantis in document",
              additional_kwargs: {},
              response_metadata: {},
              type: "human",
              name: null,
              id: "id-3",
            },
            {
              content: "",
              additional_kwargs: {},
              response_metadata: {
                finish_reason: "tool_calls",
                model_name: "gpt-4.1-mini",
                model_provider: "openai",
              },
              type: "ai",
              name: null,
              id: "id-5",
              tool_calls: [
                {
                  name: "write_document_local",
                  args: {
                    document: shared4,
                  },
                  id: "id-4",
                  type: "tool_call",
                },
              ],
              invalid_tool_calls: [],
              usage_metadata: null,
            },
            {
              content: "Document written.",
              additional_kwargs: {},
              response_metadata: {},
              type: "tool",
              name: null,
              id: "id-6",
              tool_call_id: "id-4",
              artifact: null,
              status: "success",
            },
            {
              content: "",
              additional_kwargs: {},
              response_metadata: {},
              type: "ai",
              name: null,
              id: "id-7",
              tool_calls: [
                {
                  name: "confirm_changes",
                  args: {},
                  id: "id-8",
                  type: "tool_call",
                },
              ],
              invalid_tool_calls: [],
              usage_metadata: null,
            },
            {
              content: '{"accepted":true}',
              additional_kwargs: {},
              response_metadata: {},
              type: "tool",
              name: null,
              id: "id-10",
              tool_call_id: "id-8",
              artifact: null,
              status: "success",
            },
            {
              content: "Done! I've completed that for you.",
              additional_kwargs: {},
              response_metadata: {
                finish_reason: "stop",
                model_name: "gpt-4.1-mini",
                model_provider: "openai",
              },
              type: "ai",
              name: null,
              id: "id-11",
              tool_calls: [],
              invalid_tool_calls: [],
              usage_metadata: null,
            },
            {
              content: "Change dragon name to Lola",
              additional_kwargs: {},
              response_metadata: {},
              type: "human",
              name: null,
              id: "id-13",
            },
            {
              content: "",
              additional_kwargs: {},
              response_metadata: {
                finish_reason: "tool_calls",
                model_name: "gpt-4.1-mini",
                model_provider: "openai",
              },
              type: "ai",
              name: null,
              id: "id-15",
              tool_calls: [
                {
                  name: "write_document_local",
                  args: {
                    document: shared5,
                  },
                  id: "id-14",
                  type: "tool_call",
                },
              ],
              invalid_tool_calls: [],
              usage_metadata: null,
            },
            {
              content: "Document written.",
              additional_kwargs: {},
              response_metadata: {},
              type: "tool",
              name: null,
              id: "id-16",
              tool_call_id: "id-14",
              artifact: null,
              status: "success",
            },
            {
              content: "",
              additional_kwargs: {},
              response_metadata: {},
              type: "ai",
              name: null,
              id: "id-17",
              tool_calls: [
                {
                  name: "confirm_changes",
                  args: {},
                  id: "id-18",
                  type: "tool_call",
                },
              ],
              invalid_tool_calls: [],
              usage_metadata: null,
            },
            {
              content: '{"accepted":true}',
              additional_kwargs: {},
              response_metadata: {},
              type: "tool",
              name: null,
              id: "id-20",
              tool_call_id: "id-18",
              artifact: null,
              status: "success",
            },
            shared16,
          ],
          document: shared2,
          tools: [
            {
              name: "confirm_changes",
              description: "",
              parameters: {
                type: "object",
                properties: {},
              },
            },
            {
              name: "write_document",
              description:
                "Present the proposed changes to the user for review",
              parameters: {
                type: "object",
                properties: {
                  document: {
                    type: "string",
                    description: "The full updated document in markdown format",
                  },
                },
                required: ["document"],
              },
            },
          ],
        },
      },
      {
        type: "MESSAGES_SNAPSHOT",
        messages: [
          {
            id: "id-3",
            role: "user",
            content: "Give me a story for a dragon called Atlantis in document",
          },
          {
            id: "id-5",
            role: "assistant",
            content: "",
            toolCalls: [
              {
                id: "id-4",
                type: "function",
                function: {
                  name: "write_document_local",
                  arguments: shared1,
                },
              },
            ],
          },
          {
            id: "id-6",
            role: "tool",
            content: "Document written.",
            toolCallId: "id-4",
          },
          {
            id: "id-7",
            role: "assistant",
            content: "",
            toolCalls: [
              {
                id: "id-8",
                type: "function",
                function: {
                  name: "confirm_changes",
                  arguments: "{}",
                },
              },
            ],
          },
          {
            id: "id-10",
            role: "tool",
            content: '{"accepted":true}',
            toolCallId: "id-8",
          },
          {
            id: "id-11",
            role: "assistant",
            content: "Done! I've completed that for you.",
          },
          {
            id: "id-13",
            role: "user",
            content: "Change dragon name to Lola",
          },
          {
            id: "id-15",
            role: "assistant",
            content: "",
            toolCalls: [
              {
                id: "id-14",
                type: "function",
                function: {
                  name: "write_document_local",
                  arguments: shared3,
                },
              },
            ],
          },
          {
            id: "id-16",
            role: "tool",
            content: "Document written.",
            toolCallId: "id-14",
          },
          {
            id: "id-17",
            role: "assistant",
            content: "",
            toolCalls: [
              {
                id: "id-18",
                type: "function",
                function: {
                  name: "confirm_changes",
                  arguments: "{}",
                },
              },
            ],
          },
          shared23,
          {
            id: "id-21",
            role: "assistant",
            content: "Done! I've completed that for you.",
          },
        ],
      },
      {
        type: "RUN_FINISHED",
        threadId: "id-1",
        runId: "id-19",
      },
    ],
    interactWithAgentAndRejectAskedChanges: [
      shared14,
      {
        type: "STEP_STARTED",
        stepName: "start_node",
      },
      {
        type: "STEP_FINISHED",
        stepName: "start_node",
      },
      {
        type: "STEP_STARTED",
        stepName: "chat_node",
      },
      shared17,
      shared19,
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: '{"document":"Once up',
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "on a time, in a land",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: " far away, there liv",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "ed a magnificent dra",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "gon named Atlantis. ",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "Atlantis was known t",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "hroughout the realm ",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "for its shimmering s",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "cales that reflected",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: " the light of a thou",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "sand stars. The drag",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "on Atlantis would so",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "ar above the mountai",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "ns, breathing fire t",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "hat lit up the night",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: " sky. Villagers woul",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "d gather to watch At",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "lantis perform its a",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "erial dances, marvel",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "ing at the grace of ",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "this ancient creatur",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: 'e."}',
      },
      {
        type: "TOOL_CALL_END",
        toolCallId: "id-4",
      },
      {
        type: "STEP_FINISHED",
        stepName: "chat_node",
      },
      shared9,
      shared13,
      {
        type: "RUN_FINISHED",
        threadId: "id-1",
        runId: "id-2",
      },
      shared11,
      {
        type: "STEP_STARTED",
        stepName: "start_node",
      },
      {
        type: "STEP_FINISHED",
        stepName: "start_node",
      },
      {
        type: "STEP_STARTED",
        stepName: "chat_node",
      },
      {
        type: "TEXT_MESSAGE_START",
        messageId: "id-11",
        role: "assistant",
      },
      shared21,
      {
        type: "TEXT_MESSAGE_CONTENT",
        messageId: "id-11",
        delta: " that for you.",
      },
      {
        type: "TEXT_MESSAGE_END",
        messageId: "id-11",
      },
      {
        type: "STEP_FINISHED",
        stepName: "chat_node",
      },
      shared8,
      shared12,
      {
        type: "RUN_FINISHED",
        threadId: "id-1",
        runId: "id-9",
      },
      shared7,
      {
        type: "STEP_STARTED",
        stepName: "start_node",
      },
      {
        type: "STEP_FINISHED",
        stepName: "start_node",
      },
      {
        type: "STEP_STARTED",
        stepName: "chat_node",
      },
      shared17,
      shared18,
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: '{"document":"Once up',
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: "on a time, in a land",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: " far away, there liv",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: "ed a magnificent dra",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: "gon named Lola. Lola",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: " was known throughou",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: "t the realm for its ",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: "shimmering scales th",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: "at reflected the lig",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: "ht of a thousand sta",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: "rs. The dragon Lola ",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: "would soar above the",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: " mountains, breathin",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: "g fire that lit up t",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: "he night sky. Villag",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: "ers would gather to ",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: "watch Lola perform i",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: "ts aerial dances, ma",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: "rveling at the grace",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: " of this ancient cre",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-14",
        delta: 'ature."}',
      },
      {
        type: "TOOL_CALL_END",
        toolCallId: "id-14",
      },
      {
        type: "STEP_FINISHED",
        stepName: "chat_node",
      },
      shared6,
      shared10,
      {
        type: "RUN_FINISHED",
        threadId: "id-1",
        runId: "id-12",
      },
      {
        type: "RUN_STARTED",
        threadId: "id-1",
        runId: "id-19",
        input: {
          threadId: "id-1",
          runId: "id-19",
          protocolVersion: "1.0",
          state: shared15,
          messages: [
            {
              id: "id-15",
              role: "assistant",
              content: "",
              toolCalls: [
                {
                  id: "id-14",
                  type: "function",
                  function: {
                    name: "write_document_local",
                    arguments: shared3,
                  },
                },
              ],
            },
            {
              id: "id-16",
              role: "tool",
              content: "Document written.",
              toolCallId: "id-14",
            },
            {
              id: "id-17",
              role: "assistant",
              content: "",
              toolCalls: [
                {
                  id: "id-18",
                  type: "function",
                  function: {
                    name: "confirm_changes",
                    arguments: "{}",
                  },
                },
              ],
            },
            shared20,
          ],
          tools: [
            {
              name: "confirm_changes",
              description: "",
              parameters: {
                type: "object",
                properties: {},
              },
            },
            {
              name: "write_document",
              description:
                "Present the proposed changes to the user for review",
              parameters: {
                type: "object",
                properties: {
                  document: {
                    type: "string",
                    description: "The full updated document in markdown format",
                  },
                },
                required: ["document"],
              },
            },
          ],
          context: [],
          forwardedProps: {},
        },
      },
      {
        type: "STEP_STARTED",
        stepName: "start_node",
      },
      {
        type: "STEP_FINISHED",
        stepName: "start_node",
      },
      {
        type: "STEP_STARTED",
        stepName: "chat_node",
      },
      {
        type: "TEXT_MESSAGE_START",
        messageId: "id-21",
        role: "assistant",
      },
      shared22,
      {
        type: "TEXT_MESSAGE_CONTENT",
        messageId: "id-21",
        delta: " that for you.",
      },
      {
        type: "TEXT_MESSAGE_END",
        messageId: "id-21",
      },
      {
        type: "STEP_FINISHED",
        stepName: "chat_node",
      },
      {
        type: "STATE_SNAPSHOT",
        snapshot: {
          messages: [
            {
              content:
                "Give me a story for a dragon called Atlantis in document",
              additional_kwargs: {},
              response_metadata: {},
              type: "human",
              name: null,
              id: "id-3",
            },
            {
              content: "",
              additional_kwargs: {},
              response_metadata: {
                finish_reason: "tool_calls",
                model_name: "gpt-4.1-mini",
                model_provider: "openai",
              },
              type: "ai",
              name: null,
              id: "id-5",
              tool_calls: [
                {
                  name: "write_document_local",
                  args: {
                    document: shared4,
                  },
                  id: "id-4",
                  type: "tool_call",
                },
              ],
              invalid_tool_calls: [],
              usage_metadata: null,
            },
            {
              content: "Document written.",
              additional_kwargs: {},
              response_metadata: {},
              type: "tool",
              name: null,
              id: "id-6",
              tool_call_id: "id-4",
              artifact: null,
              status: "success",
            },
            {
              content: "",
              additional_kwargs: {},
              response_metadata: {},
              type: "ai",
              name: null,
              id: "id-7",
              tool_calls: [
                {
                  name: "confirm_changes",
                  args: {},
                  id: "id-8",
                  type: "tool_call",
                },
              ],
              invalid_tool_calls: [],
              usage_metadata: null,
            },
            {
              content: '{"accepted":true}',
              additional_kwargs: {},
              response_metadata: {},
              type: "tool",
              name: null,
              id: "id-10",
              tool_call_id: "id-8",
              artifact: null,
              status: "success",
            },
            {
              content: "Done! I've completed that for you.",
              additional_kwargs: {},
              response_metadata: {
                finish_reason: "stop",
                model_name: "gpt-4.1-mini",
                model_provider: "openai",
              },
              type: "ai",
              name: null,
              id: "id-11",
              tool_calls: [],
              invalid_tool_calls: [],
              usage_metadata: null,
            },
            {
              content: "Change dragon name to Lola",
              additional_kwargs: {},
              response_metadata: {},
              type: "human",
              name: null,
              id: "id-13",
            },
            {
              content: "",
              additional_kwargs: {},
              response_metadata: {
                finish_reason: "tool_calls",
                model_name: "gpt-4.1-mini",
                model_provider: "openai",
              },
              type: "ai",
              name: null,
              id: "id-15",
              tool_calls: [
                {
                  name: "write_document_local",
                  args: {
                    document: shared5,
                  },
                  id: "id-14",
                  type: "tool_call",
                },
              ],
              invalid_tool_calls: [],
              usage_metadata: null,
            },
            {
              content: "Document written.",
              additional_kwargs: {},
              response_metadata: {},
              type: "tool",
              name: null,
              id: "id-16",
              tool_call_id: "id-14",
              artifact: null,
              status: "success",
            },
            {
              content: "",
              additional_kwargs: {},
              response_metadata: {},
              type: "ai",
              name: null,
              id: "id-17",
              tool_calls: [
                {
                  name: "confirm_changes",
                  args: {},
                  id: "id-18",
                  type: "tool_call",
                },
              ],
              invalid_tool_calls: [],
              usage_metadata: null,
            },
            {
              content: '{"accepted":false}',
              additional_kwargs: {},
              response_metadata: {},
              type: "tool",
              name: null,
              id: "id-20",
              tool_call_id: "id-18",
              artifact: null,
              status: "success",
            },
            shared16,
          ],
          document: shared2,
          tools: [
            {
              name: "confirm_changes",
              description: "",
              parameters: {
                type: "object",
                properties: {},
              },
            },
            {
              name: "write_document",
              description:
                "Present the proposed changes to the user for review",
              parameters: {
                type: "object",
                properties: {
                  document: {
                    type: "string",
                    description: "The full updated document in markdown format",
                  },
                },
                required: ["document"],
              },
            },
          ],
        },
      },
      {
        type: "MESSAGES_SNAPSHOT",
        messages: [
          {
            id: "id-3",
            role: "user",
            content: "Give me a story for a dragon called Atlantis in document",
          },
          {
            id: "id-5",
            role: "assistant",
            content: "",
            toolCalls: [
              {
                id: "id-4",
                type: "function",
                function: {
                  name: "write_document_local",
                  arguments: shared1,
                },
              },
            ],
          },
          {
            id: "id-6",
            role: "tool",
            content: "Document written.",
            toolCallId: "id-4",
          },
          {
            id: "id-7",
            role: "assistant",
            content: "",
            toolCalls: [
              {
                id: "id-8",
                type: "function",
                function: {
                  name: "confirm_changes",
                  arguments: "{}",
                },
              },
            ],
          },
          {
            id: "id-10",
            role: "tool",
            content: '{"accepted":true}',
            toolCallId: "id-8",
          },
          {
            id: "id-11",
            role: "assistant",
            content: "Done! I've completed that for you.",
          },
          {
            id: "id-13",
            role: "user",
            content: "Change dragon name to Lola",
          },
          {
            id: "id-15",
            role: "assistant",
            content: "",
            toolCalls: [
              {
                id: "id-14",
                type: "function",
                function: {
                  name: "write_document_local",
                  arguments: shared3,
                },
              },
            ],
          },
          {
            id: "id-16",
            role: "tool",
            content: "Document written.",
            toolCallId: "id-14",
          },
          {
            id: "id-17",
            role: "assistant",
            content: "",
            toolCalls: [
              {
                id: "id-18",
                type: "function",
                function: {
                  name: "confirm_changes",
                  arguments: "{}",
                },
              },
            ],
          },
          shared20,
          {
            id: "id-21",
            role: "assistant",
            content: "Done! I've completed that for you.",
          },
        ],
      },
      {
        type: "RUN_FINISHED",
        threadId: "id-1",
        runId: "id-19",
      },
    ],
  },
);
