import { defineEventTrace } from "../../event-trace-test";

// Generated by the event trace updater.
// Reason: PNI-560: canonical interrupt outcomes and ID-addressed resume replace legacy interrupt events
// Before accepting changes, verify whether the implementation regressed.
const shared1 =
  "\n        Found 3 accommodation options in San Francisco.\n        I recommend choosing the Hotel Zoe since it strikes the balance between rating, price, and location.\n        " as const;
const shared2 =
  "\n        Found 2 flight options from Amsterdam to San Francisco.\n        I recommend choosing the flight by KLM since it's known to be on time and cheaper.\n        " as const;
const shared3 =
  "Flights Agent: Great. I'll book you the United flight from Amsterdam (AMS) to San Francisco (SFO)." as const;
const shared4 =
  "Flights Agent: Great. I'll book you the KLM flight from Amsterdam (AMS) to San Francisco (SFO)." as const;
const shared5 = {
  type: "RUN_FINISHED",
  threadId: "id-1",
  runId: "id-7",
  outcome: {
    type: "interrupt",
    interrupts: [
      {
        id: "id-11",
        reason: "langgraph:interrupt",
        message: shared1,
        metadata: {
          langgraph: {
            raw: {
              message: shared1,
              options: [
                {
                  name: "Hotel Zephyr",
                  location: "Fisherman's Wharf",
                  price_per_night: "$280/night",
                  rating: "4.2 stars",
                },
                {
                  name: "The Ritz-Carlton",
                  location: "Nob Hill",
                  price_per_night: "$550/night",
                  rating: "4.8 stars",
                },
                {
                  name: "Hotel Zoe",
                  location: "Union Square",
                  price_per_night: "$320/night",
                  rating: "4.4 stars",
                },
              ],
              recommendation: {
                name: "Hotel Zoe",
                location: "Union Square",
                price_per_night: "$320/night",
                rating: "4.4 stars",
              },
              agent: "hotels",
            },
            ns: null,
            resumable: null,
            when: null,
          },
        },
      },
    ],
  },
} as const;
const shared6 = {
  type: "RUN_FINISHED",
  threadId: "id-1",
  runId: "id-2",
  outcome: {
    type: "interrupt",
    interrupts: [
      {
        id: "id-6",
        reason: "langgraph:interrupt",
        message: shared2,
        metadata: {
          langgraph: {
            raw: {
              message: shared2,
              options: [
                {
                  airline: "KLM",
                  departure: "Amsterdam (AMS)",
                  arrival: "San Francisco (SFO)",
                  price: "$650",
                  duration: "11h 30m",
                },
                {
                  airline: "United",
                  departure: "Amsterdam (AMS)",
                  arrival: "San Francisco (SFO)",
                  price: "$720",
                  duration: "12h 15m",
                },
              ],
              recommendation: {
                airline: "KLM",
                departure: "Amsterdam (AMS)",
                arrival: "San Francisco (SFO)",
                price: "$650",
                duration: "11h 30m",
              },
              agent: "flights",
            },
            ns: null,
            resumable: null,
            when: null,
          },
        },
      },
    ],
  },
} as const;
const shared7 = {
  messages: [
    {
      content: "I want to visit San Francisco from Amsterdam",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
      name: null,
      id: "id-3",
    },
    {
      content: shared3,
      additional_kwargs: {},
      response_metadata: {},
      type: "ai",
      name: null,
      id: "id-8",
      tool_calls: [],
      invalid_tool_calls: [],
      usage_metadata: null,
    },
  ],
  flights: [
    {
      airline: "KLM",
      departure: "Amsterdam (AMS)",
      arrival: "San Francisco (SFO)",
      price: "$650",
      duration: "11h 30m",
    },
    {
      airline: "United",
      departure: "Amsterdam (AMS)",
      arrival: "San Francisco (SFO)",
      price: "$720",
      duration: "12h 15m",
    },
  ],
  itinerary: {
    flight: {
      airline: "United",
      departure: "Amsterdam (AMS)",
      arrival: "San Francisco (SFO)",
      price: "$720",
      duration: "12h 15m",
    },
  },
  tools: [],
} as const;
const shared8 = {
  messages: [
    {
      content: "Help me plan a trip to San Francisco",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
      name: null,
      id: "id-3",
    },
    {
      content: shared4,
      additional_kwargs: {},
      response_metadata: {},
      type: "ai",
      name: null,
      id: "id-8",
      tool_calls: [],
      invalid_tool_calls: [],
      usage_metadata: null,
    },
  ],
  flights: [
    {
      airline: "KLM",
      departure: "Amsterdam (AMS)",
      arrival: "San Francisco (SFO)",
      price: "$650",
      duration: "11h 30m",
    },
    {
      airline: "United",
      departure: "Amsterdam (AMS)",
      arrival: "San Francisco (SFO)",
      price: "$720",
      duration: "12h 15m",
    },
  ],
  itinerary: {
    flight: {
      airline: "KLM",
      departure: "Amsterdam (AMS)",
      arrival: "San Francisco (SFO)",
      price: "$650",
      duration: "11h 30m",
    },
  },
  tools: [],
} as const;
const shared9 = [
  {
    name: "Swan Oyster Depot",
    type: "restaurant",
    description: "Historic seafood counter serving fresh oysters",
    location: "Polk Street",
  },
  {
    name: "Tartine Bakery",
    type: "restaurant",
    description: "Artisanal bakery famous for bread and pastries",
    location: "Mission District",
  },
  {
    name: "Pier 39",
    type: "activity",
    description: "Iconic waterfront destination with shops and sea lions",
    location: "Fisherman's Wharf",
  },
  {
    name: "Golden Gate Bridge",
    type: "activity",
    description: "World-famous suspension bridge with stunning views",
    location: "Golden Gate",
  },
] as const;
const shared10 = {
  content:
    "I've found some wonderful experiences for your trip to San Francisco!",
  additional_kwargs: {},
  response_metadata: {
    finish_reason: "stop",
    model_name: "gpt-4.1-mini",
    model_provider: "openai",
  },
  type: "ai",
  name: null,
  id: "id-16",
  tool_calls: [],
  invalid_tool_calls: [],
  usage_metadata: null,
} as const;
const shared11 = {
  type: "MESSAGES_SNAPSHOT",
  messages: [
    {
      id: "id-3",
      role: "user",
      content: "I want to visit San Francisco from Amsterdam",
    },
    {
      id: "id-8",
      role: "assistant",
      content: shared3,
    },
  ],
} as const;
const shared12 = {
  type: "MESSAGES_SNAPSHOT",
  messages: [
    {
      id: "id-3",
      role: "user",
      content: "Help me plan a trip to San Francisco",
    },
    {
      id: "id-8",
      role: "assistant",
      content: shared4,
    },
  ],
} as const;
const shared13 = {
  flight: {
    airline: "United",
    departure: "Amsterdam (AMS)",
    arrival: "San Francisco (SFO)",
    price: "$720",
    duration: "12h 15m",
  },
  hotel: {
    name: "The Ritz-Carlton",
    location: "Nob Hill",
    price_per_night: "$550/night",
    rating: "4.8 stars",
  },
} as const;
const shared14 = {
  flight: {
    airline: "KLM",
    departure: "Amsterdam (AMS)",
    arrival: "San Francisco (SFO)",
    price: "$650",
    duration: "11h 30m",
  },
  hotel: {
    name: "Hotel Zoe",
    location: "Union Square",
    price_per_night: "$320/night",
    rating: "4.4 stars",
  },
} as const;
const shared15 = {
  type: "STATE_SNAPSHOT",
  snapshot: {
    messages: [
      {
        content: "I want to visit San Francisco from Amsterdam",
        additional_kwargs: {},
        response_metadata: {},
        type: "human",
        name: null,
        id: "id-3",
      },
    ],
    itinerary: {},
    tools: [],
  },
} as const;
const shared16 = {
  content: "Hotels Agent: Excellent choice! You'll like The Ritz-Carlton.",
  additional_kwargs: {},
  response_metadata: {},
  type: "ai",
  name: null,
  id: "id-13",
  tool_calls: [],
  invalid_tool_calls: [],
  usage_metadata: null,
} as const;
const shared17 = {
  content: "Hotels Agent: Excellent choice! You'll like Hotel Zoe.",
  additional_kwargs: {},
  response_metadata: {},
  type: "ai",
  name: null,
  id: "id-13",
  tool_calls: [],
  invalid_tool_calls: [],
  usage_metadata: null,
} as const;
const shared18 = {
  type: "STATE_SNAPSHOT",
  snapshot: {
    messages: [
      {
        content: "Help me plan a trip to San Francisco",
        additional_kwargs: {},
        response_metadata: {},
        type: "human",
        name: null,
        id: "id-3",
      },
    ],
    itinerary: {},
    tools: [],
  },
} as const;
const shared19 = {
  type: "MESSAGES_SNAPSHOT",
  messages: [
    {
      id: "id-3",
      role: "user",
      content: "I want to visit San Francisco from Amsterdam",
    },
  ],
} as const;
const shared20 = {
  type: "MESSAGES_SNAPSHOT",
  messages: [
    {
      id: "id-3",
      role: "user",
      content: "Help me plan a trip to San Francisco",
    },
  ],
} as const;
const shared21 = {
  id: "id-16",
  role: "assistant",
  content:
    "I've found some wonderful experiences for your trip to San Francisco!",
} as const;
const shared22 = {
  type: "TOOL_CALL_START",
  toolCallId: "id-14",
  toolCallName: "supervisor_response",
  parentMessageId: "id-15",
} as const;
const shared23 = {
  type: "TOOL_CALL_START",
  toolCallId: "id-17",
  toolCallName: "supervisor_response",
  parentMessageId: "id-18",
} as const;
const shared24 = {
  type: "TOOL_CALL_START",
  toolCallId: "id-9",
  toolCallName: "supervisor_response",
  parentMessageId: "id-10",
} as const;
const shared25 = {
  type: "TOOL_CALL_START",
  toolCallId: "id-4",
  toolCallName: "supervisor_response",
  parentMessageId: "id-5",
} as const;
const shared26 = {
  id: "id-13",
  role: "assistant",
  content: "Hotels Agent: Excellent choice! You'll like The Ritz-Carlton.",
} as const;
const shared27 = {
  id: "id-13",
  role: "assistant",
  content: "Hotels Agent: Excellent choice! You'll like Hotel Zoe.",
} as const;
const shared28 = {
  type: "TEXT_MESSAGE_CONTENT",
  messageId: "id-16",
  delta: "erful experiences fo",
} as const;
const shared29 = {
  type: "TEXT_MESSAGE_CONTENT",
  messageId: "id-16",
  delta: "I've found some wond",
} as const;
const shared30 = {
  type: "TEXT_MESSAGE_CONTENT",
  messageId: "id-16",
  delta: "r your trip to San F",
} as const;
const shared31 = {
  type: "TOOL_CALL_ARGS",
  toolCallId: "id-14",
  delta: 'ou.","next_agent":"e',
} as const;

export const subgraphsPageEventTrace = defineEventTrace(import.meta.url, {
  completeFullTravelPlanningFlowWithFeatureValidation: [
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-2",
      protocolVersion: "1.0",
      input: {
        threadId: "id-1",
        runId: "id-2",
        protocolVersion: "1.0",
        state: {},
        messages: [
          {
            id: "id-3",
            role: "user",
            content: "Help me plan a trip to San Francisco",
          },
        ],
        tools: [],
        context: [],
        forwardedProps: {},
      },
    },
    {
      type: "STEP_STARTED",
      stepName: "supervisor",
    },
    shared25,
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: '{"answer":"Let me fi',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: 'nd flights for you!"',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: ',"next_agent":"fligh',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: 'ts_agent"}',
    },
    {
      type: "TOOL_CALL_END",
      toolCallId: "id-4",
    },
    shared18,
    shared20,
    {
      type: "STEP_FINISHED",
      stepName: "supervisor",
    },
    {
      type: "STEP_STARTED",
      stepName: "flights_agent",
    },
    {
      type: "STEP_FINISHED",
      stepName: "flights_agent",
    },
    {
      type: "STEP_STARTED",
      stepName: "flights_agent_chat_node",
    },
    shared20,
    {
      type: "STEP_FINISHED",
      stepName: "flights_agent_chat_node",
    },
    shared6,
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-7",
      protocolVersion: "1.0",
      input: {
        threadId: "id-1",
        runId: "id-7",
        protocolVersion: "1.0",
        state: {
          messages: [
            {
              content: "Help me plan a trip to San Francisco",
              additional_kwargs: {},
              response_metadata: {},
              type: "human",
              name: null,
              id: "id-3",
            },
          ],
          itinerary: {},
          tools: [],
        },
        messages: [],
        tools: [],
        context: [],
        forwardedProps: {},
        resume: [
          {
            interruptId: "id-6",
            status: "resolved",
            payload:
              '{"airline":"KLM","departure":"Amsterdam (AMS)","arrival":"San Francisco (SFO)","price":"$650","duration":"11h 30m"}',
          },
        ],
      },
    },
    shared18,
    shared20,
    {
      type: "STEP_STARTED",
      stepName: "flights_agent",
    },
    {
      type: "STEP_FINISHED",
      stepName: "flights_agent",
    },
    {
      type: "STEP_STARTED",
      stepName: "flights_agent_chat_node",
    },
    {
      type: "STEP_FINISHED",
      stepName: "flights_agent_chat_node",
    },
    {
      type: "STEP_STARTED",
      stepName: "flights_agent",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            content: "Help me plan a trip to San Francisco",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-3",
          },
          {
            content: shared4,
            additional_kwargs: {},
            response_metadata: {},
            type: "ai",
            name: null,
            id: "id-8",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
        ],
        itinerary: {
          flight: {
            airline: "KLM",
            departure: "Amsterdam (AMS)",
            arrival: "San Francisco (SFO)",
            price: "$650",
            duration: "11h 30m",
          },
        },
        tools: [],
        flights: [
          {
            airline: "KLM",
            departure: "Amsterdam (AMS)",
            arrival: "San Francisco (SFO)",
            price: "$650",
            duration: "11h 30m",
          },
          {
            airline: "United",
            departure: "Amsterdam (AMS)",
            arrival: "San Francisco (SFO)",
            price: "$720",
            duration: "12h 15m",
          },
        ],
      },
    },
    {
      type: "STEP_FINISHED",
      stepName: "flights_agent",
    },
    {
      type: "STEP_STARTED",
      stepName: "supervisor",
    },
    shared24,
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-9",
      delta: '{"answer":"Great cho',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-9",
      delta: "ice! Now let me find",
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-9",
      delta: ' hotels for you.","n',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-9",
      delta: 'ext_agent":"hotels_a',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-9",
      delta: 'gent"}',
    },
    {
      type: "TOOL_CALL_END",
      toolCallId: "id-9",
    },
    shared12,
    {
      type: "STEP_FINISHED",
      stepName: "supervisor",
    },
    {
      type: "STEP_STARTED",
      stepName: "hotels_agent",
    },
    {
      type: "STEP_FINISHED",
      stepName: "hotels_agent",
    },
    {
      type: "STEP_STARTED",
      stepName: "hotels_agent_chat_node",
    },
    shared12,
    {
      type: "STEP_FINISHED",
      stepName: "hotels_agent_chat_node",
    },
    shared5,
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-12",
      protocolVersion: "1.0",
      input: {
        threadId: "id-1",
        runId: "id-12",
        protocolVersion: "1.0",
        state: shared8,
        messages: [
          {
            id: "id-8",
            role: "assistant",
            content: shared4,
          },
        ],
        tools: [],
        context: [],
        forwardedProps: {},
        resume: [
          {
            interruptId: "id-11",
            status: "resolved",
            payload:
              '{"name":"Hotel Zoe","location":"Union Square","price_per_night":"$320/night","rating":"4.4 stars"}',
          },
        ],
      },
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: shared8,
    },
    shared12,
    {
      type: "STEP_STARTED",
      stepName: "hotels_agent",
    },
    {
      type: "STEP_FINISHED",
      stepName: "hotels_agent",
    },
    {
      type: "STEP_STARTED",
      stepName: "hotels_agent_chat_node",
    },
    {
      type: "STEP_FINISHED",
      stepName: "hotels_agent_chat_node",
    },
    {
      type: "STEP_STARTED",
      stepName: "hotels_agent",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            content: "Help me plan a trip to San Francisco",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-3",
          },
          {
            content: shared4,
            additional_kwargs: {},
            response_metadata: {},
            type: "ai",
            name: null,
            id: "id-8",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          shared17,
        ],
        flights: [
          {
            airline: "KLM",
            departure: "Amsterdam (AMS)",
            arrival: "San Francisco (SFO)",
            price: "$650",
            duration: "11h 30m",
          },
          {
            airline: "United",
            departure: "Amsterdam (AMS)",
            arrival: "San Francisco (SFO)",
            price: "$720",
            duration: "12h 15m",
          },
        ],
        itinerary: shared14,
        tools: [],
        hotels: [
          {
            name: "Hotel Zephyr",
            location: "Fisherman's Wharf",
            price_per_night: "$280/night",
            rating: "4.2 stars",
          },
          {
            name: "The Ritz-Carlton",
            location: "Nob Hill",
            price_per_night: "$550/night",
            rating: "4.8 stars",
          },
          {
            name: "Hotel Zoe",
            location: "Union Square",
            price_per_night: "$320/night",
            rating: "4.4 stars",
          },
        ],
      },
    },
    {
      type: "STEP_FINISHED",
      stepName: "hotels_agent",
    },
    {
      type: "STEP_STARTED",
      stepName: "supervisor",
    },
    shared22,
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-14",
      delta: '{"answer":"Excellent',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-14",
      delta: "! Now let me find so",
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-14",
      delta: "me experiences for y",
    },
    shared31,
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-14",
      delta: 'xperiences_agent"}',
    },
    {
      type: "TOOL_CALL_END",
      toolCallId: "id-14",
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Help me plan a trip to San Francisco",
        },
        {
          id: "id-8",
          role: "assistant",
          content: shared4,
        },
        shared27,
      ],
    },
    {
      type: "STEP_FINISHED",
      stepName: "supervisor",
    },
    {
      type: "STEP_STARTED",
      stepName: "experiences_agent",
    },
    {
      type: "STEP_FINISHED",
      stepName: "experiences_agent",
    },
    {
      type: "STEP_STARTED",
      stepName: "experiences_agent_chat_node",
    },
    {
      type: "TEXT_MESSAGE_START",
      messageId: "id-16",
      role: "assistant",
    },
    shared29,
    shared28,
    shared30,
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-16",
      delta: "rancisco!",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-16",
    },
    {
      type: "STEP_FINISHED",
      stepName: "experiences_agent_chat_node",
    },
    {
      type: "STEP_STARTED",
      stepName: "experiences_agent",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            content: "Help me plan a trip to San Francisco",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-3",
          },
          {
            content: shared4,
            additional_kwargs: {},
            response_metadata: {},
            type: "ai",
            name: null,
            id: "id-8",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          shared17,
          shared10,
        ],
        flights: [
          {
            airline: "KLM",
            departure: "Amsterdam (AMS)",
            arrival: "San Francisco (SFO)",
            price: "$650",
            duration: "11h 30m",
          },
          {
            airline: "United",
            departure: "Amsterdam (AMS)",
            arrival: "San Francisco (SFO)",
            price: "$720",
            duration: "12h 15m",
          },
        ],
        itinerary: shared14,
        tools: [],
        hotels: [
          {
            name: "Hotel Zephyr",
            location: "Fisherman's Wharf",
            price_per_night: "$280/night",
            rating: "4.2 stars",
          },
          {
            name: "The Ritz-Carlton",
            location: "Nob Hill",
            price_per_night: "$550/night",
            rating: "4.8 stars",
          },
          {
            name: "Hotel Zoe",
            location: "Union Square",
            price_per_night: "$320/night",
            rating: "4.4 stars",
          },
        ],
        experiences: shared9,
      },
    },
    {
      type: "STEP_FINISHED",
      stepName: "experiences_agent",
    },
    {
      type: "STEP_STARTED",
      stepName: "supervisor",
    },
    shared23,
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-17",
      delta: '{"answer":"Your trav',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-17",
      delta: 'el plan is all set!"',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-17",
      delta: ',"next_agent":"compl',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-17",
      delta: 'ete"}',
    },
    {
      type: "TOOL_CALL_END",
      toolCallId: "id-17",
    },
    {
      type: "STEP_FINISHED",
      stepName: "supervisor",
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Help me plan a trip to San Francisco",
        },
        {
          id: "id-8",
          role: "assistant",
          content: shared4,
        },
        shared27,
        shared21,
      ],
    },
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-12",
    },
  ],
  handleDifferentSelectionsAndDemonstrateSupervisorRoutingPatterns: [
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-2",
      protocolVersion: "1.0",
      input: {
        threadId: "id-1",
        runId: "id-2",
        protocolVersion: "1.0",
        state: {},
        messages: [
          {
            id: "id-3",
            role: "user",
            content: "I want to visit San Francisco from Amsterdam",
          },
        ],
        tools: [],
        context: [],
        forwardedProps: {},
      },
    },
    {
      type: "STEP_STARTED",
      stepName: "supervisor",
    },
    shared25,
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: '{"answer":"Let me fi',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: 'nd flights for you!"',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: ',"next_agent":"fligh',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-4",
      delta: 'ts_agent"}',
    },
    {
      type: "TOOL_CALL_END",
      toolCallId: "id-4",
    },
    shared15,
    shared19,
    {
      type: "STEP_FINISHED",
      stepName: "supervisor",
    },
    {
      type: "STEP_STARTED",
      stepName: "flights_agent",
    },
    {
      type: "STEP_FINISHED",
      stepName: "flights_agent",
    },
    {
      type: "STEP_STARTED",
      stepName: "flights_agent_chat_node",
    },
    shared19,
    {
      type: "STEP_FINISHED",
      stepName: "flights_agent_chat_node",
    },
    shared6,
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-7",
      protocolVersion: "1.0",
      input: {
        threadId: "id-1",
        runId: "id-7",
        protocolVersion: "1.0",
        state: {
          messages: [
            {
              content: "I want to visit San Francisco from Amsterdam",
              additional_kwargs: {},
              response_metadata: {},
              type: "human",
              name: null,
              id: "id-3",
            },
          ],
          itinerary: {},
          tools: [],
        },
        messages: [],
        tools: [],
        context: [],
        forwardedProps: {},
        resume: [
          {
            interruptId: "id-6",
            status: "resolved",
            payload:
              '{"airline":"United","departure":"Amsterdam (AMS)","arrival":"San Francisco (SFO)","price":"$720","duration":"12h 15m"}',
          },
        ],
      },
    },
    shared15,
    shared19,
    {
      type: "STEP_STARTED",
      stepName: "flights_agent",
    },
    {
      type: "STEP_FINISHED",
      stepName: "flights_agent",
    },
    {
      type: "STEP_STARTED",
      stepName: "flights_agent_chat_node",
    },
    {
      type: "STEP_FINISHED",
      stepName: "flights_agent_chat_node",
    },
    {
      type: "STEP_STARTED",
      stepName: "flights_agent",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            content: "I want to visit San Francisco from Amsterdam",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-3",
          },
          {
            content: shared3,
            additional_kwargs: {},
            response_metadata: {},
            type: "ai",
            name: null,
            id: "id-8",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
        ],
        itinerary: {
          flight: {
            airline: "United",
            departure: "Amsterdam (AMS)",
            arrival: "San Francisco (SFO)",
            price: "$720",
            duration: "12h 15m",
          },
        },
        tools: [],
        flights: [
          {
            airline: "KLM",
            departure: "Amsterdam (AMS)",
            arrival: "San Francisco (SFO)",
            price: "$650",
            duration: "11h 30m",
          },
          {
            airline: "United",
            departure: "Amsterdam (AMS)",
            arrival: "San Francisco (SFO)",
            price: "$720",
            duration: "12h 15m",
          },
        ],
      },
    },
    {
      type: "STEP_FINISHED",
      stepName: "flights_agent",
    },
    {
      type: "STEP_STARTED",
      stepName: "supervisor",
    },
    shared24,
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-9",
      delta: '{"answer":"Great cho',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-9",
      delta: "ice! Now let me find",
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-9",
      delta: ' hotels for you.","n',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-9",
      delta: 'ext_agent":"hotels_a',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-9",
      delta: 'gent"}',
    },
    {
      type: "TOOL_CALL_END",
      toolCallId: "id-9",
    },
    shared11,
    {
      type: "STEP_FINISHED",
      stepName: "supervisor",
    },
    {
      type: "STEP_STARTED",
      stepName: "hotels_agent",
    },
    {
      type: "STEP_FINISHED",
      stepName: "hotels_agent",
    },
    {
      type: "STEP_STARTED",
      stepName: "hotels_agent_chat_node",
    },
    shared11,
    {
      type: "STEP_FINISHED",
      stepName: "hotels_agent_chat_node",
    },
    shared5,
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-12",
      protocolVersion: "1.0",
      input: {
        threadId: "id-1",
        runId: "id-12",
        protocolVersion: "1.0",
        state: shared7,
        messages: [
          {
            id: "id-8",
            role: "assistant",
            content: shared3,
          },
        ],
        tools: [],
        context: [],
        forwardedProps: {},
        resume: [
          {
            interruptId: "id-11",
            status: "resolved",
            payload:
              '{"name":"The Ritz-Carlton","location":"Nob Hill","price_per_night":"$550/night","rating":"4.8 stars"}',
          },
        ],
      },
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: shared7,
    },
    shared11,
    {
      type: "STEP_STARTED",
      stepName: "hotels_agent",
    },
    {
      type: "STEP_FINISHED",
      stepName: "hotels_agent",
    },
    {
      type: "STEP_STARTED",
      stepName: "hotels_agent_chat_node",
    },
    {
      type: "STEP_FINISHED",
      stepName: "hotels_agent_chat_node",
    },
    {
      type: "STEP_STARTED",
      stepName: "hotels_agent",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            content: "I want to visit San Francisco from Amsterdam",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-3",
          },
          {
            content: shared3,
            additional_kwargs: {},
            response_metadata: {},
            type: "ai",
            name: null,
            id: "id-8",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          shared16,
        ],
        flights: [
          {
            airline: "KLM",
            departure: "Amsterdam (AMS)",
            arrival: "San Francisco (SFO)",
            price: "$650",
            duration: "11h 30m",
          },
          {
            airline: "United",
            departure: "Amsterdam (AMS)",
            arrival: "San Francisco (SFO)",
            price: "$720",
            duration: "12h 15m",
          },
        ],
        itinerary: shared13,
        tools: [],
        hotels: [
          {
            name: "Hotel Zephyr",
            location: "Fisherman's Wharf",
            price_per_night: "$280/night",
            rating: "4.2 stars",
          },
          {
            name: "The Ritz-Carlton",
            location: "Nob Hill",
            price_per_night: "$550/night",
            rating: "4.8 stars",
          },
          {
            name: "Hotel Zoe",
            location: "Union Square",
            price_per_night: "$320/night",
            rating: "4.4 stars",
          },
        ],
      },
    },
    {
      type: "STEP_FINISHED",
      stepName: "hotels_agent",
    },
    {
      type: "STEP_STARTED",
      stepName: "supervisor",
    },
    shared22,
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-14",
      delta: '{"answer":"Excellent',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-14",
      delta: "! Now let me find so",
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-14",
      delta: "me experiences for y",
    },
    shared31,
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-14",
      delta: 'xperiences_agent"}',
    },
    {
      type: "TOOL_CALL_END",
      toolCallId: "id-14",
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "I want to visit San Francisco from Amsterdam",
        },
        {
          id: "id-8",
          role: "assistant",
          content: shared3,
        },
        shared26,
      ],
    },
    {
      type: "STEP_FINISHED",
      stepName: "supervisor",
    },
    {
      type: "STEP_STARTED",
      stepName: "experiences_agent",
    },
    {
      type: "STEP_FINISHED",
      stepName: "experiences_agent",
    },
    {
      type: "STEP_STARTED",
      stepName: "experiences_agent_chat_node",
    },
    {
      type: "TEXT_MESSAGE_START",
      messageId: "id-16",
      role: "assistant",
    },
    shared29,
    shared28,
    shared30,
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-16",
      delta: "rancisco!",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-16",
    },
    {
      type: "STEP_FINISHED",
      stepName: "experiences_agent_chat_node",
    },
    {
      type: "STEP_STARTED",
      stepName: "experiences_agent",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            content: "I want to visit San Francisco from Amsterdam",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-3",
          },
          {
            content: shared3,
            additional_kwargs: {},
            response_metadata: {},
            type: "ai",
            name: null,
            id: "id-8",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          shared16,
          shared10,
        ],
        flights: [
          {
            airline: "KLM",
            departure: "Amsterdam (AMS)",
            arrival: "San Francisco (SFO)",
            price: "$650",
            duration: "11h 30m",
          },
          {
            airline: "United",
            departure: "Amsterdam (AMS)",
            arrival: "San Francisco (SFO)",
            price: "$720",
            duration: "12h 15m",
          },
        ],
        itinerary: shared13,
        tools: [],
        hotels: [
          {
            name: "Hotel Zephyr",
            location: "Fisherman's Wharf",
            price_per_night: "$280/night",
            rating: "4.2 stars",
          },
          {
            name: "The Ritz-Carlton",
            location: "Nob Hill",
            price_per_night: "$550/night",
            rating: "4.8 stars",
          },
          {
            name: "Hotel Zoe",
            location: "Union Square",
            price_per_night: "$320/night",
            rating: "4.4 stars",
          },
        ],
        experiences: shared9,
      },
    },
    {
      type: "STEP_FINISHED",
      stepName: "experiences_agent",
    },
    {
      type: "STEP_STARTED",
      stepName: "supervisor",
    },
    shared23,
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-17",
      delta: '{"answer":"Your trav',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-17",
      delta: 'el plan is all set!"',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-17",
      delta: ',"next_agent":"compl',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-17",
      delta: 'ete"}',
    },
    {
      type: "TOOL_CALL_END",
      toolCallId: "id-17",
    },
    {
      type: "STEP_FINISHED",
      stepName: "supervisor",
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "I want to visit San Francisco from Amsterdam",
        },
        {
          id: "id-8",
          role: "assistant",
          content: shared3,
        },
        shared26,
        shared21,
      ],
    },
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-12",
    },
  ],
});
