# Dependabot configuration for AG-UI Go SDK
# This file configures automated dependency updates for the project

version: 2

updates:
  # Go modules dependency updates
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    
    # Update strategy
    open-pull-requests-limit: 10
    target-branch: "main"
    
    # Commit message configuration
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    
    # Review configuration
    reviewers:
      - "ag-ui/go-maintainers"
    assignees:
      - "ag-ui/go-maintainers"
    
    # Labels to add to pull requests
    labels:
      - "dependencies"
      - "go"
      - "automated"
    
    # Milestone to add to pull requests
    milestone: "Dependencies"
    
    # Version update strategy
    versioning-strategy: "increase"
    
    # Rebase strategy
    rebase-strategy: "auto"
    
    # Allow specific dependency updates
    allow:
      # Allow all security updates
      - dependency-type: "all"
        update-type: "security"
      
      # Allow direct dependencies updates
      - dependency-type: "direct"
        update-type: "version-update:semver-patch"
      
      - dependency-type: "direct"
        update-type: "version-update:semver-minor"
      
      # Be more cautious with major version updates for direct dependencies
      - dependency-type: "direct"
        update-type: "version-update:semver-major"
      
      # Allow indirect dependency updates for security
      - dependency-type: "indirect"
        update-type: "security"
    
    # Ignore specific dependencies or versions
    ignore:
      # Ignore specific packages that might need manual attention
      - dependency-name: "google.golang.org/grpc"
        update-types: ["version-update:semver-major"]
        reason: "Major gRPC updates require careful testing with protocol buffer compatibility"
      
      - dependency-name: "google.golang.org/protobuf"
        update-types: ["version-update:semver-major"]
        reason: "Major protobuf updates require regeneration of all proto files"
    
    # Groups for bundling related updates
    groups:
      # Group golang.org/x/* packages together
      golang-x:
        patterns:
          - "golang.org/x/*"
        update-types:
          - "minor"
          - "patch"
      
      # Group Google/gRPC related packages
      grpc-ecosystem:
        patterns:
          - "google.golang.org/grpc*"
          - "google.golang.org/protobuf*"
          - "google.golang.org/genproto*"
        update-types:
          - "minor"
          - "patch"
      
      # Group testing frameworks
      testing:
        patterns:
          - "github.com/stretchr/testify*"
          - "github.com/golang/mock*"
          - "go.uber.org/mock*"
        update-types:
          - "minor"
          - "patch"
      
      # Group security-related tools
      security-tools:
        patterns:
          - "*gosec*"
          - "*govulncheck*"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions dependency updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "UTC"
    
    open-pull-requests-limit: 5
    target-branch: "main"
    
    commit-message:
      prefix: "ci"
      include: "scope"
    
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
    
    reviewers:
      - "ag-ui/go-maintainers"

  # Docker dependency updates (if Dockerfiles are added in the future)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "UTC"
    
    open-pull-requests-limit: 3
    target-branch: "main"
    
    commit-message:
      prefix: "docker"
      include: "scope"
    
    labels:
      - "dependencies"
      - "docker"
      - "automated"
    
    reviewers:
      - "ag-ui/go-maintainers" 