// V2 provenance: historical seed 40284a07ad184eddc7fc77bda8fa23ff64398af9;
// verified/updated only through forced V2 on 2026-09-25, never transformer V3.
// Independent full V2 replay passed with committed dependency locks and production
// CopilotKit SDK 0.1.96 source commit 53110f119632dc6b99583893294413f88a5c00d3.
import { defineEventTrace } from "../../../event-trace-test";

// Generated by the event trace updater.
// Reason: Forced-V2 browser capture on 2026-09-25, using committed dependency locks (TypeScript LangGraph 1.4.8; Python LangGraph 1.2.10/API 0.14.4) with production CopilotKit 0.1.96 commit 53110f11. Refreshes historical V2 references for current runtime state boundaries, production ag-ui state preservation, and current mock fixtures. Never captured from transformer V3; independent strict V2 replay passed on 2026-09-25.
// Before accepting changes, verify whether the implementation regressed.
const shared1 =
  '{"steps":[{"description":"Crack eggs into bowl","status":"enabled"},{"description":"Preheat oven to 350F","status":"enabled"},{"description":"Mix and bake for 25 min","status":"enabled"}]}' as const;
const shared2 =
  '{"steps":[{"description":"Start The Planning","status":"enabled"},{"description":"Design spacecraft","status":"enabled"},{"description":"Launch mission","status":"enabled"}]}' as const;
const shared3 =
  "Give me a plan to make brownies, there should be only one step with eggs and one step with oven, this is a strict requirement so adhere" as const;
const shared4 =
  "Does the planner include Start The Planning? ⚠️ Reply with only words 'Yes' or 'No' (no explanation, no punctuation)." as const;
const shared5 =
  "Does the planner include eggs? ⚠️ Reply with only words 'Yes' or 'No' (no explanation, no punctuation)." as const;
const shared6 = {
  steps: [
    {
      description: "Crack eggs into bowl",
      status: "enabled",
    },
    {
      description: "Preheat oven to 350F",
      status: "enabled",
    },
    {
      description: "Mix and bake for 25 min",
      status: "enabled",
    },
  ],
  tools: [
    {
      type: "function",
      name: "generate_task_steps",
      function: {
        name: "generate_task_steps",
        description: "Generates a list of steps for the user to perform",
        parameters: {
          type: "object",
          properties: {
            steps: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  description: {
                    type: "string",
                  },
                  status: {
                    type: "string",
                    enum: ["enabled", "disabled", "executing"],
                  },
                },
                required: ["description", "status"],
              },
            },
          },
          required: ["steps"],
        },
      },
    },
  ],
  messages: [
    {
      id: "id-3",
      content: "Hi",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
    },
    {
      content: "Hello! How can I assist you today?",
      additional_kwargs: {},
      response_metadata: {
        model_provider: "openai",
        usage: {
          prompt_tokens: 58,
          completion_tokens: 9,
          total_tokens: 67,
        },
      },
      tool_call_chunks: [],
      id: "id-4",
      usage_metadata: {
        input_tokens: 58,
        output_tokens: 9,
        total_tokens: 67,
        input_token_details: {},
        output_token_details: {},
      },
      invalid_tool_calls: [],
      tool_calls: [],
      type: "ai",
    },
    {
      id: "id-7",
      content: shared3,
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
    },
    {
      content: "",
      additional_kwargs: {
        tool_calls: [
          {
            index: 0,
            id: "id-8",
            type: "function",
            function: {
              name: "plan_execution_steps",
              arguments: shared1,
            },
          },
        ],
      },
      response_metadata: {
        model_provider: "openai",
        usage: {
          prompt_tokens: 100,
          completion_tokens: 52,
          total_tokens: 152,
        },
      },
      tool_call_chunks: [
        {
          name: "plan_execution_steps",
          args: shared1,
          id: "id-8",
          index: 0,
          type: "tool_call_chunk",
        },
      ],
      tool_calls: [
        {
          name: "plan_execution_steps",
          args: {
            steps: [
              {
                description: "Crack eggs into bowl",
                status: "enabled",
              },
              {
                description: "Preheat oven to 350F",
                status: "enabled",
              },
              {
                description: "Mix and bake for 25 min",
                status: "enabled",
              },
            ],
          },
          id: "id-8",
          type: "tool_call",
        },
      ],
      id: "id-9",
      usage_metadata: {
        input_tokens: 100,
        output_tokens: 52,
        total_tokens: 152,
        input_token_details: {},
        output_token_details: {},
      },
      invalid_tool_calls: [],
      type: "ai",
    },
    {
      content: "Task steps generated.",
      tool_call_id: "id-8",
      additional_kwargs: {},
      response_metadata: {},
      id: "id-10",
      type: "tool",
    },
    {
      content: "I understand. How can I help you with that?",
      additional_kwargs: {},
      response_metadata: {
        model_provider: "openai",
        usage: {
          prompt_tokens: 144,
          completion_tokens: 11,
          total_tokens: 155,
        },
      },
      tool_call_chunks: [],
      tool_calls: [],
      id: "id-12",
      usage_metadata: {
        input_tokens: 144,
        output_tokens: 11,
        total_tokens: 155,
        input_token_details: {},
        output_token_details: {},
      },
      invalid_tool_calls: [],
      type: "ai",
    },
  ],
} as const;
const shared7 = {
  steps: [
    {
      description: "Start The Planning",
      status: "enabled",
    },
    {
      description: "Design spacecraft",
      status: "enabled",
    },
    {
      description: "Launch mission",
      status: "enabled",
    },
  ],
  tools: [
    {
      type: "function",
      name: "generate_task_steps",
      function: {
        name: "generate_task_steps",
        description: "Generates a list of steps for the user to perform",
        parameters: {
          type: "object",
          properties: {
            steps: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  description: {
                    type: "string",
                  },
                  status: {
                    type: "string",
                    enum: ["enabled", "disabled", "executing"],
                  },
                },
                required: ["description", "status"],
              },
            },
          },
          required: ["steps"],
        },
      },
    },
  ],
  messages: [
    {
      id: "id-3",
      content: "Hi",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
    },
    {
      content: "Hello! How can I assist you today?",
      additional_kwargs: {},
      response_metadata: {
        model_provider: "openai",
        usage: {
          prompt_tokens: 58,
          completion_tokens: 9,
          total_tokens: 67,
        },
      },
      tool_call_chunks: [],
      id: "id-4",
      usage_metadata: {
        input_tokens: 58,
        output_tokens: 9,
        total_tokens: 67,
        input_token_details: {},
        output_token_details: {},
      },
      invalid_tool_calls: [],
      tool_calls: [],
      type: "ai",
    },
    {
      id: "id-7",
      content:
        "Plan a mission to Mars with the first step being Start The Planning",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
    },
    {
      content: "",
      additional_kwargs: {
        tool_calls: [
          {
            index: 0,
            id: "id-8",
            type: "function",
            function: {
              name: "plan_execution_steps",
              arguments: shared2,
            },
          },
        ],
      },
      response_metadata: {
        model_provider: "openai",
        usage: {
          prompt_tokens: 83,
          completion_tokens: 49,
          total_tokens: 132,
        },
      },
      tool_call_chunks: [
        {
          name: "plan_execution_steps",
          args: shared2,
          id: "id-8",
          index: 0,
          type: "tool_call_chunk",
        },
      ],
      tool_calls: [
        {
          name: "plan_execution_steps",
          args: {
            steps: [
              {
                description: "Start The Planning",
                status: "enabled",
              },
              {
                description: "Design spacecraft",
                status: "enabled",
              },
              {
                description: "Launch mission",
                status: "enabled",
              },
            ],
          },
          id: "id-8",
          type: "tool_call",
        },
      ],
      id: "id-9",
      usage_metadata: {
        input_tokens: 83,
        output_tokens: 49,
        total_tokens: 132,
        input_token_details: {},
        output_token_details: {},
      },
      invalid_tool_calls: [],
      type: "ai",
    },
    {
      content: "Task steps generated.",
      tool_call_id: "id-8",
      additional_kwargs: {},
      response_metadata: {},
      id: "id-10",
      type: "tool",
    },
    {
      content: "I understand. How can I help you with that?",
      additional_kwargs: {},
      response_metadata: {
        model_provider: "openai",
        usage: {
          prompt_tokens: 141,
          completion_tokens: 11,
          total_tokens: 152,
        },
      },
      tool_call_chunks: [],
      tool_calls: [],
      id: "id-12",
      usage_metadata: {
        input_tokens: 141,
        output_tokens: 11,
        total_tokens: 152,
        input_token_details: {},
        output_token_details: {},
      },
      invalid_tool_calls: [],
      type: "ai",
    },
  ],
} as const;
const shared8 = {
  type: "STATE_SNAPSHOT",
  snapshot: {
    steps: [
      {
        description: "Crack eggs into bowl",
        status: "enabled",
      },
      {
        description: "Preheat oven to 350F",
        status: "enabled",
      },
      {
        description: "Mix and bake for 25 min",
        status: "enabled",
      },
    ],
    tools: [
      {
        type: "function",
        name: "generate_task_steps",
        function: {
          name: "generate_task_steps",
          description: "Generates a list of steps for the user to perform",
          parameters: {
            type: "object",
            properties: {
              steps: {
                type: "array",
                items: {
                  type: "object",
                  properties: {
                    description: {
                      type: "string",
                    },
                    status: {
                      type: "string",
                      enum: ["enabled", "disabled", "executing"],
                    },
                  },
                  required: ["description", "status"],
                },
              },
            },
            required: ["steps"],
          },
        },
      },
    ],
    messages: [
      {
        id: "id-3",
        content: "Hi",
        additional_kwargs: {},
        response_metadata: {},
        type: "human",
      },
      {
        content: "Hello! How can I assist you today?",
        additional_kwargs: {},
        response_metadata: {
          model_provider: "openai",
          usage: {
            prompt_tokens: 58,
            completion_tokens: 9,
            total_tokens: 67,
          },
        },
        tool_call_chunks: [],
        id: "id-4",
        usage_metadata: {
          input_tokens: 58,
          output_tokens: 9,
          total_tokens: 67,
          input_token_details: {},
          output_token_details: {},
        },
        invalid_tool_calls: [],
        tool_calls: [],
        type: "ai",
      },
      {
        id: "id-7",
        content: shared3,
        additional_kwargs: {},
        response_metadata: {},
        type: "human",
      },
      {
        content: "",
        additional_kwargs: {
          tool_calls: [
            {
              index: 0,
              id: "id-8",
              type: "function",
              function: {
                name: "plan_execution_steps",
                arguments: shared1,
              },
            },
          ],
        },
        response_metadata: {
          model_provider: "openai",
          usage: {
            prompt_tokens: 100,
            completion_tokens: 52,
            total_tokens: 152,
          },
        },
        tool_call_chunks: [
          {
            name: "plan_execution_steps",
            args: shared1,
            id: "id-8",
            index: 0,
            type: "tool_call_chunk",
          },
        ],
        tool_calls: [
          {
            name: "plan_execution_steps",
            args: {
              steps: [
                {
                  description: "Crack eggs into bowl",
                  status: "enabled",
                },
                {
                  description: "Preheat oven to 350F",
                  status: "enabled",
                },
                {
                  description: "Mix and bake for 25 min",
                  status: "enabled",
                },
              ],
            },
            id: "id-8",
            type: "tool_call",
          },
        ],
        id: "id-9",
        usage_metadata: {
          input_tokens: 100,
          output_tokens: 52,
          total_tokens: 152,
          input_token_details: {},
          output_token_details: {},
        },
        invalid_tool_calls: [],
        type: "ai",
      },
      {
        content: "Task steps generated.",
        tool_call_id: "id-8",
        additional_kwargs: {},
        response_metadata: {},
        id: "id-10",
        type: "tool",
      },
    ],
  },
} as const;
const shared9 = {
  type: "STATE_SNAPSHOT",
  snapshot: {
    steps: [
      {
        description: "Start The Planning",
        status: "enabled",
      },
      {
        description: "Design spacecraft",
        status: "enabled",
      },
      {
        description: "Launch mission",
        status: "enabled",
      },
    ],
    tools: [
      {
        type: "function",
        name: "generate_task_steps",
        function: {
          name: "generate_task_steps",
          description: "Generates a list of steps for the user to perform",
          parameters: {
            type: "object",
            properties: {
              steps: {
                type: "array",
                items: {
                  type: "object",
                  properties: {
                    description: {
                      type: "string",
                    },
                    status: {
                      type: "string",
                      enum: ["enabled", "disabled", "executing"],
                    },
                  },
                  required: ["description", "status"],
                },
              },
            },
            required: ["steps"],
          },
        },
      },
    ],
    messages: [
      {
        id: "id-3",
        content: "Hi",
        additional_kwargs: {},
        response_metadata: {},
        type: "human",
      },
      {
        content: "Hello! How can I assist you today?",
        additional_kwargs: {},
        response_metadata: {
          model_provider: "openai",
          usage: {
            prompt_tokens: 58,
            completion_tokens: 9,
            total_tokens: 67,
          },
        },
        tool_call_chunks: [],
        id: "id-4",
        usage_metadata: {
          input_tokens: 58,
          output_tokens: 9,
          total_tokens: 67,
          input_token_details: {},
          output_token_details: {},
        },
        invalid_tool_calls: [],
        tool_calls: [],
        type: "ai",
      },
      {
        id: "id-7",
        content:
          "Plan a mission to Mars with the first step being Start The Planning",
        additional_kwargs: {},
        response_metadata: {},
        type: "human",
      },
      {
        content: "",
        additional_kwargs: {
          tool_calls: [
            {
              index: 0,
              id: "id-8",
              type: "function",
              function: {
                name: "plan_execution_steps",
                arguments: shared2,
              },
            },
          ],
        },
        response_metadata: {
          model_provider: "openai",
          usage: {
            prompt_tokens: 83,
            completion_tokens: 49,
            total_tokens: 132,
          },
        },
        tool_call_chunks: [
          {
            name: "plan_execution_steps",
            args: shared2,
            id: "id-8",
            index: 0,
            type: "tool_call_chunk",
          },
        ],
        tool_calls: [
          {
            name: "plan_execution_steps",
            args: {
              steps: [
                {
                  description: "Start The Planning",
                  status: "enabled",
                },
                {
                  description: "Design spacecraft",
                  status: "enabled",
                },
                {
                  description: "Launch mission",
                  status: "enabled",
                },
              ],
            },
            id: "id-8",
            type: "tool_call",
          },
        ],
        id: "id-9",
        usage_metadata: {
          input_tokens: 83,
          output_tokens: 49,
          total_tokens: 132,
          input_token_details: {},
          output_token_details: {},
        },
        invalid_tool_calls: [],
        type: "ai",
      },
      {
        content: "Task steps generated.",
        tool_call_id: "id-8",
        additional_kwargs: {},
        response_metadata: {},
        id: "id-10",
        type: "tool",
      },
    ],
  },
} as const;
const shared10 = {
  content: "",
  additional_kwargs: {
    tool_calls: [
      {
        index: 0,
        id: "id-8",
        type: "function",
        function: {
          name: "plan_execution_steps",
          arguments: shared1,
        },
      },
    ],
  },
  response_metadata: {
    model_provider: "openai",
    usage: {
      prompt_tokens: 100,
      completion_tokens: 52,
      total_tokens: 152,
    },
  },
  tool_call_chunks: [
    {
      name: "plan_execution_steps",
      args: shared1,
      id: "id-8",
      index: 0,
      type: "tool_call_chunk",
    },
  ],
  id: "id-9",
  usage_metadata: {
    input_tokens: 100,
    output_tokens: 52,
    total_tokens: 152,
    input_token_details: {},
    output_token_details: {},
  },
  invalid_tool_calls: [],
  tool_calls: [
    {
      name: "plan_execution_steps",
      args: {
        steps: [
          {
            description: "Crack eggs into bowl",
            status: "enabled",
          },
          {
            description: "Preheat oven to 350F",
            status: "enabled",
          },
          {
            description: "Mix and bake for 25 min",
            status: "enabled",
          },
        ],
      },
      id: "id-8",
      type: "tool_call",
    },
  ],
  type: "ai",
} as const;
const shared11 = {
  content: "",
  additional_kwargs: {
    tool_calls: [
      {
        index: 0,
        id: "id-8",
        type: "function",
        function: {
          name: "plan_execution_steps",
          arguments: shared2,
        },
      },
    ],
  },
  response_metadata: {
    model_provider: "openai",
    usage: {
      prompt_tokens: 83,
      completion_tokens: 49,
      total_tokens: 132,
    },
  },
  tool_call_chunks: [
    {
      name: "plan_execution_steps",
      args: shared2,
      id: "id-8",
      index: 0,
      type: "tool_call_chunk",
    },
  ],
  id: "id-9",
  usage_metadata: {
    input_tokens: 83,
    output_tokens: 49,
    total_tokens: 132,
    input_token_details: {},
    output_token_details: {},
  },
  invalid_tool_calls: [],
  tool_calls: [
    {
      name: "plan_execution_steps",
      args: {
        steps: [
          {
            description: "Start The Planning",
            status: "enabled",
          },
          {
            description: "Design spacecraft",
            status: "enabled",
          },
          {
            description: "Launch mission",
            status: "enabled",
          },
        ],
      },
      id: "id-8",
      type: "tool_call",
    },
  ],
  type: "ai",
} as const;
const shared12 = {
  type: "STATE_SNAPSHOT",
  snapshot: {
    steps: [],
    tools: [
      {
        type: "function",
        name: "generate_task_steps",
        function: {
          name: "generate_task_steps",
          description: "Generates a list of steps for the user to perform",
          parameters: {
            type: "object",
            properties: {
              steps: {
                type: "array",
                items: {
                  type: "object",
                  properties: {
                    description: {
                      type: "string",
                    },
                    status: {
                      type: "string",
                      enum: ["enabled", "disabled", "executing"],
                    },
                  },
                  required: ["description", "status"],
                },
              },
            },
            required: ["steps"],
          },
        },
      },
    ],
    messages: [
      {
        id: "id-3",
        content: "Hi",
        additional_kwargs: {},
        response_metadata: {},
        type: "human",
      },
      {
        content: "Hello! How can I assist you today?",
        additional_kwargs: {},
        response_metadata: {
          model_provider: "openai",
          usage: {
            prompt_tokens: 58,
            completion_tokens: 9,
            total_tokens: 67,
          },
        },
        tool_call_chunks: [],
        tool_calls: [],
        id: "id-4",
        usage_metadata: {
          input_tokens: 58,
          output_tokens: 9,
          total_tokens: 67,
          input_token_details: {},
          output_token_details: {},
        },
        invalid_tool_calls: [],
        type: "ai",
      },
    ],
  },
} as const;
const shared13 = {
  type: "STATE_SNAPSHOT",
  snapshot: {
    steps: [],
    tools: [
      {
        type: "function",
        name: "generate_task_steps",
        function: {
          name: "generate_task_steps",
          description: "Generates a list of steps for the user to perform",
          parameters: {
            type: "object",
            properties: {
              steps: {
                type: "array",
                items: {
                  type: "object",
                  properties: {
                    description: {
                      type: "string",
                    },
                    status: {
                      type: "string",
                      enum: ["enabled", "disabled", "executing"],
                    },
                  },
                  required: ["description", "status"],
                },
              },
            },
            required: ["steps"],
          },
        },
      },
    ],
    messages: [
      {
        id: "id-3",
        content: "Hi",
        additional_kwargs: {},
        response_metadata: {},
        type: "human",
      },
    ],
  },
} as const;
const shared14 = {
  type: "RUN_STARTED",
  threadId: "id-1",
  runId: "id-2",
  input: {
    threadId: "id-1",
    runId: "id-2",
    state: {},
    messages: [
      {
        id: "id-3",
        role: "user",
        content: "Hi",
      },
    ],
    tools: [
      {
        name: "generate_task_steps",
        description: "Generates a list of steps for the user to perform",
        parameters: {
          type: "object",
          properties: {
            steps: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  description: {
                    type: "string",
                  },
                  status: {
                    type: "string",
                    enum: ["enabled", "disabled", "executing"],
                  },
                },
                required: ["description", "status"],
              },
            },
          },
          required: ["steps"],
        },
      },
    ],
    context: [],
    forwardedProps: {},
  },
} as const;
const shared15 = {
  content: "I understand. How can I help you with that?",
  additional_kwargs: {},
  response_metadata: {
    model_provider: "openai",
    usage: {
      prompt_tokens: 141,
      completion_tokens: 11,
      total_tokens: 152,
    },
  },
  tool_call_chunks: [],
  id: "id-12",
  usage_metadata: {
    input_tokens: 141,
    output_tokens: 11,
    total_tokens: 152,
    input_token_details: {},
    output_token_details: {},
  },
  invalid_tool_calls: [],
  tool_calls: [],
  type: "ai",
} as const;
const shared16 = {
  content: "I understand. How can I help you with that?",
  additional_kwargs: {},
  response_metadata: {
    model_provider: "openai",
    usage: {
      prompt_tokens: 144,
      completion_tokens: 11,
      total_tokens: 155,
    },
  },
  tool_call_chunks: [],
  id: "id-12",
  usage_metadata: {
    input_tokens: 144,
    output_tokens: 11,
    total_tokens: 155,
    input_token_details: {},
    output_token_details: {},
  },
  invalid_tool_calls: [],
  tool_calls: [],
  type: "ai",
} as const;
const shared17 = {
  id: "id-9",
  role: "assistant",
  content: "",
  toolCalls: [
    {
      id: "id-8",
      type: "function",
      function: {
        name: "plan_execution_steps",
        arguments: shared1,
      },
    },
  ],
} as const;
const shared18 = {
  id: "id-9",
  role: "assistant",
  content: "",
  toolCalls: [
    {
      id: "id-8",
      type: "function",
      function: {
        name: "plan_execution_steps",
        arguments: shared2,
      },
    },
  ],
} as const;
const shared19 = {
  type: "CUSTOM",
  name: "on_interrupt",
  value: shared2,
} as const;
const shared20 = {
  id: "id-15",
  content: shared4,
  additional_kwargs: {},
  response_metadata: {},
  type: "human",
} as const;
const shared21 = {
  id: "id-15",
  content: shared5,
  additional_kwargs: {},
  response_metadata: {},
  type: "human",
} as const;
const shared22 = {
  type: "MESSAGES_SNAPSHOT",
  messages: [
    {
      id: "id-3",
      role: "user",
      content: "Hi",
    },
    {
      id: "id-4",
      role: "assistant",
      content: "Hello! How can I assist you today?",
      toolCalls: [],
    },
  ],
} as const;
const shared23 = {
  id: "id-7",
  role: "user",
  content: shared3,
} as const;
const shared24 = {
  type: "RUN_FINISHED",
  threadId: "id-1",
  runId: "id-5",
  usage: [
    {
      provider: "openai",
      model: "gpt-4o-mini",
      inputTokens: 58,
      outputTokens: 9,
      totalTokens: 67,
    },
  ],
} as const;
const shared25 = {
  id: "id-15",
  role: "user",
  content: shared4,
} as const;
const shared26 = {
  id: "id-15",
  role: "user",
  content: shared5,
} as const;
const shared27 = {
  type: "CUSTOM",
  name: "PredictState",
  value: [
    {
      state_key: "steps",
      tool: "plan_execution_steps",
      tool_argument: "steps",
    },
  ],
} as const;
const shared28 = {
  type: "TOOL_CALL_START",
  toolCallId: "id-8",
  toolCallName: "plan_execution_steps",
  parentMessageId: "id-9",
} as const;
const shared29 = {
  id: "id-7",
  role: "user",
  content:
    "Plan a mission to Mars with the first step being Start The Planning",
} as const;
const shared30 = {
  id: "id-12",
  role: "assistant",
  content: "I understand. How can I help you with that?",
  toolCalls: [],
} as const;
const shared31 = {
  id: "id-10",
  role: "tool",
  content: "Task steps generated.",
  toolCallId: "id-8",
} as const;
const shared32 = {
  id: "id-10",
  content: "Task steps generated.",
  role: "tool",
  toolCallId: "id-8",
} as const;
const shared33 = {
  type: "TEXT_MESSAGE_CONTENT",
  messageId: "id-12",
  delta: "I understand. How ca",
} as const;
const shared34 = {
  type: "TEXT_MESSAGE_CONTENT",
  messageId: "id-12",
  delta: "n I help you with th",
} as const;
const shared35 = {
  type: "TEXT_MESSAGE_CONTENT",
  messageId: "id-4",
  delta: "Hello! How can I ass",
} as const;

export const humanInTheLoopPageEventTrace = defineEventTrace(import.meta.url, {
  interactWithTheChatAndPerformSteps: [
    shared14,
    {
      type: "STEP_STARTED",
      stepName: "start_flow",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {},
    },
    shared13,
    {
      type: "STEP_FINISHED",
      stepName: "start_flow",
    },
    {
      type: "STEP_STARTED",
      stepName: "chat_node",
    },
    {
      type: "TEXT_MESSAGE_START",
      role: "assistant",
      messageId: "id-4",
    },
    shared35,
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: "ist you today?",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-4",
    },
    shared12,
    {
      type: "STEP_FINISHED",
      stepName: "chat_node",
    },
    shared22,
    shared24,
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-6",
      input: {
        threadId: "id-1",
        runId: "id-6",
        state: {
          steps: [],
          tools: [
            {
              type: "function",
              name: "generate_task_steps",
              function: {
                name: "generate_task_steps",
                description:
                  "Generates a list of steps for the user to perform",
                parameters: {
                  type: "object",
                  properties: {
                    steps: {
                      type: "array",
                      items: {
                        type: "object",
                        properties: {
                          description: {
                            type: "string",
                          },
                          status: {
                            type: "string",
                            enum: ["enabled", "disabled", "executing"],
                          },
                        },
                        required: ["description", "status"],
                      },
                    },
                  },
                  required: ["steps"],
                },
              },
            },
          ],
          messages: [
            {
              id: "id-3",
              content: "Hi",
              additional_kwargs: {},
              response_metadata: {},
              type: "human",
            },
            {
              content: "Hello! How can I assist you today?",
              additional_kwargs: {},
              response_metadata: {
                model_provider: "openai",
                usage: {
                  prompt_tokens: 58,
                  completion_tokens: 9,
                  total_tokens: 67,
                },
              },
              tool_call_chunks: [],
              tool_calls: [],
              id: "id-4",
              usage_metadata: {
                input_tokens: 58,
                output_tokens: 9,
                total_tokens: 67,
                input_token_details: {},
                output_token_details: {},
              },
              invalid_tool_calls: [],
              type: "ai",
            },
          ],
        },
        messages: [shared23],
        tools: [
          {
            name: "generate_task_steps",
            description: "Generates a list of steps for the user to perform",
            parameters: {
              type: "object",
              properties: {
                steps: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      description: {
                        type: "string",
                      },
                      status: {
                        type: "string",
                        enum: ["enabled", "disabled", "executing"],
                      },
                    },
                    required: ["description", "status"],
                  },
                },
              },
              required: ["steps"],
            },
          },
        ],
        context: [],
        forwardedProps: {},
      },
    },
    {
      type: "STEP_STARTED",
      stepName: "start_flow",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {},
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        steps: [],
        tools: [
          {
            type: "function",
            name: "generate_task_steps",
            function: {
              name: "generate_task_steps",
              description: "Generates a list of steps for the user to perform",
              parameters: {
                type: "object",
                properties: {
                  steps: {
                    type: "array",
                    items: {
                      type: "object",
                      properties: {
                        description: {
                          type: "string",
                        },
                        status: {
                          type: "string",
                          enum: ["enabled", "disabled", "executing"],
                        },
                      },
                      required: ["description", "status"],
                    },
                  },
                },
                required: ["steps"],
              },
            },
          },
        ],
        messages: [
          {
            id: "id-3",
            content: "Hi",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
          },
          {
            content: "Hello! How can I assist you today?",
            additional_kwargs: {},
            response_metadata: {
              model_provider: "openai",
              usage: {
                prompt_tokens: 58,
                completion_tokens: 9,
                total_tokens: 67,
              },
            },
            tool_call_chunks: [],
            id: "id-4",
            usage_metadata: {
              input_tokens: 58,
              output_tokens: 9,
              total_tokens: 67,
              input_token_details: {},
              output_token_details: {},
            },
            invalid_tool_calls: [],
            tool_calls: [],
            type: "ai",
          },
          {
            id: "id-7",
            content: shared3,
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
          },
        ],
      },
    },
    {
      type: "STEP_FINISHED",
      stepName: "start_flow",
    },
    {
      type: "STEP_STARTED",
      stepName: "chat_node",
    },
    shared27,
    shared28,
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: '{"steps":[{"descript',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: 'ion":"Crack eggs int',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: 'o bowl","status":"en',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: 'abled"},{"descriptio',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: 'n":"Preheat oven to ',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: '350F","status":"enab',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: 'led"},{"description"',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: ':"Mix and bake for 2',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: '5 min","status":"ena',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: 'bled"}]}',
    },
    {
      type: "TOOL_CALL_END",
      toolCallId: "id-8",
    },
    {
      type: "STEP_FINISHED",
      stepName: "chat_node",
    },
    {
      type: "STEP_STARTED",
      stepName: "process_steps_node",
    },
    {
      type: "STEP_FINISHED",
      stepName: "process_steps_node",
    },
    shared8,
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hi",
        },
        {
          id: "id-4",
          role: "assistant",
          content: "Hello! How can I assist you today?",
          toolCalls: [],
        },
        shared23,
        shared17,
        shared31,
      ],
    },
    {
      type: "CUSTOM",
      name: "on_interrupt",
      value: shared1,
    },
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-11",
      usage: [
        {
          provider: "openai",
          model: "gpt-4o-mini",
          inputTokens: 100,
          outputTokens: 52,
          totalTokens: 152,
        },
      ],
    },
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-6",
      input: {
        threadId: "id-1",
        runId: "id-6",
        state: {
          steps: [
            {
              description: "Crack eggs into bowl",
              status: "enabled",
            },
            {
              description: "Preheat oven to 350F",
              status: "enabled",
            },
            {
              description: "Mix and bake for 25 min",
              status: "enabled",
            },
          ],
          tools: [
            {
              type: "function",
              name: "generate_task_steps",
              function: {
                name: "generate_task_steps",
                description:
                  "Generates a list of steps for the user to perform",
                parameters: {
                  type: "object",
                  properties: {
                    steps: {
                      type: "array",
                      items: {
                        type: "object",
                        properties: {
                          description: {
                            type: "string",
                          },
                          status: {
                            type: "string",
                            enum: ["enabled", "disabled", "executing"],
                          },
                        },
                        required: ["description", "status"],
                      },
                    },
                  },
                  required: ["steps"],
                },
              },
            },
          ],
          messages: [
            {
              id: "id-3",
              content: "Hi",
              additional_kwargs: {},
              response_metadata: {},
              type: "human",
            },
            {
              content: "Hello! How can I assist you today?",
              additional_kwargs: {},
              response_metadata: {
                model_provider: "openai",
                usage: {
                  prompt_tokens: 58,
                  completion_tokens: 9,
                  total_tokens: 67,
                },
              },
              tool_call_chunks: [],
              id: "id-4",
              usage_metadata: {
                input_tokens: 58,
                output_tokens: 9,
                total_tokens: 67,
                input_token_details: {},
                output_token_details: {},
              },
              invalid_tool_calls: [],
              tool_calls: [],
              type: "ai",
            },
            {
              id: "id-7",
              content: shared3,
              additional_kwargs: {},
              response_metadata: {},
              type: "human",
            },
            {
              content: "",
              additional_kwargs: {
                tool_calls: [
                  {
                    index: 0,
                    id: "id-8",
                    type: "function",
                    function: {
                      name: "plan_execution_steps",
                      arguments: shared1,
                    },
                  },
                ],
              },
              response_metadata: {
                model_provider: "openai",
                usage: {
                  prompt_tokens: 100,
                  completion_tokens: 52,
                  total_tokens: 152,
                },
              },
              tool_call_chunks: [
                {
                  name: "plan_execution_steps",
                  args: shared1,
                  id: "id-8",
                  index: 0,
                  type: "tool_call_chunk",
                },
              ],
              tool_calls: [
                {
                  name: "plan_execution_steps",
                  args: {
                    steps: [
                      {
                        description: "Crack eggs into bowl",
                        status: "enabled",
                      },
                      {
                        description: "Preheat oven to 350F",
                        status: "enabled",
                      },
                      {
                        description: "Mix and bake for 25 min",
                        status: "enabled",
                      },
                    ],
                  },
                  id: "id-8",
                  type: "tool_call",
                },
              ],
              id: "id-9",
              usage_metadata: {
                input_tokens: 100,
                output_tokens: 52,
                total_tokens: 152,
                input_token_details: {},
                output_token_details: {},
              },
              invalid_tool_calls: [],
              type: "ai",
            },
            {
              content: "Task steps generated.",
              tool_call_id: "id-8",
              additional_kwargs: {},
              response_metadata: {},
              id: "id-10",
              type: "tool",
            },
          ],
        },
        messages: [shared17, shared32],
        tools: [
          {
            name: "generate_task_steps",
            description: "Generates a list of steps for the user to perform",
            parameters: {
              type: "object",
              properties: {
                steps: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      description: {
                        type: "string",
                      },
                      status: {
                        type: "string",
                        enum: ["enabled", "disabled", "executing"],
                      },
                    },
                    required: ["description", "status"],
                  },
                },
              },
              required: ["steps"],
            },
          },
        ],
        context: [],
        forwardedProps: {
          command: {
            resume:
              "The user selected the following steps: Preheat oven to 350F, Mix and bake for 25 min",
            interruptEvent: shared1,
          },
        },
      },
    },
    {
      type: "STEP_STARTED",
      stepName: "process_steps_node",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {},
    },
    shared8,
    {
      type: "TEXT_MESSAGE_START",
      role: "assistant",
      messageId: "id-12",
    },
    shared33,
    shared34,
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-12",
      delta: "at?",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-12",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: shared6,
    },
    {
      type: "STEP_FINISHED",
      stepName: "process_steps_node",
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hi",
        },
        {
          id: "id-4",
          role: "assistant",
          content: "Hello! How can I assist you today?",
          toolCalls: [],
        },
        shared23,
        shared17,
        shared31,
        shared30,
      ],
    },
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-13",
      usage: [
        {
          provider: "openai",
          model: "gpt-4o",
          inputTokens: 144,
          outputTokens: 11,
          totalTokens: 155,
        },
      ],
    },
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-14",
      input: {
        threadId: "id-1",
        runId: "id-14",
        state: shared6,
        messages: [shared26],
        tools: [
          {
            name: "generate_task_steps",
            description: "Generates a list of steps for the user to perform",
            parameters: {
              type: "object",
              properties: {
                steps: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      description: {
                        type: "string",
                      },
                      status: {
                        type: "string",
                        enum: ["enabled", "disabled", "executing"],
                      },
                    },
                    required: ["description", "status"],
                  },
                },
              },
              required: ["steps"],
            },
          },
        ],
        context: [],
        forwardedProps: {},
      },
    },
    {
      type: "STEP_STARTED",
      stepName: "start_flow",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {},
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        steps: [
          {
            description: "Crack eggs into bowl",
            status: "enabled",
          },
          {
            description: "Preheat oven to 350F",
            status: "enabled",
          },
          {
            description: "Mix and bake for 25 min",
            status: "enabled",
          },
        ],
        tools: [
          {
            type: "function",
            name: "generate_task_steps",
            function: {
              name: "generate_task_steps",
              description: "Generates a list of steps for the user to perform",
              parameters: {
                type: "object",
                properties: {
                  steps: {
                    type: "array",
                    items: {
                      type: "object",
                      properties: {
                        description: {
                          type: "string",
                        },
                        status: {
                          type: "string",
                          enum: ["enabled", "disabled", "executing"],
                        },
                      },
                      required: ["description", "status"],
                    },
                  },
                },
                required: ["steps"],
              },
            },
          },
        ],
        messages: [
          {
            id: "id-3",
            content: "Hi",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
          },
          {
            content: "Hello! How can I assist you today?",
            additional_kwargs: {},
            response_metadata: {
              model_provider: "openai",
              usage: {
                prompt_tokens: 58,
                completion_tokens: 9,
                total_tokens: 67,
              },
            },
            tool_call_chunks: [],
            id: "id-4",
            usage_metadata: {
              input_tokens: 58,
              output_tokens: 9,
              total_tokens: 67,
              input_token_details: {},
              output_token_details: {},
            },
            invalid_tool_calls: [],
            tool_calls: [],
            type: "ai",
          },
          {
            id: "id-7",
            content: shared3,
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
          },
          shared10,
          {
            content: "Task steps generated.",
            tool_call_id: "id-8",
            additional_kwargs: {},
            response_metadata: {},
            id: "id-10",
            type: "tool",
          },
          shared16,
          shared21,
        ],
      },
    },
    {
      type: "STEP_FINISHED",
      stepName: "start_flow",
    },
    {
      type: "STEP_STARTED",
      stepName: "chat_node",
    },
    {
      type: "TEXT_MESSAGE_START",
      role: "assistant",
      messageId: "id-16",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-16",
      delta: "No",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-16",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        steps: [
          {
            description: "Crack eggs into bowl",
            status: "enabled",
          },
          {
            description: "Preheat oven to 350F",
            status: "enabled",
          },
          {
            description: "Mix and bake for 25 min",
            status: "enabled",
          },
        ],
        tools: [
          {
            type: "function",
            name: "generate_task_steps",
            function: {
              name: "generate_task_steps",
              description: "Generates a list of steps for the user to perform",
              parameters: {
                type: "object",
                properties: {
                  steps: {
                    type: "array",
                    items: {
                      type: "object",
                      properties: {
                        description: {
                          type: "string",
                        },
                        status: {
                          type: "string",
                          enum: ["enabled", "disabled", "executing"],
                        },
                      },
                      required: ["description", "status"],
                    },
                  },
                },
                required: ["steps"],
              },
            },
          },
        ],
        messages: [
          {
            id: "id-3",
            content: "Hi",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
          },
          {
            content: "Hello! How can I assist you today?",
            additional_kwargs: {},
            response_metadata: {
              model_provider: "openai",
              usage: {
                prompt_tokens: 58,
                completion_tokens: 9,
                total_tokens: 67,
              },
            },
            tool_call_chunks: [],
            id: "id-4",
            usage_metadata: {
              input_tokens: 58,
              output_tokens: 9,
              total_tokens: 67,
              input_token_details: {},
              output_token_details: {},
            },
            invalid_tool_calls: [],
            tool_calls: [],
            type: "ai",
          },
          {
            id: "id-7",
            content: shared3,
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
          },
          shared10,
          {
            content: "Task steps generated.",
            tool_call_id: "id-8",
            additional_kwargs: {},
            response_metadata: {},
            id: "id-10",
            type: "tool",
          },
          shared16,
          shared21,
          {
            content: "No",
            additional_kwargs: {},
            response_metadata: {
              model_provider: "openai",
              usage: {
                prompt_tokens: 142,
                completion_tokens: 1,
                total_tokens: 143,
              },
            },
            tool_call_chunks: [],
            tool_calls: [],
            id: "id-16",
            usage_metadata: {
              input_tokens: 142,
              output_tokens: 1,
              total_tokens: 143,
              input_token_details: {},
              output_token_details: {},
            },
            invalid_tool_calls: [],
            type: "ai",
          },
        ],
      },
    },
    {
      type: "STEP_FINISHED",
      stepName: "chat_node",
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hi",
        },
        {
          id: "id-4",
          role: "assistant",
          content: "Hello! How can I assist you today?",
          toolCalls: [],
        },
        shared23,
        shared17,
        shared31,
        shared30,
        shared26,
        {
          id: "id-16",
          role: "assistant",
          content: "No",
          toolCalls: [],
        },
      ],
    },
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-17",
      usage: [
        {
          provider: "openai",
          model: "gpt-4o-mini",
          inputTokens: 142,
          outputTokens: 1,
          totalTokens: 143,
        },
      ],
    },
  ],
  interactWithTheChatUsingPredefinedPromptsAndPerformSteps: [
    shared14,
    {
      type: "STEP_STARTED",
      stepName: "start_flow",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {},
    },
    shared13,
    {
      type: "STEP_FINISHED",
      stepName: "start_flow",
    },
    {
      type: "STEP_STARTED",
      stepName: "chat_node",
    },
    {
      type: "TEXT_MESSAGE_START",
      role: "assistant",
      messageId: "id-4",
    },
    shared35,
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: "ist you today?",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-4",
    },
    shared12,
    {
      type: "STEP_FINISHED",
      stepName: "chat_node",
    },
    shared22,
    shared24,
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-6",
      input: {
        threadId: "id-1",
        runId: "id-6",
        state: {
          steps: [],
          tools: [
            {
              type: "function",
              name: "generate_task_steps",
              function: {
                name: "generate_task_steps",
                description:
                  "Generates a list of steps for the user to perform",
                parameters: {
                  type: "object",
                  properties: {
                    steps: {
                      type: "array",
                      items: {
                        type: "object",
                        properties: {
                          description: {
                            type: "string",
                          },
                          status: {
                            type: "string",
                            enum: ["enabled", "disabled", "executing"],
                          },
                        },
                        required: ["description", "status"],
                      },
                    },
                  },
                  required: ["steps"],
                },
              },
            },
          ],
          messages: [
            {
              id: "id-3",
              content: "Hi",
              additional_kwargs: {},
              response_metadata: {},
              type: "human",
            },
            {
              content: "Hello! How can I assist you today?",
              additional_kwargs: {},
              response_metadata: {
                model_provider: "openai",
                usage: {
                  prompt_tokens: 58,
                  completion_tokens: 9,
                  total_tokens: 67,
                },
              },
              tool_call_chunks: [],
              tool_calls: [],
              id: "id-4",
              usage_metadata: {
                input_tokens: 58,
                output_tokens: 9,
                total_tokens: 67,
                input_token_details: {},
                output_token_details: {},
              },
              invalid_tool_calls: [],
              type: "ai",
            },
          ],
        },
        messages: [shared29],
        tools: [
          {
            name: "generate_task_steps",
            description: "Generates a list of steps for the user to perform",
            parameters: {
              type: "object",
              properties: {
                steps: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      description: {
                        type: "string",
                      },
                      status: {
                        type: "string",
                        enum: ["enabled", "disabled", "executing"],
                      },
                    },
                    required: ["description", "status"],
                  },
                },
              },
              required: ["steps"],
            },
          },
        ],
        context: [],
        forwardedProps: {},
      },
    },
    {
      type: "STEP_STARTED",
      stepName: "start_flow",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {},
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        steps: [],
        tools: [
          {
            type: "function",
            name: "generate_task_steps",
            function: {
              name: "generate_task_steps",
              description: "Generates a list of steps for the user to perform",
              parameters: {
                type: "object",
                properties: {
                  steps: {
                    type: "array",
                    items: {
                      type: "object",
                      properties: {
                        description: {
                          type: "string",
                        },
                        status: {
                          type: "string",
                          enum: ["enabled", "disabled", "executing"],
                        },
                      },
                      required: ["description", "status"],
                    },
                  },
                },
                required: ["steps"],
              },
            },
          },
        ],
        messages: [
          {
            id: "id-3",
            content: "Hi",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
          },
          {
            content: "Hello! How can I assist you today?",
            additional_kwargs: {},
            response_metadata: {
              model_provider: "openai",
              usage: {
                prompt_tokens: 58,
                completion_tokens: 9,
                total_tokens: 67,
              },
            },
            tool_call_chunks: [],
            id: "id-4",
            usage_metadata: {
              input_tokens: 58,
              output_tokens: 9,
              total_tokens: 67,
              input_token_details: {},
              output_token_details: {},
            },
            invalid_tool_calls: [],
            tool_calls: [],
            type: "ai",
          },
          {
            id: "id-7",
            content:
              "Plan a mission to Mars with the first step being Start The Planning",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
          },
        ],
      },
    },
    {
      type: "STEP_FINISHED",
      stepName: "start_flow",
    },
    {
      type: "STEP_STARTED",
      stepName: "chat_node",
    },
    shared27,
    shared28,
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: '{"steps":[{"descript',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: 'ion":"Start The Plan',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: 'ning","status":"enab',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: 'led"},{"description"',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: ':"Design spacecraft"',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: ',"status":"enabled"}',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: ',{"description":"Lau',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: 'nch mission","status',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-8",
      delta: '":"enabled"}]}',
    },
    {
      type: "TOOL_CALL_END",
      toolCallId: "id-8",
    },
    {
      type: "STEP_FINISHED",
      stepName: "chat_node",
    },
    {
      type: "STEP_STARTED",
      stepName: "process_steps_node",
    },
    {
      type: "STEP_FINISHED",
      stepName: "process_steps_node",
    },
    shared9,
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hi",
        },
        {
          id: "id-4",
          role: "assistant",
          content: "Hello! How can I assist you today?",
          toolCalls: [],
        },
        shared29,
        shared18,
        shared31,
      ],
    },
    shared19,
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-11",
      usage: [
        {
          provider: "openai",
          model: "gpt-4o-mini",
          inputTokens: 83,
          outputTokens: 49,
          totalTokens: 132,
        },
      ],
    },
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-6",
      input: {
        threadId: "id-1",
        runId: "id-6",
        state: {
          steps: [
            {
              description: "Start The Planning",
              status: "enabled",
            },
            {
              description: "Design spacecraft",
              status: "enabled",
            },
            {
              description: "Launch mission",
              status: "enabled",
            },
          ],
          tools: [
            {
              type: "function",
              name: "generate_task_steps",
              function: {
                name: "generate_task_steps",
                description:
                  "Generates a list of steps for the user to perform",
                parameters: {
                  type: "object",
                  properties: {
                    steps: {
                      type: "array",
                      items: {
                        type: "object",
                        properties: {
                          description: {
                            type: "string",
                          },
                          status: {
                            type: "string",
                            enum: ["enabled", "disabled", "executing"],
                          },
                        },
                        required: ["description", "status"],
                      },
                    },
                  },
                  required: ["steps"],
                },
              },
            },
          ],
          messages: [
            {
              id: "id-3",
              content: "Hi",
              additional_kwargs: {},
              response_metadata: {},
              type: "human",
            },
            {
              content: "Hello! How can I assist you today?",
              additional_kwargs: {},
              response_metadata: {
                model_provider: "openai",
                usage: {
                  prompt_tokens: 58,
                  completion_tokens: 9,
                  total_tokens: 67,
                },
              },
              tool_call_chunks: [],
              id: "id-4",
              usage_metadata: {
                input_tokens: 58,
                output_tokens: 9,
                total_tokens: 67,
                input_token_details: {},
                output_token_details: {},
              },
              invalid_tool_calls: [],
              tool_calls: [],
              type: "ai",
            },
            {
              id: "id-7",
              content:
                "Plan a mission to Mars with the first step being Start The Planning",
              additional_kwargs: {},
              response_metadata: {},
              type: "human",
            },
            {
              content: "",
              additional_kwargs: {
                tool_calls: [
                  {
                    index: 0,
                    id: "id-8",
                    type: "function",
                    function: {
                      name: "plan_execution_steps",
                      arguments: shared2,
                    },
                  },
                ],
              },
              response_metadata: {
                model_provider: "openai",
                usage: {
                  prompt_tokens: 83,
                  completion_tokens: 49,
                  total_tokens: 132,
                },
              },
              tool_call_chunks: [
                {
                  name: "plan_execution_steps",
                  args: shared2,
                  id: "id-8",
                  index: 0,
                  type: "tool_call_chunk",
                },
              ],
              tool_calls: [
                {
                  name: "plan_execution_steps",
                  args: {
                    steps: [
                      {
                        description: "Start The Planning",
                        status: "enabled",
                      },
                      {
                        description: "Design spacecraft",
                        status: "enabled",
                      },
                      {
                        description: "Launch mission",
                        status: "enabled",
                      },
                    ],
                  },
                  id: "id-8",
                  type: "tool_call",
                },
              ],
              id: "id-9",
              usage_metadata: {
                input_tokens: 83,
                output_tokens: 49,
                total_tokens: 132,
                input_token_details: {},
                output_token_details: {},
              },
              invalid_tool_calls: [],
              type: "ai",
            },
            {
              content: "Task steps generated.",
              tool_call_id: "id-8",
              additional_kwargs: {},
              response_metadata: {},
              id: "id-10",
              type: "tool",
            },
          ],
        },
        messages: [shared18, shared32],
        tools: [
          {
            name: "generate_task_steps",
            description: "Generates a list of steps for the user to perform",
            parameters: {
              type: "object",
              properties: {
                steps: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      description: {
                        type: "string",
                      },
                      status: {
                        type: "string",
                        enum: ["enabled", "disabled", "executing"],
                      },
                    },
                    required: ["description", "status"],
                  },
                },
              },
              required: ["steps"],
            },
          },
        ],
        context: [],
        forwardedProps: {
          command: {
            resume:
              "The user selected the following steps: Design spacecraft, Launch mission",
            interruptEvent: shared2,
          },
        },
      },
    },
    {
      type: "STEP_STARTED",
      stepName: "process_steps_node",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {},
    },
    shared9,
    {
      type: "TEXT_MESSAGE_START",
      role: "assistant",
      messageId: "id-12",
    },
    shared33,
    shared34,
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-12",
      delta: "at?",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-12",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: shared7,
    },
    {
      type: "STEP_FINISHED",
      stepName: "process_steps_node",
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hi",
        },
        {
          id: "id-4",
          role: "assistant",
          content: "Hello! How can I assist you today?",
          toolCalls: [],
        },
        shared29,
        shared18,
        shared31,
        shared30,
      ],
    },
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-13",
      usage: [
        {
          provider: "openai",
          model: "gpt-4o",
          inputTokens: 141,
          outputTokens: 11,
          totalTokens: 152,
        },
      ],
    },
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-14",
      input: {
        threadId: "id-1",
        runId: "id-14",
        state: shared7,
        messages: [shared25],
        tools: [
          {
            name: "generate_task_steps",
            description: "Generates a list of steps for the user to perform",
            parameters: {
              type: "object",
              properties: {
                steps: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      description: {
                        type: "string",
                      },
                      status: {
                        type: "string",
                        enum: ["enabled", "disabled", "executing"],
                      },
                    },
                    required: ["description", "status"],
                  },
                },
              },
              required: ["steps"],
            },
          },
        ],
        context: [],
        forwardedProps: {},
      },
    },
    {
      type: "STEP_STARTED",
      stepName: "start_flow",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {},
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        steps: [
          {
            description: "Start The Planning",
            status: "enabled",
          },
          {
            description: "Design spacecraft",
            status: "enabled",
          },
          {
            description: "Launch mission",
            status: "enabled",
          },
        ],
        tools: [
          {
            type: "function",
            name: "generate_task_steps",
            function: {
              name: "generate_task_steps",
              description: "Generates a list of steps for the user to perform",
              parameters: {
                type: "object",
                properties: {
                  steps: {
                    type: "array",
                    items: {
                      type: "object",
                      properties: {
                        description: {
                          type: "string",
                        },
                        status: {
                          type: "string",
                          enum: ["enabled", "disabled", "executing"],
                        },
                      },
                      required: ["description", "status"],
                    },
                  },
                },
                required: ["steps"],
              },
            },
          },
        ],
        messages: [
          {
            id: "id-3",
            content: "Hi",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
          },
          {
            content: "Hello! How can I assist you today?",
            additional_kwargs: {},
            response_metadata: {
              model_provider: "openai",
              usage: {
                prompt_tokens: 58,
                completion_tokens: 9,
                total_tokens: 67,
              },
            },
            tool_call_chunks: [],
            id: "id-4",
            usage_metadata: {
              input_tokens: 58,
              output_tokens: 9,
              total_tokens: 67,
              input_token_details: {},
              output_token_details: {},
            },
            invalid_tool_calls: [],
            tool_calls: [],
            type: "ai",
          },
          {
            id: "id-7",
            content:
              "Plan a mission to Mars with the first step being Start The Planning",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
          },
          shared11,
          {
            content: "Task steps generated.",
            tool_call_id: "id-8",
            additional_kwargs: {},
            response_metadata: {},
            id: "id-10",
            type: "tool",
          },
          shared15,
          shared20,
        ],
      },
    },
    {
      type: "STEP_FINISHED",
      stepName: "start_flow",
    },
    {
      type: "STEP_STARTED",
      stepName: "chat_node",
    },
    shared27,
    {
      type: "TOOL_CALL_START",
      toolCallId: "id-16",
      toolCallName: "plan_execution_steps",
      parentMessageId: "id-17",
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-16",
      delta: '{"steps":[{"descript',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-16",
      delta: 'ion":"Start The Plan',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-16",
      delta: 'ning","status":"enab',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-16",
      delta: 'led"},{"description"',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-16",
      delta: ':"Design spacecraft"',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-16",
      delta: ',"status":"enabled"}',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-16",
      delta: ',{"description":"Lau',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-16",
      delta: 'nch mission","status',
    },
    {
      type: "TOOL_CALL_ARGS",
      toolCallId: "id-16",
      delta: '":"enabled"}]}',
    },
    {
      type: "TOOL_CALL_END",
      toolCallId: "id-16",
    },
    {
      type: "STEP_FINISHED",
      stepName: "chat_node",
    },
    {
      type: "STEP_STARTED",
      stepName: "process_steps_node",
    },
    {
      type: "STEP_FINISHED",
      stepName: "process_steps_node",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        steps: [
          {
            description: "Start The Planning",
            status: "enabled",
          },
          {
            description: "Design spacecraft",
            status: "enabled",
          },
          {
            description: "Launch mission",
            status: "enabled",
          },
        ],
        tools: [
          {
            type: "function",
            name: "generate_task_steps",
            function: {
              name: "generate_task_steps",
              description: "Generates a list of steps for the user to perform",
              parameters: {
                type: "object",
                properties: {
                  steps: {
                    type: "array",
                    items: {
                      type: "object",
                      properties: {
                        description: {
                          type: "string",
                        },
                        status: {
                          type: "string",
                          enum: ["enabled", "disabled", "executing"],
                        },
                      },
                      required: ["description", "status"],
                    },
                  },
                },
                required: ["steps"],
              },
            },
          },
        ],
        messages: [
          {
            id: "id-3",
            content: "Hi",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
          },
          {
            content: "Hello! How can I assist you today?",
            additional_kwargs: {},
            response_metadata: {
              model_provider: "openai",
              usage: {
                prompt_tokens: 58,
                completion_tokens: 9,
                total_tokens: 67,
              },
            },
            tool_call_chunks: [],
            id: "id-4",
            usage_metadata: {
              input_tokens: 58,
              output_tokens: 9,
              total_tokens: 67,
              input_token_details: {},
              output_token_details: {},
            },
            invalid_tool_calls: [],
            tool_calls: [],
            type: "ai",
          },
          {
            id: "id-7",
            content:
              "Plan a mission to Mars with the first step being Start The Planning",
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
          },
          shared11,
          {
            content: "Task steps generated.",
            tool_call_id: "id-8",
            additional_kwargs: {},
            response_metadata: {},
            id: "id-10",
            type: "tool",
          },
          shared15,
          shared20,
          {
            content: "",
            additional_kwargs: {
              tool_calls: [
                {
                  index: 0,
                  id: "id-16",
                  type: "function",
                  function: {
                    name: "plan_execution_steps",
                    arguments: shared2,
                  },
                },
              ],
            },
            response_metadata: {
              model_provider: "openai",
              usage: {
                prompt_tokens: 128,
                completion_tokens: 49,
                total_tokens: 177,
              },
            },
            tool_call_chunks: [
              {
                name: "plan_execution_steps",
                args: shared2,
                id: "id-16",
                index: 0,
                type: "tool_call_chunk",
              },
            ],
            tool_calls: [
              {
                name: "plan_execution_steps",
                args: {
                  steps: [
                    {
                      description: "Start The Planning",
                      status: "enabled",
                    },
                    {
                      description: "Design spacecraft",
                      status: "enabled",
                    },
                    {
                      description: "Launch mission",
                      status: "enabled",
                    },
                  ],
                },
                id: "id-16",
                type: "tool_call",
              },
            ],
            id: "id-17",
            usage_metadata: {
              input_tokens: 128,
              output_tokens: 49,
              total_tokens: 177,
              input_token_details: {},
              output_token_details: {},
            },
            invalid_tool_calls: [],
            type: "ai",
          },
          {
            content: "Task steps generated.",
            tool_call_id: "id-16",
            additional_kwargs: {},
            response_metadata: {},
            id: "id-18",
            type: "tool",
          },
        ],
      },
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hi",
        },
        {
          id: "id-4",
          role: "assistant",
          content: "Hello! How can I assist you today?",
          toolCalls: [],
        },
        shared29,
        shared18,
        shared31,
        shared30,
        shared25,
        {
          id: "id-17",
          role: "assistant",
          content: "",
          toolCalls: [
            {
              id: "id-16",
              type: "function",
              function: {
                name: "plan_execution_steps",
                arguments: shared2,
              },
            },
          ],
        },
        {
          id: "id-18",
          role: "tool",
          content: "Task steps generated.",
          toolCallId: "id-16",
        },
      ],
    },
    shared19,
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-19",
      usage: [
        {
          provider: "openai",
          model: "gpt-4o-mini",
          inputTokens: 128,
          outputTokens: 49,
          totalTokens: 177,
        },
      ],
    },
  ],
});
