import { defineEventTrace } from "../../event-trace-test";

// Generated by the event trace updater.
// Reason: Native Python raw V3 capture audited against forced-V2 references after tool-result recovery. Native task/checkpoint channels are unavailable at the pinned runtime: no synthetic step events; final business state, messages and tool payloads verified. Native message metadata and legacy callback timing differ. Unexecuted journeys preserved.
// Before accepting changes, verify whether the implementation regressed.
const shared1 =
  '{"document":"Once upon a time, in a land far away, there lived a magnificent dragon named Atlantis. Atlantis was known throughout the realm for its shimmering scales that reflected the light of a thousand stars. The dragon Atlantis would soar above the mountains, breathing fire that lit up the night sky. Villagers would gather to watch Atlantis perform its aerial dances, marveling at the grace of this ancient creature."}' as const;
const shared2 =
  "Once upon a time, in a land far away, there lived a magnificent dragon named AtlantisLola. AtlantisLola was known throughout the realm for its shimmering scales that reflected the light of a thousand stars. The dragon AtlantisLola would soar above the mountains, breathing fire that lit up the night sky. Villagers would gather to watch AtlantisLola perform its aerial dances, marveling at the grace of this ancient creature." as const;
const shared3 =
  '{"document":"Once upon a time, in a land far away, there lived a magnificent dragon named Lola. Lola was known throughout the realm for its shimmering scales that reflected the light of a thousand stars. The dragon Lola would soar above the mountains, breathing fire that lit up the night sky. Villagers would gather to watch Lola perform its aerial dances, marveling at the grace of this ancient creature."}' as const;
const shared4 =
  "Once upon a time, in a land far away, there lived a magnificent dragon named Atlantis. Atlantis was known throughout the realm for its shimmering scales that reflected the light of a thousand stars. The dragon Atlantis would soar above the mountains, breathing fire that lit up the night sky. Villagers would gather to watch Atlantis perform its aerial dances, marveling at the grace of this ancient creature." as const;
const shared5 =
  "Once upon a time, in a land far away, there lived a magnificent dragon named Lola. Lola was known throughout the realm for its shimmering scales that reflected the light of a thousand stars. The dragon Lola would soar above the mountains, breathing fire that lit up the night sky. Villagers would gather to watch Lola perform its aerial dances, marveling at the grace of this ancient creature." as const;
const shared6 = {
  type: "STATE_SNAPSHOT",
  snapshot: {
    messages: [
      {
        content: "Give me a story for a dragon called Atlantis in document",
        additional_kwargs: {
          type: "human",
        },
        response_metadata: {},
        type: "human",
        name: null,
        id: "id-3",
      },
      {
        content: "",
        additional_kwargs: {
          invalid_tool_calls: [],
          usage_metadata: null,
        },
        response_metadata: {
          model_provider: "openai",
          finish_reason: "tool_calls",
          model_name: "gpt-4.1-mini",
        },
        type: "ai",
        name: null,
        id: "id-5",
        tool_calls: [
          {
            name: "write_document_local",
            args: {
              document: shared4,
            },
            id: "id-4",
            type: "tool_call",
          },
        ],
        invalid_tool_calls: [],
        usage_metadata: null,
      },
      {
        content: "Document written.",
        additional_kwargs: {},
        response_metadata: {},
        type: "tool",
        name: null,
        id: "id-7",
        tool_call_id: "id-4",
        artifact: null,
        status: "success",
      },
      {
        content: "",
        additional_kwargs: {
          invalid_tool_calls: [],
          usage_metadata: null,
        },
        response_metadata: {},
        type: "ai",
        name: null,
        id: "id-8",
        tool_calls: [
          {
            name: "confirm_changes",
            args: {},
            id: "id-9",
            type: "tool_call",
          },
        ],
        invalid_tool_calls: [],
        usage_metadata: null,
      },
      {
        content: '{"accepted":true}',
        additional_kwargs: {
          type: "tool",
        },
        response_metadata: {},
        type: "tool",
        name: null,
        id: "id-12",
        tool_call_id: "id-9",
        artifact: null,
        status: "success",
      },
      {
        content: "Done! I've completed that for you.",
        additional_kwargs: {
          invalid_tool_calls: [],
          usage_metadata: null,
        },
        response_metadata: {
          model_provider: "openai",
          finish_reason: "stop",
          model_name: "gpt-4.1-mini",
        },
        type: "ai",
        name: null,
        id: "id-13",
        tool_calls: [],
        invalid_tool_calls: [],
        usage_metadata: null,
      },
      {
        content: "Change dragon name to Lola",
        additional_kwargs: {
          type: "human",
        },
        response_metadata: {},
        type: "human",
        name: null,
        id: "id-16",
      },
      {
        content: "",
        additional_kwargs: {
          tool_calls: [
            {
              index: 0,
              id: "id-17",
              type: "function",
              function: {
                name: "write_document_local",
                arguments: shared3,
              },
            },
          ],
        },
        response_metadata: {
          model_provider: "openai",
          usage: {},
        },
        type: "ai",
        name: null,
        id: "id-18",
        tool_calls: [
          {
            name: "write_document_local",
            args: {
              document: shared5,
            },
            id: "id-17",
            type: "tool_call",
          },
        ],
        invalid_tool_calls: [],
        usage_metadata: null,
        tool_call_chunks: [
          {
            name: "write_document_local",
            args: shared3,
            id: "id-17",
            index: 0,
            type: "tool_call_chunk",
          },
        ],
      },
      {
        content: "Document written.",
        additional_kwargs: {},
        response_metadata: {},
        type: "tool",
        name: null,
        id: "id-20",
        tool_call_id: "id-17",
        artifact: null,
        status: "success",
      },
      {
        content: "",
        additional_kwargs: {},
        response_metadata: {},
        type: "ai",
        name: null,
        id: "id-21",
        tool_calls: [
          {
            name: "confirm_changes",
            args: {},
            id: "id-22",
            type: "tool_call",
          },
        ],
        invalid_tool_calls: [],
        usage_metadata: null,
      },
    ],
    document: shared5,
    tools: [
      {
        type: "function",
        name: "confirm_changes",
        function: {
          name: "confirm_changes",
          description: "",
          parameters: {
            type: "object",
            properties: {},
          },
        },
      },
      {
        type: "function",
        name: "write_document",
        function: {
          name: "write_document",
          description: "Present the proposed changes to the user for review",
          parameters: {
            type: "object",
            properties: {
              document: {
                type: "string",
                description: "The full updated document in markdown format",
              },
            },
            required: ["document"],
          },
        },
      },
    ],
  },
} as const;
const shared7 = {
  type: "RUN_STARTED",
  threadId: "id-1",
  runId: "id-15",
  protocolVersion: "1.0",
  input: {
    threadId: "id-1",
    runId: "id-15",
    protocolVersion: "1.0",
    state: {
      messages: [
        {
          content: "Give me a story for a dragon called Atlantis in document",
          additional_kwargs: {
            type: "human",
          },
          response_metadata: {},
          type: "human",
          name: null,
          id: "id-3",
        },
        {
          content: "",
          additional_kwargs: {
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          response_metadata: {
            model_provider: "openai",
            finish_reason: "tool_calls",
            model_name: "gpt-4.1-mini",
          },
          type: "ai",
          name: null,
          id: "id-5",
          tool_calls: [
            {
              name: "write_document_local",
              args: {
                document: shared4,
              },
              id: "id-4",
              type: "tool_call",
            },
          ],
          invalid_tool_calls: [],
          usage_metadata: null,
        },
        {
          content: "Document written.",
          additional_kwargs: {},
          response_metadata: {},
          type: "tool",
          name: null,
          id: "id-7",
          tool_call_id: "id-4",
          artifact: null,
          status: "success",
        },
        {
          content: "",
          additional_kwargs: {
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          response_metadata: {},
          type: "ai",
          name: null,
          id: "id-8",
          tool_calls: [
            {
              name: "confirm_changes",
              args: {},
              id: "id-9",
              type: "tool_call",
            },
          ],
          invalid_tool_calls: [],
          usage_metadata: null,
        },
        {
          content: '{"accepted":true}',
          additional_kwargs: {
            type: "tool",
          },
          response_metadata: {},
          type: "tool",
          name: null,
          id: "id-12",
          tool_call_id: "id-9",
          artifact: null,
          status: "success",
        },
        {
          content: "Done! I've completed that for you.",
          additional_kwargs: {},
          response_metadata: {
            model_provider: "openai",
            usage: {},
          },
          type: "ai",
          name: null,
          id: "id-13",
          tool_calls: [],
          invalid_tool_calls: [],
          usage_metadata: null,
          tool_call_chunks: [],
        },
      ],
      document: shared4,
      tools: [
        {
          type: "function",
          name: "confirm_changes",
          function: {
            name: "confirm_changes",
            description: "",
            parameters: {
              type: "object",
              properties: {},
            },
          },
        },
        {
          type: "function",
          name: "write_document",
          function: {
            name: "write_document",
            description: "Present the proposed changes to the user for review",
            parameters: {
              type: "object",
              properties: {
                document: {
                  type: "string",
                  description: "The full updated document in markdown format",
                },
              },
              required: ["document"],
            },
          },
        },
      ],
    },
    messages: [
      {
        id: "id-16",
        role: "user",
        content: "Change dragon name to Lola",
      },
    ],
    tools: [
      {
        name: "confirm_changes",
        description: "",
        parameters: {
          type: "object",
          properties: {},
        },
      },
      {
        name: "write_document",
        description: "Present the proposed changes to the user for review",
        parameters: {
          type: "object",
          properties: {
            document: {
              type: "string",
              description: "The full updated document in markdown format",
            },
          },
          required: ["document"],
        },
      },
    ],
    context: [],
    forwardedProps: {},
  },
} as const;
const shared8 = {
  type: "STATE_SNAPSHOT",
  snapshot: {
    messages: [
      {
        content: "Give me a story for a dragon called Atlantis in document",
        additional_kwargs: {
          type: "human",
        },
        response_metadata: {},
        type: "human",
        name: null,
        id: "id-3",
      },
      {
        content: "",
        additional_kwargs: {
          tool_calls: [
            {
              index: 0,
              id: "id-4",
              type: "function",
              function: {
                name: "write_document_local",
                arguments: shared1,
              },
            },
          ],
        },
        response_metadata: {
          model_provider: "openai",
          usage: {},
        },
        type: "ai",
        name: null,
        id: "id-5",
        tool_calls: [
          {
            name: "write_document_local",
            args: {
              document: shared4,
            },
            id: "id-4",
            type: "tool_call",
          },
        ],
        invalid_tool_calls: [],
        usage_metadata: null,
        tool_call_chunks: [
          {
            name: "write_document_local",
            args: shared1,
            id: "id-4",
            index: 0,
            type: "tool_call_chunk",
          },
        ],
      },
      {
        content: "Document written.",
        additional_kwargs: {},
        response_metadata: {},
        type: "tool",
        name: null,
        id: "id-7",
        tool_call_id: "id-4",
        artifact: null,
        status: "success",
      },
      {
        content: "",
        additional_kwargs: {},
        response_metadata: {},
        type: "ai",
        name: null,
        id: "id-8",
        tool_calls: [
          {
            name: "confirm_changes",
            args: {},
            id: "id-9",
            type: "tool_call",
          },
        ],
        invalid_tool_calls: [],
        usage_metadata: null,
      },
    ],
    document: shared4,
    tools: [
      {
        type: "function",
        name: "confirm_changes",
        function: {
          name: "confirm_changes",
          description: "",
          parameters: {
            type: "object",
            properties: {},
          },
        },
      },
      {
        type: "function",
        name: "write_document",
        function: {
          name: "write_document",
          description: "Present the proposed changes to the user for review",
          parameters: {
            type: "object",
            properties: {
              document: {
                type: "string",
                description: "The full updated document in markdown format",
              },
            },
            required: ["document"],
          },
        },
      },
    ],
  },
} as const;
const shared9 = {
  type: "STATE_SNAPSHOT",
  snapshot: {
    messages: [
      {
        content: "Give me a story for a dragon called Atlantis in document",
        additional_kwargs: {
          type: "human",
        },
        response_metadata: {},
        type: "human",
        name: null,
        id: "id-3",
      },
      {
        content: "",
        additional_kwargs: {
          invalid_tool_calls: [],
          usage_metadata: null,
        },
        response_metadata: {
          model_provider: "openai",
          finish_reason: "tool_calls",
          model_name: "gpt-4.1-mini",
        },
        type: "ai",
        name: null,
        id: "id-5",
        tool_calls: [
          {
            name: "write_document_local",
            args: {
              document: shared4,
            },
            id: "id-4",
            type: "tool_call",
          },
        ],
        invalid_tool_calls: [],
        usage_metadata: null,
      },
      {
        content: "Document written.",
        additional_kwargs: {},
        response_metadata: {},
        type: "tool",
        name: null,
        id: "id-7",
        tool_call_id: "id-4",
        artifact: null,
        status: "success",
      },
      {
        content: "",
        additional_kwargs: {
          invalid_tool_calls: [],
          usage_metadata: null,
        },
        response_metadata: {},
        type: "ai",
        name: null,
        id: "id-8",
        tool_calls: [
          {
            name: "confirm_changes",
            args: {},
            id: "id-9",
            type: "tool_call",
          },
        ],
        invalid_tool_calls: [],
        usage_metadata: null,
      },
      {
        content: '{"accepted":true}',
        additional_kwargs: {
          type: "tool",
        },
        response_metadata: {},
        type: "tool",
        name: null,
        id: "id-12",
        tool_call_id: "id-9",
        artifact: null,
        status: "success",
      },
      {
        content: "Done! I've completed that for you.",
        additional_kwargs: {},
        response_metadata: {
          model_provider: "openai",
          usage: {},
        },
        type: "ai",
        name: null,
        id: "id-13",
        tool_calls: [],
        invalid_tool_calls: [],
        usage_metadata: null,
        tool_call_chunks: [],
      },
    ],
    document: shared4,
    tools: [
      {
        type: "function",
        name: "confirm_changes",
        function: {
          name: "confirm_changes",
          description: "",
          parameters: {
            type: "object",
            properties: {},
          },
        },
      },
      {
        type: "function",
        name: "write_document",
        function: {
          name: "write_document",
          description: "Present the proposed changes to the user for review",
          parameters: {
            type: "object",
            properties: {
              document: {
                type: "string",
                description: "The full updated document in markdown format",
              },
            },
            required: ["document"],
          },
        },
      },
    ],
  },
} as const;
const shared10 = {
  type: "MESSAGES_SNAPSHOT",
  messages: [
    {
      id: "id-3",
      role: "user",
      content: "Give me a story for a dragon called Atlantis in document",
    },
    {
      id: "id-5",
      role: "assistant",
      content: "",
      toolCalls: [
        {
          id: "id-4",
          type: "function",
          function: {
            name: "write_document_local",
            arguments: shared1,
          },
        },
      ],
    },
    {
      id: "id-7",
      role: "tool",
      content: "Document written.",
      toolCallId: "id-4",
    },
    {
      id: "id-8",
      role: "assistant",
      content: "",
      toolCalls: [
        {
          id: "id-9",
          type: "function",
          function: {
            name: "confirm_changes",
            arguments: "{}",
          },
        },
      ],
    },
    {
      id: "id-12",
      role: "tool",
      content: '{"accepted":true}',
      toolCallId: "id-9",
    },
    {
      id: "id-13",
      role: "assistant",
      content: "Done! I've completed that for you.",
      toolCalls: [],
    },
    {
      id: "id-16",
      role: "user",
      content: "Change dragon name to Lola",
    },
    {
      id: "id-18",
      role: "assistant",
      content: "",
      toolCalls: [
        {
          id: "id-17",
          type: "function",
          function: {
            name: "write_document_local",
            arguments: shared3,
          },
        },
      ],
    },
    {
      id: "id-20",
      role: "tool",
      content: "Document written.",
      toolCallId: "id-17",
    },
    {
      id: "id-21",
      role: "assistant",
      content: "",
      toolCalls: [
        {
          id: "id-22",
          type: "function",
          function: {
            name: "confirm_changes",
            arguments: "{}",
          },
        },
      ],
    },
  ],
} as const;
const shared11 = {
  type: "RUN_STARTED",
  threadId: "id-1",
  runId: "id-11",
  protocolVersion: "1.0",
  input: {
    threadId: "id-1",
    runId: "id-11",
    protocolVersion: "1.0",
    state: {
      document: shared4,
    },
    messages: [
      {
        id: "id-5",
        role: "assistant",
        content: "",
        toolCalls: [
          {
            id: "id-4",
            type: "function",
            function: {
              name: "write_document_local",
              arguments: shared1,
            },
          },
        ],
      },
      {
        id: "id-7",
        role: "tool",
        content: "Document written.",
        toolCallId: "id-4",
      },
      {
        id: "id-8",
        role: "assistant",
        content: "",
        toolCalls: [
          {
            id: "id-9",
            type: "function",
            function: {
              name: "confirm_changes",
              arguments: "{}",
            },
          },
        ],
      },
      {
        id: "id-12",
        role: "tool",
        content: '{"accepted":true}',
        toolCallId: "id-9",
      },
    ],
    tools: [
      {
        name: "confirm_changes",
        description: "",
        parameters: {
          type: "object",
          properties: {},
        },
      },
      {
        name: "write_document",
        description: "Present the proposed changes to the user for review",
        parameters: {
          type: "object",
          properties: {
            document: {
              type: "string",
              description: "The full updated document in markdown format",
            },
          },
          required: ["document"],
        },
      },
    ],
    context: [],
    forwardedProps: {},
  },
} as const;
const shared12 = {
  type: "MESSAGES_SNAPSHOT",
  messages: [
    {
      id: "id-3",
      role: "user",
      content: "Give me a story for a dragon called Atlantis in document",
    },
    {
      id: "id-5",
      role: "assistant",
      content: "",
      toolCalls: [
        {
          id: "id-4",
          type: "function",
          function: {
            name: "write_document_local",
            arguments: shared1,
          },
        },
      ],
    },
    {
      id: "id-7",
      role: "tool",
      content: "Document written.",
      toolCallId: "id-4",
    },
    {
      id: "id-8",
      role: "assistant",
      content: "",
      toolCalls: [
        {
          id: "id-9",
          type: "function",
          function: {
            name: "confirm_changes",
            arguments: "{}",
          },
        },
      ],
    },
    {
      id: "id-12",
      role: "tool",
      content: '{"accepted":true}',
      toolCallId: "id-9",
    },
    {
      id: "id-13",
      role: "assistant",
      content: "Done! I've completed that for you.",
      toolCalls: [],
    },
  ],
} as const;
const shared13 = {
  type: "MESSAGES_SNAPSHOT",
  messages: [
    {
      id: "id-3",
      role: "user",
      content: "Give me a story for a dragon called Atlantis in document",
    },
    {
      id: "id-5",
      role: "assistant",
      content: "",
      toolCalls: [
        {
          id: "id-4",
          type: "function",
          function: {
            name: "write_document_local",
            arguments: shared1,
          },
        },
      ],
    },
    {
      id: "id-7",
      role: "tool",
      content: "Document written.",
      toolCallId: "id-4",
    },
    {
      id: "id-8",
      role: "assistant",
      content: "",
      toolCalls: [
        {
          id: "id-9",
          type: "function",
          function: {
            name: "confirm_changes",
            arguments: "{}",
          },
        },
      ],
    },
  ],
} as const;
const shared14 = {
  content: "",
  additional_kwargs: {
    invalid_tool_calls: [],
    usage_metadata: null,
  },
  response_metadata: {
    model_provider: "openai",
    finish_reason: "tool_calls",
    model_name: "gpt-4.1-mini",
  },
  type: "ai",
  name: null,
  id: "id-18",
  tool_calls: [
    {
      name: "write_document_local",
      args: {
        document: shared5,
      },
      id: "id-17",
      type: "tool_call",
    },
  ],
  invalid_tool_calls: [],
  usage_metadata: null,
} as const;
const shared15 = {
  type: "RUN_STARTED",
  threadId: "id-1",
  runId: "id-2",
  protocolVersion: "1.0",
  input: {
    threadId: "id-1",
    runId: "id-2",
    protocolVersion: "1.0",
    state: {},
    messages: [
      {
        id: "id-3",
        role: "user",
        content: "Give me a story for a dragon called Atlantis in document",
      },
    ],
    tools: [
      {
        name: "confirm_changes",
        description: "",
        parameters: {
          type: "object",
          properties: {},
        },
      },
      {
        name: "write_document",
        description: "Present the proposed changes to the user for review",
        parameters: {
          type: "object",
          properties: {
            document: {
              type: "string",
              description: "The full updated document in markdown format",
            },
          },
          required: ["document"],
        },
      },
    ],
    context: [],
    forwardedProps: {},
  },
} as const;
const shared16 = {
  document: shared2,
} as const;
const shared17 = {
  content: "",
  additional_kwargs: {
    invalid_tool_calls: [],
    usage_metadata: null,
  },
  response_metadata: {},
  type: "ai",
  name: null,
  id: "id-21",
  tool_calls: [
    {
      name: "confirm_changes",
      args: {},
      id: "id-22",
      type: "tool_call",
    },
  ],
  invalid_tool_calls: [],
  usage_metadata: null,
} as const;
const shared18 = {
  content: "Done! I've completed that for you.",
  additional_kwargs: {},
  response_metadata: {
    model_provider: "openai",
    usage: {},
  },
  type: "ai",
  name: null,
  id: "id-26",
  tool_calls: [],
  invalid_tool_calls: [],
  usage_metadata: null,
  tool_call_chunks: [],
} as const;
const shared19 = {
  type: "TOOL_CALL_RESULT",
  messageId: "id-19",
  toolCallId: "id-17",
  content: "Document written.",
  role: "tool",
} as const;
const shared20 = {
  type: "TOOL_CALL_START",
  toolCallId: "id-17",
  toolCallName: "write_document_local",
  parentMessageId: "id-18",
} as const;
const shared21 = {
  type: "TOOL_CALL_RESULT",
  messageId: "id-6",
  toolCallId: "id-4",
  content: "Document written.",
  role: "tool",
} as const;
const shared22 = {
  type: "TOOL_CALL_START",
  toolCallId: "id-4",
  toolCallName: "write_document_local",
  parentMessageId: "id-5",
} as const;
const shared23 = {
  id: "id-26",
  role: "assistant",
  content: "Done! I've completed that for you.",
  toolCalls: [],
} as const;
const shared24 = {
  id: "id-25",
  role: "tool",
  content: '{"accepted":false}',
  toolCallId: "id-22",
} as const;
const shared25 = {
  type: "TEXT_MESSAGE_CONTENT",
  messageId: "id-13",
  delta: "Done! I've completed",
} as const;
const shared26 = {
  type: "TEXT_MESSAGE_CONTENT",
  messageId: "id-26",
  delta: "Done! I've completed",
} as const;
const shared27 = {
  id: "id-25",
  role: "tool",
  content: '{"accepted":true}',
  toolCallId: "id-22",
} as const;

export const predictiveStateUpdatePageEventTrace = defineEventTrace(
  import.meta.url,
  {
    interactWithAgentAndApproveAskedChanges: [
      shared15,
      shared22,
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: '{"document":"Once up',
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "on a time, in a land",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: " far away, there liv",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "ed a magnificent dra",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "gon named Atlantis. ",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "Atlantis was known t",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "hroughout the realm ",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "for its shimmering s",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "cales that reflected",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: " the light of a thou",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "sand stars. The drag",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "on Atlantis would so",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "ar above the mountai",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "ns, breathing fire t",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "hat lit up the night",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: " sky. Villagers woul",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "d gather to watch At",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "lantis perform its a",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "erial dances, marvel",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "ing at the grace of ",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "this ancient creatur",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: 'e."}',
      },
      {
        type: "TOOL_CALL_END",
        toolCallId: "id-4",
      },
      shared21,
      shared8,
      shared13,
      {
        type: "RUN_FINISHED",
        threadId: "id-1",
        runId: "id-10",
      },
      shared11,
      {
        type: "TEXT_MESSAGE_START",
        messageId: "id-13",
        role: "assistant",
      },
      shared25,
      {
        type: "TEXT_MESSAGE_CONTENT",
        messageId: "id-13",
        delta: " that for you.",
      },
      {
        type: "TEXT_MESSAGE_END",
        messageId: "id-13",
      },
      shared9,
      shared12,
      {
        type: "RUN_FINISHED",
        threadId: "id-1",
        runId: "id-14",
      },
      shared7,
      shared20,
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: '{"document":"Once up',
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: "on a time, in a land",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: " far away, there liv",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: "ed a magnificent dra",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: "gon named Lola. Lola",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: " was known throughou",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: "t the realm for its ",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: "shimmering scales th",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: "at reflected the lig",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: "ht of a thousand sta",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: "rs. The dragon Lola ",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: "would soar above the",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: " mountains, breathin",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: "g fire that lit up t",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: "he night sky. Villag",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: "ers would gather to ",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: "watch Lola perform i",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: "ts aerial dances, ma",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: "rveling at the grace",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: " of this ancient cre",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: 'ature."}',
      },
      {
        type: "TOOL_CALL_END",
        toolCallId: "id-17",
      },
      shared19,
      shared6,
      shared10,
      {
        type: "RUN_FINISHED",
        threadId: "id-1",
        runId: "id-23",
      },
      {
        type: "RUN_STARTED",
        threadId: "id-1",
        runId: "id-24",
        protocolVersion: "1.0",
        input: {
          threadId: "id-1",
          runId: "id-24",
          protocolVersion: "1.0",
          state: shared16,
          messages: [
            {
              id: "id-18",
              role: "assistant",
              content: "",
              toolCalls: [
                {
                  id: "id-17",
                  type: "function",
                  function: {
                    name: "write_document_local",
                    arguments: shared3,
                  },
                },
              ],
            },
            {
              id: "id-20",
              role: "tool",
              content: "Document written.",
              toolCallId: "id-17",
            },
            {
              id: "id-21",
              role: "assistant",
              content: "",
              toolCalls: [
                {
                  id: "id-22",
                  type: "function",
                  function: {
                    name: "confirm_changes",
                    arguments: "{}",
                  },
                },
              ],
            },
            shared27,
          ],
          tools: [
            {
              name: "confirm_changes",
              description: "",
              parameters: {
                type: "object",
                properties: {},
              },
            },
            {
              name: "write_document",
              description:
                "Present the proposed changes to the user for review",
              parameters: {
                type: "object",
                properties: {
                  document: {
                    type: "string",
                    description: "The full updated document in markdown format",
                  },
                },
                required: ["document"],
              },
            },
          ],
          context: [],
          forwardedProps: {},
        },
      },
      {
        type: "TEXT_MESSAGE_START",
        messageId: "id-26",
        role: "assistant",
      },
      shared26,
      {
        type: "TEXT_MESSAGE_CONTENT",
        messageId: "id-26",
        delta: " that for you.",
      },
      {
        type: "TEXT_MESSAGE_END",
        messageId: "id-26",
      },
      {
        type: "STATE_SNAPSHOT",
        snapshot: {
          messages: [
            {
              content:
                "Give me a story for a dragon called Atlantis in document",
              additional_kwargs: {
                type: "human",
              },
              response_metadata: {},
              type: "human",
              name: null,
              id: "id-3",
            },
            {
              content: "",
              additional_kwargs: {
                invalid_tool_calls: [],
                usage_metadata: null,
              },
              response_metadata: {
                model_provider: "openai",
                finish_reason: "tool_calls",
                model_name: "gpt-4.1-mini",
              },
              type: "ai",
              name: null,
              id: "id-5",
              tool_calls: [
                {
                  name: "write_document_local",
                  args: {
                    document: shared4,
                  },
                  id: "id-4",
                  type: "tool_call",
                },
              ],
              invalid_tool_calls: [],
              usage_metadata: null,
            },
            {
              content: "Document written.",
              additional_kwargs: {},
              response_metadata: {},
              type: "tool",
              name: null,
              id: "id-7",
              tool_call_id: "id-4",
              artifact: null,
              status: "success",
            },
            {
              content: "",
              additional_kwargs: {
                invalid_tool_calls: [],
                usage_metadata: null,
              },
              response_metadata: {},
              type: "ai",
              name: null,
              id: "id-8",
              tool_calls: [
                {
                  name: "confirm_changes",
                  args: {},
                  id: "id-9",
                  type: "tool_call",
                },
              ],
              invalid_tool_calls: [],
              usage_metadata: null,
            },
            {
              content: '{"accepted":true}',
              additional_kwargs: {
                type: "tool",
              },
              response_metadata: {},
              type: "tool",
              name: null,
              id: "id-12",
              tool_call_id: "id-9",
              artifact: null,
              status: "success",
            },
            {
              content: "Done! I've completed that for you.",
              additional_kwargs: {
                invalid_tool_calls: [],
                usage_metadata: null,
              },
              response_metadata: {
                model_provider: "openai",
                finish_reason: "stop",
                model_name: "gpt-4.1-mini",
              },
              type: "ai",
              name: null,
              id: "id-13",
              tool_calls: [],
              invalid_tool_calls: [],
              usage_metadata: null,
            },
            {
              content: "Change dragon name to Lola",
              additional_kwargs: {
                type: "human",
              },
              response_metadata: {},
              type: "human",
              name: null,
              id: "id-16",
            },
            shared14,
            {
              content: "Document written.",
              additional_kwargs: {},
              response_metadata: {},
              type: "tool",
              name: null,
              id: "id-20",
              tool_call_id: "id-17",
              artifact: null,
              status: "success",
            },
            shared17,
            {
              content: '{"accepted":true}',
              additional_kwargs: {
                type: "tool",
              },
              response_metadata: {},
              type: "tool",
              name: null,
              id: "id-25",
              tool_call_id: "id-22",
              artifact: null,
              status: "success",
            },
            shared18,
          ],
          document: shared2,
          tools: [
            {
              type: "function",
              name: "confirm_changes",
              function: {
                name: "confirm_changes",
                description: "",
                parameters: {
                  type: "object",
                  properties: {},
                },
              },
            },
            {
              type: "function",
              name: "write_document",
              function: {
                name: "write_document",
                description:
                  "Present the proposed changes to the user for review",
                parameters: {
                  type: "object",
                  properties: {
                    document: {
                      type: "string",
                      description:
                        "The full updated document in markdown format",
                    },
                  },
                  required: ["document"],
                },
              },
            },
          ],
        },
      },
      {
        type: "MESSAGES_SNAPSHOT",
        messages: [
          {
            id: "id-3",
            role: "user",
            content: "Give me a story for a dragon called Atlantis in document",
          },
          {
            id: "id-5",
            role: "assistant",
            content: "",
            toolCalls: [
              {
                id: "id-4",
                type: "function",
                function: {
                  name: "write_document_local",
                  arguments: shared1,
                },
              },
            ],
          },
          {
            id: "id-7",
            role: "tool",
            content: "Document written.",
            toolCallId: "id-4",
          },
          {
            id: "id-8",
            role: "assistant",
            content: "",
            toolCalls: [
              {
                id: "id-9",
                type: "function",
                function: {
                  name: "confirm_changes",
                  arguments: "{}",
                },
              },
            ],
          },
          {
            id: "id-12",
            role: "tool",
            content: '{"accepted":true}',
            toolCallId: "id-9",
          },
          {
            id: "id-13",
            role: "assistant",
            content: "Done! I've completed that for you.",
            toolCalls: [],
          },
          {
            id: "id-16",
            role: "user",
            content: "Change dragon name to Lola",
          },
          {
            id: "id-18",
            role: "assistant",
            content: "",
            toolCalls: [
              {
                id: "id-17",
                type: "function",
                function: {
                  name: "write_document_local",
                  arguments: shared3,
                },
              },
            ],
          },
          {
            id: "id-20",
            role: "tool",
            content: "Document written.",
            toolCallId: "id-17",
          },
          {
            id: "id-21",
            role: "assistant",
            content: "",
            toolCalls: [
              {
                id: "id-22",
                type: "function",
                function: {
                  name: "confirm_changes",
                  arguments: "{}",
                },
              },
            ],
          },
          shared27,
          shared23,
        ],
      },
      {
        type: "RUN_FINISHED",
        threadId: "id-1",
        runId: "id-27",
      },
    ],
    interactWithAgentAndRejectAskedChanges: [
      shared15,
      shared22,
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: '{"document":"Once up',
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "on a time, in a land",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: " far away, there liv",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "ed a magnificent dra",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "gon named Atlantis. ",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "Atlantis was known t",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "hroughout the realm ",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "for its shimmering s",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "cales that reflected",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: " the light of a thou",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "sand stars. The drag",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "on Atlantis would so",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "ar above the mountai",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "ns, breathing fire t",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "hat lit up the night",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: " sky. Villagers woul",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "d gather to watch At",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "lantis perform its a",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "erial dances, marvel",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "ing at the grace of ",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: "this ancient creatur",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-4",
        delta: 'e."}',
      },
      {
        type: "TOOL_CALL_END",
        toolCallId: "id-4",
      },
      shared21,
      shared8,
      shared13,
      {
        type: "RUN_FINISHED",
        threadId: "id-1",
        runId: "id-10",
      },
      shared11,
      {
        type: "TEXT_MESSAGE_START",
        messageId: "id-13",
        role: "assistant",
      },
      shared25,
      {
        type: "TEXT_MESSAGE_CONTENT",
        messageId: "id-13",
        delta: " that for you.",
      },
      {
        type: "TEXT_MESSAGE_END",
        messageId: "id-13",
      },
      shared9,
      shared12,
      {
        type: "RUN_FINISHED",
        threadId: "id-1",
        runId: "id-14",
      },
      shared7,
      shared20,
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: '{"document":"Once up',
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: "on a time, in a land",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: " far away, there liv",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: "ed a magnificent dra",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: "gon named Lola. Lola",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: " was known throughou",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: "t the realm for its ",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: "shimmering scales th",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: "at reflected the lig",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: "ht of a thousand sta",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: "rs. The dragon Lola ",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: "would soar above the",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: " mountains, breathin",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: "g fire that lit up t",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: "he night sky. Villag",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: "ers would gather to ",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: "watch Lola perform i",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: "ts aerial dances, ma",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: "rveling at the grace",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: " of this ancient cre",
      },
      {
        type: "TOOL_CALL_ARGS",
        toolCallId: "id-17",
        delta: 'ature."}',
      },
      {
        type: "TOOL_CALL_END",
        toolCallId: "id-17",
      },
      shared19,
      shared6,
      shared10,
      {
        type: "RUN_FINISHED",
        threadId: "id-1",
        runId: "id-23",
      },
      {
        type: "RUN_STARTED",
        threadId: "id-1",
        runId: "id-24",
        protocolVersion: "1.0",
        input: {
          threadId: "id-1",
          runId: "id-24",
          protocolVersion: "1.0",
          state: shared16,
          messages: [
            {
              id: "id-18",
              role: "assistant",
              content: "",
              toolCalls: [
                {
                  id: "id-17",
                  type: "function",
                  function: {
                    name: "write_document_local",
                    arguments: shared3,
                  },
                },
              ],
            },
            {
              id: "id-20",
              role: "tool",
              content: "Document written.",
              toolCallId: "id-17",
            },
            {
              id: "id-21",
              role: "assistant",
              content: "",
              toolCalls: [
                {
                  id: "id-22",
                  type: "function",
                  function: {
                    name: "confirm_changes",
                    arguments: "{}",
                  },
                },
              ],
            },
            shared24,
          ],
          tools: [
            {
              name: "confirm_changes",
              description: "",
              parameters: {
                type: "object",
                properties: {},
              },
            },
            {
              name: "write_document",
              description:
                "Present the proposed changes to the user for review",
              parameters: {
                type: "object",
                properties: {
                  document: {
                    type: "string",
                    description: "The full updated document in markdown format",
                  },
                },
                required: ["document"],
              },
            },
          ],
          context: [],
          forwardedProps: {},
        },
      },
      {
        type: "TEXT_MESSAGE_START",
        messageId: "id-26",
        role: "assistant",
      },
      shared26,
      {
        type: "TEXT_MESSAGE_CONTENT",
        messageId: "id-26",
        delta: " that for you.",
      },
      {
        type: "TEXT_MESSAGE_END",
        messageId: "id-26",
      },
      {
        type: "STATE_SNAPSHOT",
        snapshot: {
          messages: [
            {
              content:
                "Give me a story for a dragon called Atlantis in document",
              additional_kwargs: {
                type: "human",
              },
              response_metadata: {},
              type: "human",
              name: null,
              id: "id-3",
            },
            {
              content: "",
              additional_kwargs: {
                invalid_tool_calls: [],
                usage_metadata: null,
              },
              response_metadata: {
                model_provider: "openai",
                finish_reason: "tool_calls",
                model_name: "gpt-4.1-mini",
              },
              type: "ai",
              name: null,
              id: "id-5",
              tool_calls: [
                {
                  name: "write_document_local",
                  args: {
                    document: shared4,
                  },
                  id: "id-4",
                  type: "tool_call",
                },
              ],
              invalid_tool_calls: [],
              usage_metadata: null,
            },
            {
              content: "Document written.",
              additional_kwargs: {},
              response_metadata: {},
              type: "tool",
              name: null,
              id: "id-7",
              tool_call_id: "id-4",
              artifact: null,
              status: "success",
            },
            {
              content: "",
              additional_kwargs: {
                invalid_tool_calls: [],
                usage_metadata: null,
              },
              response_metadata: {},
              type: "ai",
              name: null,
              id: "id-8",
              tool_calls: [
                {
                  name: "confirm_changes",
                  args: {},
                  id: "id-9",
                  type: "tool_call",
                },
              ],
              invalid_tool_calls: [],
              usage_metadata: null,
            },
            {
              content: '{"accepted":true}',
              additional_kwargs: {
                type: "tool",
              },
              response_metadata: {},
              type: "tool",
              name: null,
              id: "id-12",
              tool_call_id: "id-9",
              artifact: null,
              status: "success",
            },
            {
              content: "Done! I've completed that for you.",
              additional_kwargs: {
                invalid_tool_calls: [],
                usage_metadata: null,
              },
              response_metadata: {
                model_provider: "openai",
                finish_reason: "stop",
                model_name: "gpt-4.1-mini",
              },
              type: "ai",
              name: null,
              id: "id-13",
              tool_calls: [],
              invalid_tool_calls: [],
              usage_metadata: null,
            },
            {
              content: "Change dragon name to Lola",
              additional_kwargs: {
                type: "human",
              },
              response_metadata: {},
              type: "human",
              name: null,
              id: "id-16",
            },
            shared14,
            {
              content: "Document written.",
              additional_kwargs: {},
              response_metadata: {},
              type: "tool",
              name: null,
              id: "id-20",
              tool_call_id: "id-17",
              artifact: null,
              status: "success",
            },
            shared17,
            {
              content: '{"accepted":false}',
              additional_kwargs: {
                type: "tool",
              },
              response_metadata: {},
              type: "tool",
              name: null,
              id: "id-25",
              tool_call_id: "id-22",
              artifact: null,
              status: "success",
            },
            shared18,
          ],
          document: shared2,
          tools: [
            {
              type: "function",
              name: "confirm_changes",
              function: {
                name: "confirm_changes",
                description: "",
                parameters: {
                  type: "object",
                  properties: {},
                },
              },
            },
            {
              type: "function",
              name: "write_document",
              function: {
                name: "write_document",
                description:
                  "Present the proposed changes to the user for review",
                parameters: {
                  type: "object",
                  properties: {
                    document: {
                      type: "string",
                      description:
                        "The full updated document in markdown format",
                    },
                  },
                  required: ["document"],
                },
              },
            },
          ],
        },
      },
      {
        type: "MESSAGES_SNAPSHOT",
        messages: [
          {
            id: "id-3",
            role: "user",
            content: "Give me a story for a dragon called Atlantis in document",
          },
          {
            id: "id-5",
            role: "assistant",
            content: "",
            toolCalls: [
              {
                id: "id-4",
                type: "function",
                function: {
                  name: "write_document_local",
                  arguments: shared1,
                },
              },
            ],
          },
          {
            id: "id-7",
            role: "tool",
            content: "Document written.",
            toolCallId: "id-4",
          },
          {
            id: "id-8",
            role: "assistant",
            content: "",
            toolCalls: [
              {
                id: "id-9",
                type: "function",
                function: {
                  name: "confirm_changes",
                  arguments: "{}",
                },
              },
            ],
          },
          {
            id: "id-12",
            role: "tool",
            content: '{"accepted":true}',
            toolCallId: "id-9",
          },
          {
            id: "id-13",
            role: "assistant",
            content: "Done! I've completed that for you.",
            toolCalls: [],
          },
          {
            id: "id-16",
            role: "user",
            content: "Change dragon name to Lola",
          },
          {
            id: "id-18",
            role: "assistant",
            content: "",
            toolCalls: [
              {
                id: "id-17",
                type: "function",
                function: {
                  name: "write_document_local",
                  arguments: shared3,
                },
              },
            ],
          },
          {
            id: "id-20",
            role: "tool",
            content: "Document written.",
            toolCallId: "id-17",
          },
          {
            id: "id-21",
            role: "assistant",
            content: "",
            toolCalls: [
              {
                id: "id-22",
                type: "function",
                function: {
                  name: "confirm_changes",
                  arguments: "{}",
                },
              },
            ],
          },
          shared24,
          shared23,
        ],
      },
      {
        type: "RUN_FINISHED",
        threadId: "id-1",
        runId: "id-27",
      },
    ],
  },
);
