import { defineEventTrace } from "../../event-trace-test";

// Generated by the event trace updater.
// Reason: Native Python raw V3 capture audited against forced-V2 references after tool-result recovery. Native task/checkpoint channels are unavailable at the pinned runtime: no synthetic step events; final business state, messages and tool payloads verified. Native message metadata and legacy callback timing differ. Unexecuted journeys preserved.
// Before accepting changes, verify whether the implementation regressed.
export const v1AgenticChatPageEventTrace = defineEventTrace(import.meta.url, {
  langgraphPythonSendsAndReceivesAMessage: [
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-2",
      protocolVersion: "1.0",
      input: {
        threadId: "id-1",
        runId: "id-2",
        protocolVersion: "1.0",
        state: {},
        messages: [
          {
            id: "id-3",
            role: "user",
            content: "Hi",
          },
        ],
        tools: [],
        context: [],
        forwardedProps: {},
      },
    },
    {
      type: "TEXT_MESSAGE_START",
      messageId: "id-4",
      role: "assistant",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: "Hello! How can I ass",
    },
    {
      type: "TEXT_MESSAGE_CONTENT",
      messageId: "id-4",
      delta: "ist you today?",
    },
    {
      type: "TEXT_MESSAGE_END",
      messageId: "id-4",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            content: "Hi",
            additional_kwargs: {
              type: "human",
            },
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-3",
          },
          {
            content: "Hello! How can I assist you today?",
            additional_kwargs: {},
            response_metadata: {
              model_provider: "openai",
              usage: {},
            },
            type: "ai",
            name: null,
            id: "id-4",
            tool_calls: [],
            invalid_tool_calls: [],
            usage_metadata: null,
            tool_call_chunks: [],
          },
        ],
        copilotkit: {
          actions: [],
        },
        "ag-ui": {
          tools: [],
          context: [],
        },
      },
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: "Hi",
        },
        {
          id: "id-4",
          role: "assistant",
          content: "Hello! How can I assist you today?",
          toolCalls: [],
        },
      ],
    },
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-5",
    },
  ],
});
