name: unit

on:
  push:
    branches: [main]
    paths:
      - "sdks/community/java/**"
      - ".github/workflows/unit-java-sdk.yml"
  pull_request:
    branches: [main]
    paths:
      - "sdks/community/java/**"
      - ".github/workflows/unit-java-sdk.yml"

jobs:
  java:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: sdks/community/java

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"

      - name: Run tests
        run: mvn -B -ntp test
