name: unit-nim-sdk

on:
  push:
    branches: [main]
    paths:
      - "sdks/nim/**"
      - ".github/workflows/unit-nim-sdk.yml"
  pull_request:
    branches: [main]
    paths:
      - "sdks/nim/**"
      - ".github/workflows/unit-nim-sdk.yml"

jobs:
  nim:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Nim
        uses: jason-v-p/setup-nim-action@v1
        with:
          nim-version: '1.6.0'

      - name: Install dependencies
        working-directory: sdks/nim
        run: nimble install -y

      - name: Run tests
        working-directory: sdks/nim
        run: nimble test
